- README.md
I change the title from "Expert-driven recommendation system" to "Collaborative content recommendation".
Also changed the image of Tournesol
> Update README.md + added link to Tournesol.app

- frontend/src/components/EmailAddVerifyAlert.js
> Updated the Email Verify Alert

- .github/workflows/ci.yml
- .gitignore
- Dockerfile
- README.md
- backend/django_react/settings.py
- debug_export.sh
- docker/Dockerfile
- launch_debug.sh
- pkglist.txt
- setup.sh
- tests.sh
> Create a Dockerfile and update README accordingly

- backend/backend/youtube_search.py
> Disable "search via youtube" functionality

- backend/backend/ml_model/client_server/database_learner.py
Should fix the locking error from #99
> Run updates in per-video transactions

- backend/backend/ml_model/config/featureless_config.gin
> Do not load the model on training start

- frontend/src/components/EmailDomains.js
The API has been removed for this, so the titles are now useless
> Remove titles for pending and rejected emails domains

- frontend/src/components/PrivacyPolicy.js
> fix the HTML formatting of privacy policy page

- backend/backend/ml_model/config/featureless_config_hparam_search.gin
- backend/backend/ml_model/helpers.py
- backend/backend/ml_model/preference_aggregation_featureless.py
- backend/backend/ml_model/preference_aggregation_featureless_tf_sparse.py
- backend/backend/tests/test_aggregator_featureless_hardcoded.py
- notebooks/.gitignore
- notebooks/analyze_hparam_search_videos.ipynb
- notebooks/tf_sinh.ipynb
- The loss is implemented in backend/backend/ml_model/preference_aggregation_featureless_tf_sparse.py
- Parallel coordinates plot is done, see the Drive for results
- Disabled (see below) until the function is fixed, see #88 
```python
sp = tf.math.softplus(theta_vw_y)
```
> Implement sinh loss #88

- infra/ansible/roles/django/handlers/main.yml
- infra/ansible/roles/frontend/handlers/main.yml
- infra/ansible/roles/frontend/tasks/main.yml
As does the back end.
I also added some " style " in the alerts to put an emphasis on the host name affecter by the deployment.
> feat: front end deployments now generate alerts

- backend/core/admin.py
Among the features brought by the standard `UserAdmin`, it provides a search bar to find users by email address.
This will help with the manual operations that are required by #232.
> Update UserAdmin config to help maintenance and support on user accounts

- backend/core/admin.py
* Domains can be filtered by `status`, and the `status` can updated directly from the list.
* The search bar allows to filter by domain (or any substring of `domain`)
* It's possible to select multiple domains to mark them as "accepted" or "rejected" all at once, via the "action" menu:
> Update EmailDomainAdmin for easier editing by admins

- frontend/src/features/account/accountAPI.ts
- frontend/src/features/settings/account/DeleteAccountForm.tsx
- frontend/src/pages/settings/account/Account.tsx
https://github.com/tournesol-app/tournesol/issues/195
> Front: Delete account

- infra/ansible/roles/frontend/handlers/main.yml
- infra/ansible/roles/frontend/tasks/main.yml
> Fix not updating frontend when deploying

- backend/ml/management/commands/ml_train.py
> Fix models import in ml_train

- backend/tournesol/tests/test_api_video.py
- backend/tournesol/views/video.py
It has been noticed that requests to `/video/` could be relatively slow in production (~ 1.5 seconds). It's mostly due to how all `VideoCriteriaScore` items need to fetched in this loop:
https://github.com/tournesol-app/tournesol/blob/7c20129409a8bd41acab62badee2afd713468717/backend/tournesol/views/video.py#L78-L80
There are currently more than 10 000 `VideoCriteriaScore`  items. Even if `prefetch_related` allows them to be fetched in a single SQL query, instantiating these objects in Python has a significant overhead. And it would get worse as the number of videos on the platform increases.
This branch suggests to compute the total score in Postgres, and only fetch the details about the criteria scores that are actually needed in the response.
On my local environment the response times …
> Optimize video list query by computing the total score in the database

- backend/tournesol/tests/test_api_user.py
- backend/tournesol/tests/test_exports.py
- backend/tournesol/urls.py
- backend/tournesol/views/exports.py
- backend/tournesol/views/user.py
Part of the backend for ticket: #273
> Add endpoint for downloading all comparisons as a CSV

- infra/ansible/roles/postgresql/templates/discord-postgres-backup-fail-alert.sh.j2
- infra/ansible/roles/postgresql/templates/pg-backups.service
- infra/ansible/roles/postgresql/templates/pg_backup.config.j2
- infra/ansible/roles/postgresql/templates/pg_backup_rotated.sh.j2
A few issues that went unnoticed in #237.   
My bad :flushed:
> Fix backup config for Postgres database

- backend/tournesol/tests/test_api_video.py
- backend/tournesol/urls.py
- backend/tournesol/views/comparison.py
- backend/tournesol/views/ratings.py
- backend/tournesol/views/video.py
- backend/tournesol/views/video_rate_later.py
- frontend/scripts/openapi.yaml
* Use default pagination in VideoViewSet
* Remove Update and Destroy from VideoViewSet
* Fix warning about duplicated operation_id
* Fix warnings about missing .queryset
* Renamed ComparisonListOnlyApi -> ComparisonListFilteredApi
> Multiple improvements in Swagger docs

- tests/cypress/integration/tournesolProfilePage.spec.ts
- tests/cypress/support/commands.js
The tests ensure a user :
- can change its username
- cannot login with its previous username
- can login with its new username
- cannot use a username already taken
> e2e: add tests for the change username flow

- frontend/src/features/frame/components/sidebar/Footer.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/pages/home/Home.tsx
* Remove privacy policy and Navigation on HomePage
* Add a Footer in the sidebar with useful links
> feat(frontend): SideBar's Footer

- frontend/src/components/ContentHeader.tsx
- frontend/src/features/frame/Frame.tsx
- frontend/src/index.css
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/pages/settings/account/Account.tsx
- frontend/src/theme.ts
* backgroundColor of ContentHeader same as SideBar
* secondary color set to blue(#506AD4)
* main backgroundColor set to white (#ffffff)
> style(frontend): Color improvements

- frontend/src/features/video_selector/VideoSelector.tsx
- frontend/src/features/videos/VideoCard.tsx
- frontend/src/features/videos/VideoThumb.tsx
Link issue : https://github.com/tournesol-app/tournesol/issues/276
You were right @amatissart , parameter `light` get the upper hand on `playing`
> Play Video with one click

- frontend/public/index.html
> Define public description

- backend/tournesol/admin.py
- backend/tournesol/models/video.py
* link_to_youtube moved to Video model
* link_to_youtube opens a new tab
* Clean-up ContributorRating admin
* CR admin displays and can filter on is_public
> Improvements to ContributorRatings admin

- backend/documentation/python_dependency.md
- backend/requirements.txt
- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_video.py
- backend/tournesol/views/video.py
Linked issue : https://github.com/tournesol-app/tournesol/issues/282
This PR tackles steps 1 and 2
> Back: add duration of video

- frontend/src/features/settings/profile/ProfileForm.tsx
It's like #340 but for the `ProfileForm` component.
> [front] feat: make ProfileForm disabled during HTTP requests

- backend/tournesol/tests/test_api_video.py
- backend/tournesol/views/video.py
For some videos, such as [this one](https://www.youtube.com/watch?v=JMpuxLIgjPs), the `viewCount` is not provided by Youtube. So this field needs to be considered as optional when parsing the API response.
This PR also simplifies a bit the implementation of `POST /video/`, to take advantage of the mechanism provided by the DRF mixins that were already defined. Especially, this makes sure that the Youtube API is not called before the request data has been properly validated.
> fix(backend): Server error on video creation when statistics are missing in Youtube API response

- backend/.gitignore
- backend/README.md
- backend/requirements.txt
- backend/tests/requirements.txt
Linked issue : https://github.com/tournesol-app/tournesol/issues/240
I added a new dependency with enable the building of html report.
Provided with the good command, tests results are very clear.
> Add documentation for testing

- backend/tournesol/tests/test_exports.py
- backend/tournesol/urls.py
- backend/tournesol/views/exports.py
- frontend/src/pages/home/Home.tsx
- frontend/src/pages/home/PublicDownloadSection.tsx
> API endpoint to download public data (Completed)

- frontend/src/features/videos/VideoCard.tsx
- frontend/src/utils/video.ts
Warning: this PR needs to be merged first : https://github.com/tournesol-app/tournesol/pull/318
Linked issue : https://github.com/tournesol-app/tournesol/issues/282
This PR tackles steps 3 and 4.
> Front : Display video duration

- frontend/src/pages/about/About.tsx
Edits to Polyconseil's descrtiption according to @Laure-tech 's recommendations
> fix: Changes to Polyconseil description

- frontend/src/features/frame/components/topbar/TopBar.tsx
- frontend/src/pages/videos/VideoRecommendation.tsx
> Reset offset on Keyword search

- frontend/src/App.tsx
- frontend/src/features/login/Login.spec.tsx
- frontend/src/features/login/Login.tsx
- frontend/src/features/login/PrivateRoute.spec.tsx
- frontend/src/features/login/PrivateRoute.tsx
- frontend/src/features/login/PublicRoute.spec.tsx
- frontend/src/features/login/PublicRoute.tsx
* Create PublicRoute component
* Add tests for PublicRoute component
* Move usage of refresh token from Login to PublicRoute
* Reorganize a few imports
Closes #323
> fix: Improve automatic login from refresh token

- backend/README.md
- backend/settings/settings.py
- backend/tournesol/tests/test_exports.py
- backend/tournesol/views/exports.py
- dev-env/docker-compose.yml
- infra/ansible/roles/django/handlers/main.yml
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/restore/tasks/main.yml
> feat(backend): Adds caching to ExportPublicComparisonsView

- browser-extension/addTournesolRecommendations.js
- browser-extension/manifest.json
> [extension] Recommandations load faster

- browser-extension/utils.js
When the user was not connected to Tournesol, it received two consecutive alert asking him to connect. This fixes the issue.
> [extension] Fix a double alert bug

- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/components/sidebar/SideBar.tsx
Discussed live with @GresilleSiffle , We think that makes the recommendation page more useful
> [front] Default recency set to 'month' in recommendations

- backend/core/locale/fr/LC_MESSAGES/django.po
- backend/core/serializers/user.py
- backend/tournesol/tests/test_api_user.py
> [backend] feat: Reject username with '@' on register and profile update

- frontend/src/pages/home/ExtensionSection.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/utils/extension.ts
> [front] fix: link to web extension on rate later page adapts to browser

- infra/README.md
- infra/ansible/roles/base/tasks/main.yml
- infra/base-image/fetch-debian-image.sh
In the context of the #372 (Nginx compression), I made a separate PR for this. Personally I have had much fewer problems by renting a cloud server than by using a VM (problems with ansible, and creating/configuring the VM). And it is much more comfortable, since my computer is not slowed and I don't have to remake all the ansible process after a restart.
So I wanted to indicate this (maybe obvious) alternative for others. Tell me if you think it is an improvement. 
Also, there was a missing dependency for rsync.
> Infra readme

- frontend/package.json
- frontend/yarn.lock
see: https://github.com/advisories/GHSA-r683-j2x4-v87g
> [front] sec: upgrade i18next-http-backend from 1.3.1 to 1.3.2

- CONTRIBUTING.md
> Add a section about translation in CONTRIBUTING

- frontend/src/features/settings/account/EmailAddressForm.tsx
- frontend/src/features/settings/account/PasswordForm.tsx
- frontend/src/pages/settings/account/Account.tsx
Linked to https://github.com/tournesol-app/tournesol/issues/306
https://user-images.githubusercontent.com/3254286/151596898-709aa87b-590e-4826-bae3-cd2333e36106.mp4
> Clean Account Settings Layout

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/about/About.tsx
> Add link to Donate on About page

- backend/tournesol/tests/test_api_comparison.py
I just saw few tests were missing the comparisons API test case, and add free time today : )
> [back] tests: add PUT & DELETE methods tests for the comparisons API

- frontend/src/components/CollapseButton.tsx
- frontend/src/features/ratings/RatingsFilter.tsx
- frontend/src/features/recommendation/SearchFilter.tsx
- frontend/src/utils/constants.ts
- frontend/tsconfig.json
Linked issue : https://github.com/tournesol-app/tournesol/issues/484
Here is a first draft of the issue. For the moment, the Badge is useful only on recommendation page.
> Add Badge on the expand Button when at least one filter is active

- backend/tournesol/models/criteria.py
- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_polls.py
- backend/tournesol/urls.py
- backend/tournesol/views/polls.py
Implements item **(1)** in #529
The response includes the list of criterias, with labels in the current language (derived from request headers).
```json
{
"name": "videos",
"criterias": [
{
"name": "largely_recommended",
"label": "Devrait être largement recommandé",
"optional": false
},
{
"name": "reliability",
"label": "Fiable & non trompeur",
"optional": true
},
{
"name": "pedagogy",
"label": "Clair & pédagogique",
"optional": true
},
{
"name": "importance",
"label": "Important & actionnable",
"optional": true
},
{
"name": "layman_friendly",
"label": "Accessible aux non-spécialistes",
"optional": true
},
{
"name": "entertaining_relaxing",
"label": "Divertissant & relaxant",
"optional": true
},
{
"name": "engaging",
"label": "Stimulant & suscite la réflexion",
"optional": true
},
{ …
```
> Implement API to fetch poll details

- frontend/scripts/openapi.yaml
I ran the update schema command in order to avoid adding code to future pull requests non related to their initial topic.
> [front] feat: add /entities/ OpenAPI schema

- backend/tournesol/models/poll.py
- backend/tournesol/serializers/comparison.py
- backend/tournesol/tests/test_api_comparison.py
A validation that should have been implemented in #560
> Reject comparison when non-optional criteria is missing

- frontend/src/features/comparisons/Comparison.tsx
See https://github.com/tournesol-app/tournesol/pull/584#discussion_r811236108
> [front] refactor: use classic `const` instead of `useMemo` for URL params

- frontend/scripts/openapi.yaml
- frontend/src/features/videos/VideoCard.spec.tsx
> Sync OpenAPI schema, adjust unit tests

- browser-extension/addTournesolRecommendations.js
- browser-extension/manifest.json
close #519 
**follows the work of the pull request** #614 
---
less code less bug
This pull request also increases the patch version of the extension from `2.1.4` to `2.1.5`.
> [extension] refactor: use scores from API instead of computing them

- frontend/src/pages/videos/VideoRecommendation.spec.tsx
- frontend/src/pages/videos/VideoRecommendation.tsx
- tests/cypress/integration/frontend/recommendationsPage.ts
> Fix backward navigation on recommendations page

- frontend/public/index.html
- frontend/src/features/frame/components/topbar/PollSelector.tsx
- tests/cypress/integration/frontend/recommendationsPage.ts
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/4726554/157643900-c244cef8-436c-4010-bd9a-14303c1bd6f8.png)|![image](https://user-images.githubusercontent.com/4726554/157643947-2a2e37b8-9c64-4e31-a464-a3a43e85004a.png)|
> Make 'Tournesol' title bolder

- frontend/src/features/videos/VideoCard.tsx
I am not sure if this makes something worse. I tested mobile (from webbrowser) and all pages. It looks better everywhere in my opinion.
Closes #495 
Closes #668
> feat: add controls on video player

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/comparisons/ComparisonSliders.tsx
- tests/cypress/integration/frontend/comparisonPage.ts
In english: **video** => **item**
In french: **vidéo** => **élément**
> Remove wording specific to videos on comparison page

- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/features/comparisons/Comparison.tsx
> [front] fix: updating comparison in a series

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
Following the recommendation on Discord.
I've done my best to keep the sentences gender-friendly in french : )
> [front] fix: incomplete dialog 6 in the `presidentielle2022` tutorial

- frontend/src/components/CriteriaIcon.spec.tsx
- frontend/src/components/CriteriaIcon.tsx
- frontend/src/components/index.ts
- frontend/src/features/comparisons/CriteriaSlider.tsx
- frontend/src/features/recommendation/CriteriaFilter.tsx
- frontend/src/utils/constants.ts
> Implement `CriteriaIcon` and use emojis for presidential criteria

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/StackedCard.tsx
- frontend/src/features/feedback/StackedCandidatesPaper.tsx
- frontend/src/features/feedback/StackedCriteriaPaper.tsx
- frontend/src/pages/personal/feedback/FeedbackPagePresidentielle2022.tsx
**related to** #740 
---
still very WIP
> [front] feat: add `StackedCriteriaPaper` component (very beautiful)

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/feedback/StackedCriteriaPaper.tsx
- frontend/src/utils/ui.ts
The content of the tweet was suggested by @aidanjungo 
The translation may need reviewing.
For each criterion, the number of emojis is between 1 and 6.
> Implement 'share on Twitter' button about most important criteria

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/comparisons/ComparisonHelper.tsx
- frontend/src/features/comparisons/ComparisonHelperPresidentielle2022.tsx
Closes #750 
Help closed:
Help open:
> feat: Add optional Comparison Helper on a poll comparison page

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/feedback/StackedCandidatesPaper.tsx
@lenhoanglnh suggested to add the option to see the ranking based on a selected criteria which I really liked 👍  Here is the implementation.
Closes #766
> feat: enable seeing candidate ranking feedback based on a selected criteria

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/LoaderWrapper.tsx
- frontend/src/features/comparisons/ComparisonList.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/pages/comparisons/ComparisonList.tsx
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/4726554/161538347-c983fd05-c9b8-47ec-9b0f-4e0c13c069c4.png)|![image](https://user-images.githubusercontent.com/4726554/161538412-3c1c974c-a47d-42fb-81b4-308796788d5d.png)
> Show "no comparison" message when 'my comparisons' page is empty

- backend/settings/settings.py
- backend/settings/urls.py
- backend/tournesol/tests/test_api_user.py
- backend/tournesol/throttling.py
- frontend/src/pages/signup/Signup.tsx
- infra/ansible/inventory.yml
- infra/ansible/roles/django/templates/settings.yaml.j2
The rate limit can be configured per environment, in Ansible inventory.
> Configure throttle on account registrations

- frontend/public/locales/fr/translation.json
The old formulation sound a bit wired to some people.
> Modif last sentence of the tweet

- infra/ansible/roles/django/templates/ml-train.service.j2
This will make the ml-train service "nicer", to reduce the load on the CPUs.
> Set nice value in ml-train service

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/polls/PollLargeButton.tsx
- frontend/src/features/polls/PollList.tsx
- frontend/src/pages/personal/feedback/FeedbackPagePresidentielle2022.tsx
**related to** #740 
---
**en**
**fr**
> [front] feat: the results page invite users to check Tournesol videos

- frontend/src/components/ChoicesFilterSection.tsx
- frontend/src/features/recommendation/DateFilter.tsx
- frontend/src/features/recommendation/SearchFilter.spec.tsx
> Make the date filter behave like radio buttons

- frontend/src/components/Pagination.tsx
- frontend/src/pages/comparisons/ComparisonList.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/pages/videos/VideoRatings.tsx
- frontend/src/pages/videos/VideoRecommendation.tsx
To have something uniform for the positions of the paginations, I change from the top to the bottom for:
- Comparisons page
- Rate Later page
> All paginations at the bottom of their pages

- backend/ml/inputs.py
Following #803, this PR completes the definition of the "supertrusted" set of users (used to initialize the scaling step of Mehestan algorithm).
In the general case, the supertrusted seed is completed with the trusted users who have compared the most entities, with a minimum of 20 distinct entities, and a maximum size of 100 supertrusted users.
> Extend supertrusted seed with trusted users having most compared entities

- backend/core/admin.py
> [back] Improve user field in admin

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/videos/VideoList.tsx
- frontend/src/utils/action.tsx
> [front] feat: Link to analysis page on VideoCard (#824)

- frontend/public/locales/fr/translation.json
As per @GresilleSiffle 's recommendation
> fix: Remove unproven claim that we are beneficial

- frontend/scripts/openapi.yaml
`yarn update-schema` has not been run recently
> [front] chore: update outdated OpenAPI schema

- dev-env/.gitignore
Files created by Docker were not ignored by Git in the Dev-Env.
Add in gitignore file their paths.
> [Dev-Env] Ignore Files from Docker in Dev-Env

- frontend/src/features/criteria/CriteriaSelector.tsx
- frontend/src/features/feedback/StackedCandidatesPaper.tsx
> [front] Refactor criteria selection dropdown menu

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/CriteriaIcon.tsx
- frontend/src/features/criteria/CriteriaSelector.tsx
- frontend/src/features/recommendation/CriteriaFilter.tsx
- frontend/src/features/recommendation/SearchFilter.spec.tsx
- tests/cypress/integration/frontend/recommendationsPage.ts
> [front] Switch Criteria Filter Mode: multiple or single criteria (#843)

- backend/twitterbot/management/commands/load_tweetinfo.py
Will be use to add to the TweetInfo all the video already tweeted by the old version of the Twitterbot.
> Add load_tweetinfo management command

- frontend/src/components/CriteriaBarChart.tsx
- frontend/src/pages/entities/CandidateAnalysisPage.tsx
Criteria bar chart on candidate analysis page for https://github.com/tournesol-app/tournesol/pull/890
> Bar chart on candidate analysis page

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/entities/CandidateAnalysisPage.tsx
> [front] style: make the criteria chart pretty

- frontend/src/components/CriteriaBarChart.tsx
Found that the scaling broke the clipping.
See: https://tournesol.app/presidentielle2022/entities/wd:Q288477
> fix: scaling does not break clipping

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/CriteriaScoreDistributions.tsx
- frontend/src/features/charts/CriteriaScoresDistribution.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
Related issue: https://github.com/tournesol-app/tournesol/issues/866
> Criteria score distribution chart

- frontend/src/features/feedback/StackedCandidatesPaper.tsx
- frontend/src/index.css
- frontend/src/pages/entities/CandidateAnalysisPage.tsx
**related to** #830
---
This PR makes the candidates' avatar clickable on the personal feedback page.
> [front] feat: in personal feedback, add a link to the analysis page

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/CriteriaBarChart.tsx
- frontend/src/components/CriteriaRadarChart.tsx
- frontend/src/components/PersonalScoreCheckbox.tsx
- frontend/src/hooks/useCriteriaChartData.ts
- frontend/src/hooks/usePersonalCriteriaScores.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
Related issue: #802 
Remaining to do:
> Add checkbox to display personal criteria scores

- frontend/src/components/entity/EntityImagery.tsx
This harmonizes the behaviour of the personal feedback page and the recommendations.
> [front] feat: candidates' avatars are clickable on recommendations

- backend/tournesol/serializers/stats.py
- backend/tournesol/tests/test_api_statistics.py
- backend/tournesol/views/stats.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/scripts/openapi.yaml
- frontend/src/features/statistics/UsageStatsSection.tsx
- frontend/src/pages/about/PublicDownloadSection.tsx
Related issue: https://github.com/tournesol-app/tournesol/issues/776
> Display stats from current poll only

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/statistics/UsageStatsSection.tsx
- frontend/src/pages/home/presidentielle2022/HomePresidentielle2022.tsx
Related issue: https://github.com/tournesol-app/tournesol/issues/935
> Display stats on presidentielle home

- browser-extension/src/addTournesolRecommendations.js
- browser-extension/src/background.js
- browser-extension/src/manifest.json
Relate to #530
I don't know how to test the browser extension. I don't know if the
changes are enough in this area. If you have any feedback thanks.
> #530 Video recommandation path in extension

- frontend/package.json
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/videos/VideoAnalysisPage.tsx
- frontend/yarn.lock
> [front] feat: add video description from YT on analysis page

- backend/tournesol/tests/test_utils_contributors.py
- backend/tournesol/utils/contributors.py
**related to** #949 
**target** `twitterbot_best_contributors`
**follows the work of** #956
> [back] perf: make the `get_top_public_contributors` faster

- frontend/src/components/entity/EntityImagery.tsx
- frontend/src/features/videos/VideoCard.tsx
- tests/cypress/integration/frontend/myRatedVideosPage.spec.ts
- tests/cypress/integration/frontend/rateLaterPage.ts
- tests/cypress/integration/frontend/recommendationsPage.ts
> [e2e] tests: ensure entities' thumbnails & title are clickable

- backend/tournesol/suggestions/graph.py
- backend/tournesol/suggestions/suggested_user_video.py
- backend/tournesol/suggestions/suggested_video.py
- backend/tournesol/tests/test_suggestions.py
Added a missing minus on the exponent of the similarity matrix computation
Simplified computation of score computation
> [back] perf: small fixes in the suggestion algorithm

- browser-extension/src/addTournesolRecommendations.js
- browser-extension/src/manifest.json
Fixes #1053
Hopefully using a simpler selector will also make it more robust.
> [ext] fix: update selector used as parent element for Tournesol recommendations

- backend/vouch/serializers.py
- backend/vouch/tests/test_api_voucher.py
- backend/vouch/views.py
> [back] fix: given and received vouchers have now the same JSON

- backend/twitterbot/settings.py
- backend/twitterbot/tests/test_tournesolbot.py
- backend/twitterbot/tournesolbot.py
> [twitterbot] refactor: tweet Tournesol link instead of YT link

- frontend/scripts/openapi.yaml
- frontend/src/pages/rateLater/RateLater.tsx
Could be merged after https://github.com/tournesol-app/tournesol/pull/1091 to include the new changes.
This PR adds the last API updates in the front end's schema definition.
As the old `RateLater` type is now `RateLaterLegacy` I updated the front end accordingly.
> [front] fix: update OpenAPI schema

- backend/tournesol/urls.py
- backend/tournesol/views/preview.py
**related to** #1080 
---
This PR is finally just a refactor of the existing preview `APIView`s, to make the code more maintainable and to be ready for the future comparison preview.
> [back] refactor: factorize common behaviour between preview `APIView`s

- backend/tournesol/models/entity_poll_rating.py
- backend/tournesol/tests/test_model_entity_poll_rating.py
> [back] tests: test the model `EntityPollRating`

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/App.tsx
- frontend/src/features/frame/components/topbar/PersonalMenu.tsx
- frontend/src/pages/personal/vouchers/CreateVoucherForm.tsx
- frontend/src/pages/personal/vouchers/GivenVouchers.tsx
- frontend/src/pages/personal/vouchers/ReceivedVouchers.tsx
- frontend/src/pages/personal/vouchers/VouchersPage.spec.tsx
- frontend/src/pages/personal/vouchers/VouchersPage.tsx
- frontend/src/pages/personal/vouchers/context.tsx
Related issue: #1058 
Remaining to do:
> [front] feat: add the vouching UI

- backend/vouch/admin.py
> [back] feat: add the admin UI for the `vouch` app

- frontend/src/pages/personal/vouchers/VouchersPage.spec.tsx
And enable type check on the whole file so that in the future mocks still match the type they are replacing.
I think having an automatic check that the mocks match the type they are simulating is worth the slightly harder to read tests because of all the type annotations.
> Update outdated voucher mocks in tests

- frontend/public/locales/fr/translation.json
This suggestion was made by @GresilleSiffle in https://github.com/tournesol-app/tournesol/pull/1127#discussion_r973694191
> [front] i18n: apply suggestion on fr message about vouch mechanism

- infra/ansible/roles/django/templates/tournesol-twitterbot.service.j2
I think a tweet on Sunday evening will have more impact than a tweet on Friday evening (which generally receive very low engagement)
> [infra] refactor: twitterbot tweets on Sunday instead of Friday

- backend/ml/inputs.py
- backend/ml/management/commands/ml_train.py
- backend/scripts/ci/lint.sh
warnings encountered:
W0107: Unnecessary pass statement (unnecessary-pass)
C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
R1720: Unnecessary "elif" after "raise", remove the leading "el" from "elif" (no-else-raise)
> PyLint warnings in ml directory (#448)

- frontend/src/pages/faq/FAQ.tsx
- frontend/src/pages/faq/FAQEntryList.tsx
This PR fixes two FAQ issues:
- the anchor links were badly formatted
- the component didn't scroll to the requested anchor
> [front] fix: FAQ anchors badly formatted

- backend/vouch/tests/test_voting_rights_algo.py
- backend/vouch/voting_rights.py
Related to #1176 
This is the first part of the required implementation. Next steps will be to include this algorithm in the ML routine such that it reads and write data from/to the database.
> [back] feat: Add algorithm to compute voting rights

- backend/tournesol/suggestions/suggestionprovider.py
I believe this does the intended and reduces the number of request. This happens at every call to the suggestion provider.
> [back] perf: reduce nbr of SQL queries in _get_user_comparability_augmenting_videos

- backend/tournesol/lib/public_dataset.py
- backend/tournesol/resources/export_readme.txt
- backend/tournesol/tests/test_exports.py
- backend/tournesol/views/exports.py
> [back] feat: add individual criteria scores to public export

- infra/README.md
> [infra] update README with instructions to explore logs in Grafana

- frontend/scripts/openapi.yaml
- frontend/src/features/entity_selector/EntityInput.tsx
> [front] feat: Use strict=false in entity selector

- frontend/src/features/frame/components/footer/Footer.tsx
- frontend/src/utils/url.ts
> Add youtube playlist link in the footer

- backend/tournesol/admin.py
- backend/tournesol/models/entity.py
- backend/twitterbot/admin.py
Special for you @GresilleSiffle 😉
> Replace link to YouTube by link to Tournesol in admin

- backend/tournesol/management/commands/load_public_dataset.py
- backend/tournesol/tests/test_load_public_dataset.py
Fixes #1328 
Adds a test case for "load_public_dataset" management command
> [back] fix: `load_public_dataset` should not expect 'weight' in public comparisons file

- CONTRIBUTING.md
P.S. I am new to open source contributions, and am all ears for feedback!
> fixed typo of kaban board to kanban

- backend/pyproject.toml
For those who use black, the line length will be set by defauld here
> [back] Set black line length in toml file

- backend/core/admin.py
1. faster load time on email domains list
2. direct link to list of users associated to each domain
> [back] optimize sql query to count users by domain

- data-visualization/requirements.txt
- data-visualization/utils.py
Streamlit improve the way its cache functions works with this new version, it should improve a bit the performances https://blog.streamlit.io/p/c0a90231-9848-47ec-a40c-ad4a344e4de1/
> [dataviz] Update streamlit to version 1.18.0

- data-visualization/pages/02_Videos_and_channels.py
- data-visualization/requirements.txt
- data-visualization/utils.py
To be merged after #1349 
New podium section with filter from the sidebar:
> [dataviz] Add a video podium and more filters in the sidebar

- data-visualization/pages/02_Videos_and_channels.py
- Add missing labels to fix Streamlit warnings
- Add option `numeric_only` to fix Pandas warning
> [dataviz] fix: Pandas and Steamlit warnings

- backend/twitterbot/tests/test_tournesolbot.py
mock.patch was imported and used in two different ways in the same script.
> [back] fix: double import in `test_tournesolbot.py`

- backend/tournesol/resources/export_readme.txt
The new doc depends on merging both #1368 and #1324
> [back] docs: explain every column of every file of the public export

- backend/README.md
- backend/documentation/settings-tournesol.yaml
Fixed little errors in the readme when setup project
> [back] docs: the install doc invites explicitly the users to configure the settings

- data-visualization/pages/01_User_comparisons.py
- data-visualization/utils.py
> [dataviz] Use new route to get `comparisons.csv` and small optim

- frontend/src/pages/home/videos/sections/research/ScientificLiteratureBox.tsx
> fix: Link to Drive instead of DropBox for sharing student works

- data-visualization/pages/03_Community_evolution.py
- data-visualization/pages/03_users_traffic_evolution.py
- data-visualization/utils.py
> add contributors metrics

- backend/tournesol/lib/public_dataset.py
- backend/tournesol/resources/export_readme.txt
- backend/tournesol/tests/test_exports.py
> [back] add uncertainties in the public dataset

- backend/tournesol/entities/video.py
- backend/tournesol/serializers/entity.py
- backend/tournesol/serializers/metadata.py
- backend/tournesol/tests/test_api_video.py
- backend/tournesol/utils/api_youtube.py
- frontend/scripts/openapi.yaml
- frontend/src/components/entity/EntityMetadata.tsx
> [back] feat: added video datetime in metadata

- backend/ml/inputs.py
- backend/settings/settings.py
- backend/tournesol/lib/public_dataset.py
- backend/tournesol/management/commands/create_dataset.py
- backend/tournesol/tests/management/test_create_dataset.py
- backend/tournesol/tests/test_exports.py
- backend/vouch/voting_rights.py
- infra/ansible/roles/django/templates/settings.yaml.j2
> [back] Include a metadata and remove root folder in the public dataset

- backend/core/tests/factories/user.py
To avoid test failures, e.g observed in https://github.com/tournesol-app/tournesol/actions/runs/4376606618/jobs/7658953366
> [back] fix potential collision in emails generated by `UserFactory` 

- CONTRIBUTING.md
- backend/settings/settings.py
- backend/tournesol/tests/test_text_search.py
- backend/tournesol/views/polls.py
- browser-extension/src/background.js
- browser-extension/src/manifest.json
- frontend/src/utils/api/recommendations.tsx
- infra/ansible/roles/postgresql/templates/pg_backup.config.j2
- infra/ansible/roles/postgresql/templates/pg_backup_rotated.sh.j2
> [back][ext] perf: truncate dates and add caching on recommendations requests

- infra/ansible/roles/django/handlers/main.yml
- infra/ansible/roles/frontend/handlers/main.yml
> [infra] Add ansible_user to the deployment notification

- browser-extension/src/addTournesolRecommendations.js
- browser-extension/src/manifest.json
- frontend/src/pages/home/banners/TempStudyBanner.tsx
The previous URLs were outdated.
> [ext][front] chore: update the URLs of the research study

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/DialogBox.tsx
- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/utils/analytics.ts
- frontend/src/utils/comparisonSeries/skip.ts
**related to** #1099
---
This PR has for goal to allow user to skip the tutorial
> [front] feat: users can skip the tutorial

- backend/tournesol/models/entity.py
- backend/tournesol/tests/test_api_rate_later.py
When 2 requests attempt to create the same video, the second creation may fail after retrieving the video metadata.
In this case, the method `create_from_video_id()` will retry to fetch the object from the database.
> [back] fix: server error when concurrent requests attempt to init the same video

- backend/tournesol/management/commands/sync_yt_playlists.py
This change will catch an error observed recently that caused "sync_yt_playlists" command to fail:
```2023-03-31 07:15:14 | googleapiclient.errors.HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&alt=json returned "Precondition check failed.". Details: "[{'message': 'Precondition check failed.', 'domain': 'global', 'reason': 'failedPrecondition'}]">```
> [back] fix: catch error about unavailable video when updating youtube playlist

- dev-env/README.md
This PR adds commands about possible error during set up and global overview of docker containers.
> [dev-env] docs: more docker commands in the readme

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/components/footer/Footer.tsx
- frontend/src/pages/about/About.tsx
- frontend/src/utils/url.ts
One more step before closing the wiki (#557)
> [front] remove links and references to wiki

- backend/tournesol/tests/factories/entity_poll_rating.py
- backend/tournesol/tests/factories/ratings.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/views/ratings.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/ratings/RatingOrderByInput.tsx
- frontend/src/utils/constants.tsx
- tests/cypress/e2e/frontend/myRatedVideosPage.cy.ts
**related to** #1259 
---
Enable sorting by personnal score and global score in the "My compared items" page
> [back][front] feat: rated entities can be sorted by tournesol score

- backend/core/management/commands/watch_account_number.py
- backend/core/tests/management/test_watch_account_number.py
- backend/core/utils/email_domain.py
**related to** #1454 
---
**to-do**
> [back] feat: add the command watch_account_number

- frontend/src/pages/faq/FAQEntryList.tsx
- frontend/src/pages/faq/FAQSingleEntry.tsx
The goal is to make the faq more readable for easier access to wanted topic
> [front] refactor: move faq questions in their own component

- backend/tournesol/serializers/poll.py
- backend/tournesol/tests/test_api_polls.py
- backend/tournesol/views/polls.py
> [back] feat: Exclude already compared in recommendations

- frontend/src/hooks/index.ts
- frontend/src/hooks/useScrollToLocation.ts
- frontend/src/pages/criteria/CriteriaPage.tsx
- frontend/src/pages/home/Home.tsx
- frontend/src/pages/home/PollListSection.tsx
- frontend/src/pages/home/videos/sections/ComparisonSection.tsx
- frontend/src/pages/home/videos/sections/FundingSection.tsx
- frontend/src/pages/home/videos/sections/SectionTitle.tsx
- frontend/src/pages/home/videos/sections/recommendations/RecommendationsSection.tsx
- frontend/src/pages/home/videos/sections/recommendations/UseOurExtension.tsx
- frontend/src/pages/home/videos/sections/research/ResearchSection.tsx
Ex:
https://tournesol.app#research now leads to the research section
> [front] feat: add id to all HomeVideos' section titles

- infra/ansible/inventory.yml
- infra/ansible/roles/mediawiki/tasks/main.yml
> [infra] chore: disable wiki URL monitoring

- backend/core/serializers/user_settings.py
- backend/core/tests/test_api_user_settings.py
- frontend/scripts/openapi.yaml
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/utils/types.ts
- frontend/src/utils/userSettings.ts
> [back] feat: add email notifications settings

- browser-extension/yarn.lock
- frontend/yarn.lock
Resolves 
- https://github.com/tournesol-app/tournesol/security/dependabot/77 (front)
-  https://github.com/tournesol-app/tournesol/security/dependabot/78 (browser-extension)
> [front][ext] chore: upgrade dependencies to resolve dependabot alert about 'word-wrap'

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/talks/TalkSingleEntry.tsx
These are usually the colors used to define a live event.
Yet, does it catch too much the eye ? Or is it ok since it is its purpose ?
> [front] feat: live chip on talk entry for ongoing talks

- frontend/src/pages/home/videos/sections/research/ScientificLiteratureBox.tsx
> [front] feat: add new research article

- tests/yarn.lock
Solves https://github.com/tournesol-app/tournesol/security/dependabot/79
> [tests] chore: upgrade e2e tests dependencies

- backend/core/serializers/user_settings.py
- backend/core/tests/test_api_user_settings.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/scripts/openapi.yaml
- frontend/src/features/settings/preferences/TournesolUserSettingsForm.tsx
- frontend/src/features/settings/preferences/VideosPollUserSettingsForm.tsx
- frontend/src/features/settings/preferences/fields/RecommendationsDefaultExcludeCompared.tsx
- frontend/src/utils/userSettings.ts
- tests/cypress/e2e/frontend/settingsPreferencesPage.cy.ts
> [back][front] feat: make `exclude_compared_entities` configurable by users

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a `PULL_REQUEST_TEMPLATE.md` to the repository.
I pasted the template in this description so we all can see how it looks like.
> doc: add a PULL_REQUEST_TEMPLATE.md file

- backend/tournesol/views/previews/recommendations.py
> fix(back) add support limit & offset params in reco preview

- browser-extension/src/manifest.json
I forgot to update the version in this PR https://github.com/tournesol-app/tournesol/pull/1730
> [ext] chore: release 3.3.0

- frontend/public/index.html
- frontend/public/locales/en/translation.json
- frontend/src/pages/about/About.tsx
- infra/ansible/roles/nginx/files/maintenance/index.html
#925 
- rename 'public utility' to 'public interest'
> [front] fix: rename 'public utility' to 'public interest'

- backend/twitterbot/settings.py
> [back] twitterbot: increase number of days before tweeting about same uploader

- tests/cypress.config.ts
- tests/cypress/e2e/frontend/comparisonPageTuto.cy.ts
> [tests] fix: attempt to fix the flaky comparisonPageTuto test

- backend/ml/mehestan/run.py
- backend/tournesol/models/poll.py
- infra/ansible/inventory.yml
Closes #1843 
---
`ml-train` will run every 3 hours at 00:20, 03:20, ..., 21:20 (UTC)
> [infra][back] run ml_train on all criteria in parallel and update schedules to compute scores every 3 hours

- infra/ansible/inventory.yml
- infra/ansible/roles/base/tasks/main.yml
- infra/ansible/roles/base/templates/hosts
- infra/ansible/roles/logging/files/loki.yml
Upgrade Loki from v2.2.1 to v2.9.2.
> [infra] chore: upgrade Loki (and more)

- browser-extension/package.json
- browser-extension/prepareExtension.js
- browser-extension/src/addVideoButtons.css
- browser-extension/src/addVideoButtons.js
- browser-extension/src/images/watch.svg
Extension update : 
On a youtube video page, add a "Watch on Tournesol" button, next to "Rate Later" and "Rate Now".
I've renamed the files and the addRateButton function to addVideoButton for a more consistent name.
Pressing the button opens a new tab on the tournesol.app/video/<id> page.
Tested on Chromium and Firefox.
> Browser extension.v3.5.0

- frontend/src/features/menus/ShareMenu.tsx
**related issues**
https://github.com/tournesol-app/tournesol/issues/1891
---
Make the share button on youtube only visible if there is a youtube link
> [front] fix: link for youtube

- backend/requirements.txt
Fix CVE-2024-27351:
- https://docs.djangoproject.com/en/4.2/releases/4.2.11/
> [back] sec: upgrade Django to 4.2.11 (from 4.2.10)

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
The Tournesol Live description should now be more accurate.
> [front] refactor: more accurate desc of Tournesol Live

- frontend/src/App.tsx
> [front] fix: redirect /action to /actions to accept the URL as it appears in the book

- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/features/tips/Tip.tsx
> [front] feat: make tutorial tips more compact on mobile

- frontend/src/components/ContentBox.tsx
- frontend/src/components/ContentHeader.tsx
|Before|After|
|--|--|
|![localhost_3000_comparison_uidA=yt%3A_Jgbni6UQig uidB=yt%3AUT7QAirORp0(iPhone SE) (1)](https://github.com/tournesol-app/tournesol/assets/4726554/14729316-3246-408c-93d6-73013e000fea)|![localhost_3000_comparison_uidA=yt%3A_Jgbni6UQig uidB=yt%3AS95i1WuZNDc(iPhone SE) (1)](https://github.com/tournesol-app/tournesol/assets/4726554/f0292587-df04-47f9-b56a-886026544016)
|![localhost_3000_users_amatissart_recommendations_date= language=(iPhone SE)](https://github.com/tournesol-app/tournesol/assets/4726554/6681a6f7-4251-48aa-8021-978561743397)|![localhost_3000_(iPhone SE)](https://github.com/tournesol-app/tournesol/assets/4726554/a30a8d17-864c-4232-94e3-cf8a2bdfcb25)
[development-guidelines]: …
> [front] update style of ContentHeader and remove fixed height

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/components/footer/Footer.tsx
The page Move to actions is now discoverable by humans : ) I added an emoji to highlight its importance.
> [front] feat: add link to page "actions" in footer

- frontend/src/pages/home/videos/sections/research/ScientificLiteratureBox.tsx
Added the GBT paper to research section in home.
Added the conference where the Mehestan paper was accepted.
---
Updated "our papers" section.
> Added 2024 papers (GBT + Mehestan)

- backend/tournesol/models/criteria.py
- backend/tournesol/tests/test_api_polls.py
- backend/tournesol/views/polls.py
Reduce the number of SQL queries from 13 to 3, on requests like `GET /polls/videos/` (very frequent).
> [back] optim: prefetch criteria locales in PollsView

- backend/requirements.txt
Upgrade Django 4.2.14 to 4.2.15.
> [back] sec: upgrade django from 4.2.14 to 4.2.15

- frontend/src/pages/home/videos/sections/research/ScientificLiteratureBox.tsx
No related issue
---
Added new research paper, in philosophy with Martin & Maxime
> Added new research paper, in philosophy with Martin & Maxime

- backend/requirements.txt
This PR fixes two CSV issues: https://docs.djangoproject.com/en/4.2/releases/4.2.16/
> [back] sec: update Django from 4.2.15 to 4.2.16

- backend/requirements.txt
Fix:
- CVE-2024-53907
- CVE-2024-53908
See: https://docs.djangoproject.com/en/4.2/releases/4.2.17/
> [back] sec: upgrade Django to 4.2.17 from 4.2.16

- frontend/public/.well-known/assetlinks.tournesol.app.json
> [front] chore: add new cert fingerprint given by Google Play Console

- backend/twitterbot/tests/test_tournesolbot.py
- backend/twitterbot/tournesolbot.py
> [back] fix: fix unbound variable in tournesolbot

- frontend/src/features/frame/components/footer/Footer.tsx
- frontend/src/utils/url.ts
- infra/ansible/roles/django/templates/tournesol-twitterbot-top-contributors.timer.j2
- infra/ansible/roles/django/templates/tournesol-twitterbot.timer.j2
The timer should not automatically trigger the Tournesol bots when it's not the moment.
> [front][infra] feat: display bluesky links + fix tournesol bot deployment

- backend/requirements.txt
This fixes a regression introduced by 4.2.18
https://docs.djangoproject.com/en/4.2/releases/4.2.19/
> [back] fix: upgrade Django to 4.2.19 from 4.2.18

- infra/ansible/roles/monitoring/tasks/main.yml
As recommended in https://github.com/grafana/grafana/issues/65115
> [infra] fix: enable wal for grafana database to reduce errors about locked db

- frontend/package.json
- frontend/yarn.lock
This branch upgrade all front end packages with `yarn upgrade`.
`mui` has been updated to its latest minor version.
> [front] chore: update mui packages

- solidago/README.md
> [solidago] add instructions to build docs locally in readme

- frontend/package.json
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/App.tsx
- frontend/src/components/ContentBox.tsx
- frontend/src/features/charts/CriteriaScoresDistribution.tsx
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/i18n.ts
- frontend/src/pages/entities/EntityAnalysisPage.tsx
- frontend/src/pages/manifesto/ManifestoPage.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/menus.tsx
- frontend/src/utils/polls/presidentielle2022.ts
- frontend/src/utils/polls/videos.tsx
- frontend/src/utils/recommendationsLanguages.ts
- frontend/src/utils/types.ts
- frontend/yarn.lock
Will be available at https://tournesol.app/manifesto in french only.
For now, no link to this page. This is still a working version, used to collect external feedback.
> [front] feat: first draft of Tournsol manifesto

- frontend/index.html
- frontend/src/pages/manifesto/ManifestoPage.tsx
> [front] add link to form on manifesto draft, tweak style

- frontend/scripts/openapi.yaml
> [front] chore: update OpenAPI schema

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/hooks/useScrollToLocation.ts
- frontend/src/pages/home/videos/sections/InstallMobileApp.tsx
- frontend/src/pages/manifesto/ManifestoPage.tsx
- frontend/src/utils/url.ts
> [front] feat: Manifesto with call to actions and collapsable sections
