- frontend/src/components/Home.js
instead of total number of video on the platform which count non rated video (in people rate later list). 
Fix issue #16
> Switch to number of rated videos

- frontend/src/components/VideoCard.js
This PR replaces the score displayed on the video cards by the fixed `tournesol_score` entry received from the backend
> Always display the tournesol score on VideoCard

- frontend/src/components/ExpertInterface/index.js
- frontend/src/components/VideoComments/index.js
This PR removes the verified email banner, because it is in very non-user friendly places. It now only appears on the home page
> Remove some verified email banners

- frontend/src/features/videos/VideoCard.tsx
- frontend/src/features/videos/VideoList.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/utils/action.tsx
This PR improve the style of the video card:
- Adds border and shadow frmo Figma's mock-up
- Changes color of Video card actions
- Changes layout of actions to be a row on small screens and a column on large screens
- Add tooltip for Video card actions
Additionally I moved the code of the actions we have, previously they were defined inside other components which makes them impossible to re-use.
Before:
After:
> Refactor actions and add style to VideoCards

- frontend/src/features/videos/VideoCard.spec.tsx
- frontend/src/features/videos/VideoCard.tsx
The number of ratings was hidden when a video was rated on a single criteria "largely_recommended". 
This PR defines specific conditions for each statistics element:
* the "Rated high" and "Rated low" criterias are displayed if these criterias are defined and are different
* the "overall score" is displayed if the criteria scores are available (e.g not on the rate later list where the criteria scores are currently not defined)
> Fix display conditions for video score and nb of ratings in VideoCard

- backend/core/serializers/email_domain.py
- backend/core/serializers/user.py
- backend/settings/settings.py
- backend/tournesol/tests/test_api_domains.py
- backend/tournesol/tests/test_api_user.py
- backend/tournesol/urls.py
- backend/tournesol/views/email_domains.py
- frontend/package.json
- frontend/scripts/openapi.yaml
- frontend/src/App.tsx
- frontend/src/features/settings/account/EmailAddressForm.tsx
- frontend/src/pages/about/TrustedDomains.tsx
- tests/cypress/integration/tournesol.spec.ts
- tests/cypress/integration/tournesolAccountPage.spec.ts
Closes #191 
* Indication about the email status on account page: "Trusted" or "Non-trusted":
A boolean `is_trusted` has been added in the response of `GET /accounts/profile/`
* A page "/about/trusted_domains" explaining the motivation for this mechanism:
A new route `GET /domains/` has been implemented to fetch the list of accepted email domains
|/settings/account| /about/trusted_domains|
|-|-|
|![Capture d’écran du 2021-11-10 15-05-42](https://user-images.githubusercontent.com/4726554/141128314-88989184-40d8-4e92-a4f5-082a5dc5447d.png)|![image](https://user-images.githubusercontent.com/4726554/141128228-775648d5-ec6a-4c00-97ec-578d1a136e9f.png)|
> Show indication about email status on account page + Add page about trusted domains

- backend/tournesol/views/video.py
I was not completely convinced with the performance gain visible on staging after deploying #284 
There is actually another easy optimization: when serializing multiple objects, `many=True` should be preferred to avoid the overhead of the serializer initialization:
See https://www.django-rest-framework.org/api-guide/serializers/#dealing-with-multiple-objects
On my local environment this brings another 3x speedup.
> Video list: avoid serializer initialization overhead with 'many=True'

- backend/tournesol/admin.py
As suggested by @aidanjungo, it should now be easier to look for a specific video, e.g in order to correct its "language".
> admin: Define list_display and search_fields in VideoAdmin

- tests/cypress/integration/tournesolAccountPage.spec.ts
I added an end-to-end to ensure the change password feature is working.
The test ensures that a user :
- can change its password
- cannot login with its previous password
- can login with its new password
> test: add an e2e test for the change password flow

- backend/requirements.txt
The upgrade fixes few bugs and regressions, mainly related to the admin interface.
See the - small - django release notes here:
- https://docs.djangoproject.com/en/3.2/releases/3.2.7/
- https://docs.djangoproject.com/en/3.2/releases/3.2.8/
- https://docs.djangoproject.com/en/3.2/releases/3.2.9/
> chore: upgrade django from 3.2.6 to 3.2.9

- frontend/src/features/settings/account/PasswordForm.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/utils/action.tsx
- frontend/src/utils/notifications.ts
Closes https://github.com/tournesol-app/tournesol/issues/269
Add multiple responses with pop to inform users that request are handled, and given them feedback on the result of their request.
- Recommendation page : alert print if video added/already exists in rate Later List.
- Rate Later List : pop-up when video deleted from rate later
- Comparison page : pop-up when comparison is submitted
> Add visual feedback for actions buttons in rate later list and comparison page

- backend/.dockerignore
- backend/dev-env/Dockerfile
- dev-env/README.md
- dev-env/docker-compose.yml
- dev-env/run-docker-compose.sh
There was now easy way to rebuild the container `tournesol-dev-api` without re-initializing the whole dev-env (for example to update the Python dependencies used by the backend).
* It's now possible to run `./run-docker-compose.sh restart` in this case. The database initialization is not executed.
* The Python requirements files are no longer duplicated in backend/ and backend/dev-env/ : the backend/ directory is used as the context to build the docker image
* Apply `shellcheck` corrections (@jstainer-kleis thanks for the tip!)
> dev-env: Implement 'restart' command to rebuild the containers while preserving the data

- browser-extension/README.md
- browser-extension/addRateLaterButton.css
- browser-extension/addRateLaterButton.js
- browser-extension/addTournesolRecommendations.js
- browser-extension/background.html
- browser-extension/background.js
- browser-extension/build.sh
- browser-extension/fetchTournesolToken.js
- browser-extension/manifest.json
- browser-extension/menu.html
- browser-extension/menu.js
- browser-extension/utils.js
- tests/cypress/integration/extension.spec.ts
Related to #225 
* Back to Manifest v2, as Firefox does not support v3 yet
https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/
https://bugzilla.mozilla.org/show_bug.cgi?id=1578284
* More robust access token handling:
* The token is fetched from extension storage on each request to the API
* The token is updated in the extension storage during navigation on tournesol.app, without explicit reload. 
* Error handling and feedback in UI: buttons are disabled after the first error, error messages are visible on most actions.
* A few cosmetic changes in the popup:
> Browser extension: compatibility with Manifest v2 and Firefox

- frontend/src/App.test.tsx
- frontend/src/features/frame/components/sidebar/Footer.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/features/frame/components/topbar/AccountInfo.tsx
- frontend/src/features/frame/components/topbar/TopBar.tsx
- frontend/src/pages/home/ContributeSection.tsx
- frontend/src/pages/home/ExtensionSection.tsx
- frontend/src/pages/home/Home.tsx
- frontend/src/theme.ts
Changes to the HomePage based on PolyConseil's feedback.
Next steps may be to include the comparison interface and correctly handle signing up the user when a comparison is submitted. Currently clicking "compare videos now" leads to the login/signup page
> feat: Extensions and Contribute sections on home page

- backend/ml/management/commands/ml_train.py
- backend/tournesol/migrations/0013_create_all_contributor_ratings.py
- backend/tournesol/migrations/0014_create_all_contributor_ratings.py
- backend/tournesol/models/video.py
- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/views/comparison.py
- backend/tournesol/views/ratings.py
Related to #274 
The boolean `is_public` was already defined in `ContributorRating`. This flag represents whether the contributions of a user related to a specific video should be public (included to the public dataset, associated with the username), or private (only used to compute aggregated scores, without publishing the details about the ratings, comparisons, etc.).
* `is_public` can be updated via  `PATCH /users/me/contributor_ratings/<video_id>/`
* `ContributorRating` objects, related to the pair (user, video) will be created when a new comparison is submitted, if the relevant objects don't exist yet. For now, the default value for `is_public` is always "false".
* A custom migration has been implemented to create missing `ContributorRating` objects, related to all `Comparisons` that …
> Extend API to handle `is_public` update in ContributorRating

- frontend/src/features/frame/components/topbar/AccountInfo.tsx
- frontend/src/features/login/loginAPI.ts
- frontend/src/utils/notifications.ts
Fixes #194 
I added a `logoutProcess` function, in the login / logout component, responsible of calling all logout routines. At the moment there are only two steps: revoking the token, and logout the currently logged user.
Django OAuth Toolkit doc: https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_04.html?highlight=revoke#setup-a-request
> (#194) [front] feat: revoke access token at logout

- tests/yarn.lock
Dependencies upgraded with `yarn upgrade` in ./tests/
> chore(tests): Upgrade dependencies to solve GitHub warnings about vulnerability

- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/views/ratings.py
:warning: Depends on #315 
* New endpoint `POST /users/me/contributors_ratings/` to initialize a rating about a specific video, with an optional `is_public` preference.  
This endpoint will typically be called before a user submits their first comparison about a video.
* The `ContributorRating` serializers include a new field `n_comparisons` (= the count of comparisons by the authenticated user about the current video)
> feat(backend): Implement ContributorRating initialization endpoint

- backend/settings/settings.py
- backend/tournesol/tests/test_api_video.py
- backend/tournesol/views/video.py
* The parameter `video_id` was not correctly defined as a string for route `GET /video/{video_id}/`.
The attribute [`lookup_field`](https://www.django-rest-framework.org/api-guide/generic-views/#attributes) is defined in `VideoViewSet` to take advantage of DRF mixins.
* All query parameters to filter videos recommendations are now defined explicitly in the schema.
> fix(backend): Fix OpenAPI schema for `VideoViewSet`

- backend/tournesol/tests/test_api_video.py
- backend/tournesol/views/video.py
If multiple tags on the same video matches the "search" query, the `criteria_scores` were counted multiple times, leading to a wrong value for `total_score`, and incorrect order in the results.
This is due to how `tags` is defined as a `ManyToManyField`: filtering on tags may cause several instances of the same video to be included in the queryset before the aggregation of scores is computed.
This change makes sure that each `VideoCriteriaScore` is counted only once for each video.
> fix(backend): Incorrect video list order when a video matches 'search' query on multiple tags

- frontend/src/features/settings/account/PasswordForm.spec.tsx
- frontend/src/features/settings/account/PasswordForm.tsx
This PR adds a little improvment to `PasswordForm` component UI/UX.
The submit button is now disabled when an HTTP request is processing, as is the submit button of the login form. The tests have been updated accordingly.
Disabling the submit button adds a visual hint indicating that something is going on in the background and informs the user that his/her action has been correctly submitted.
It also prevents users to click several time in a row on the submit button and might prevent unexpected API or UI behaviours.
I also made a similar PR for the `ProfileForm` here: #341
> [front] feat: make PasswordForm disabled during HTTP requests

- frontend/src/components/filter/ChoicesFilterSection.tsx
- frontend/src/components/filter/FilterSection.tsx
- frontend/src/components/index.ts
- frontend/src/features/recommendation/CriteriaFilter.tsx
- frontend/src/features/recommendation/DateFilter.tsx
- frontend/src/features/recommendation/LanguageFilter.tsx
- frontend/src/features/recommendation/SearchFilter.tsx
- frontend/src/pages/videos/VideoRecommendation.tsx
This is a prerequisite to implement the new page "My rated videos", that will also include similar filters (on public/private ratings, etc.)
2 new components: 
* **`FilterSection`**: a generic filter section with an underlined title
* **`ChoicesFilterSection`**: a filter column, with multiple checkboxes defined by a list of `choices`.   
Used by `LanguageFilter` and `DateFilter`.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/4726554/144819193-83da4a88-fd88-4263-ad82-2fa6533c84d4.png)|![image](https://user-images.githubusercontent.com/4726554/144819305-cfae78b0-8c4c-4bb3-a65a-e30b13f070d9.png)
|![image](https://user-images.githubusercontent.com/4726554/144819685-2b107c67-730c-4667-9438-dd68c20a2414.png)|![image](https://user-images.githubusercontent.com/4726554/14 …
> refactor(frontend): Define reusable components for search filters, tweak appearance

- frontend/public/index.html
- infra/ansible/roles/frontend/templates/.env.j2
Following #350, as some platforms such as Twitter does not support relative URLs in meta tags.
> frontend: Use absolute URL in meta tags, with explicit 'PUBLIC_URL' on build

- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/urls.py
- backend/tournesol/views/ratings.py
Related to #274 
The new route `PATCH /users/me/contributor_ratings/_all/`  will be used on the page "My rated videos" to allow marking of all existing user contributions as "public" or "private".
> feat(backend): Implement route to update is_public status for all ContributorRating

- tests/cypress/integration/extension.spec.ts
The default timeout is 4000ms. It seems to be too low to load a video page completely on CI machines.  
And using a larger timeout is preferable to calling `cy.wait()` explicitly as it was done in one of the test case.
> e2e: Fix flaky test case with higher timeout for cypress commands in extension.spec.ts

- frontend/package.json
- frontend/scripts/openapi.yaml
- frontend/src/features/rateLater/rateLaterAPI.ts
- frontend/src/features/recommendation/RecommendationApi.tsx
- frontend/src/features/settings/account/EmailAddressForm.tsx
- frontend/src/features/settings/account/PasswordForm.tsx
- frontend/src/features/settings/profile/ProfileForm.tsx
- frontend/src/features/video_selector/VideoSelector.tsx
- frontend/src/features/videos/PublicStatusAction.tsx
- frontend/src/features/videos/VideoApi.tsx
- frontend/src/pages/about/TrustedDomains.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/pages/comparisons/ComparisonList.tsx
- frontend/src/pages/login/ForgotPassword.tsx
- frontend/src/pages/login/ResetPassword.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/pages/signup/Signup.tsx
- frontend/src/pages/signup/Verify.tsx
- frontend/src/pages/videos/VideoRecommendation.tsx
- frontend/src/utils/action.tsx
- frontend/src/utils/string.spec.ts
- frontend/src/utils/string.ts
- frontend/src/utils/video.ts
Now that the `/video/` endpoints are correctly described in the schema (#332), the corresponding routes can be called using the generated client. However, `openapi-typescript-codegen` uses unnamed arguments by default. It would make the usage of this endpoint (currently with 16 optional query parameters) very impractical.
That's why this PR sets [`--useOptions`](https://github.com/ferdikoomen/openapi-typescript-codegen#argument-style-vs-object-style---useoptions) in the "openapi" command line, to use options objects as arguments: parameters must be named explicitly, and no specific order is required. Moreover, the body is passed as `requestBody`. As a result, this PR includes many adjustments in how the generated client is used. But the behavior should be unchanged.
> frontend: Update OpenAPI schema, generate API client with named arguments

- frontend/.env.development
The development server uses inline script to implement hot reloading and handle compilation errors.
Currently, automatic reloading is failing with an error and the application is frozen:
>Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://www.youtube.com/iframe_api https://www.youtube.com/s/player/".
...
It seems it's related with how `react-error-overlay`  injects an iframe to display potential errors:  
https://github.com/facebook/create-react-app/blob/9673858a3715287c40aef9e800c431c7d45c05a2/packages/react-error-overlay/src/index.js#L139-L154
> fix(frontend): Update CSP to allow inline script used by development environment

- infra/ansible/roles/nginx/tasks/main.yml
- infra/ansible/roles/nginx/templates/certbot.service
During the provisioning, TLS certificates are generated with `certbot certonly --standalone` and this "standalone" setting is persisted in the letsencrypt configuration.  
On renewal, the certbot.service should use existing "nginx" instance as the authenticator, instead of using a standalone server (which would fail as the port is not available). Hence this configuration that forces `certbot.service` to use the `--nginx` option.
> fix(infra): Configure certbot service to authenticate via nginx

- backend/scripts/dataset-import/.gitignore
- frontend/src/features/videos/VideoCard.spec.tsx
- frontend/src/features/videos/VideoCard.tsx
I would prefer to implement solution 4 since dots are not conspicuous and need a bit of focus to be seen.
But then as we said if I don't know the browser's default localization, I can't tell in what format it will be rendered and what I should expect.
I found a regex that does the job for all the languages : /(1.?54.?988|١٥٤٬٩٨٨|۱۵۴٬۹۸۸) views/
It is complicated and uses non-ascii caracters, so /1.?54.?988 views/  is also pretty good except it doesn't work for arabic.
Closes #288
> View count display

- infra/README.md
- infra/ansible/restore-backup.yml
- infra/ansible/roles/restore/handlers/main.yml
- infra/ansible/roles/restore/tasks/main.yml
- infra/ansible/scripts/fetch-and-import-pg-backup.sh
- infra/ansible/scripts/list-backups.sh
- infra/ansible/scripts/restore-last-prod-backup-on-staging.sh
Closes #201
2 distinct mechanisms are implemented:
1. Restore **an entire backup from the same host:**
To be used after an incident, or in order to restore the database to a previous state (e.g after a temporary experiment on a non-production environment).
2. Fetch and import a backup **from a different host** (e.g for development purposes). 
In this case, some data on the target database is preserved to keep OAuth applications functional.
See [the updated README](https://github.com/tournesol-app/tournesol/blob/restore-pg-backup/infra/README.md#restore-postgres-backup) for more details.
> Add scripts and documentation to restore Postgres database from a backup

- frontend/src/features/videos/VideoCard.tsx
After a wrapper has been introduced in #321, a warning in React dev tools passed unnoticed.
> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?  
Check the render method of `ReactPlayer`.
...
Using [`React.forwardRef()`](https://reactjs.org/docs/react-api.html#reactforwardref), the wrapper ref can be forwarded to the inner `Box`.
> [front] fix: warning about missing ref in ReactPlayer

- frontend/src/components/ChoicesFilterSection.tsx
- frontend/src/features/ratings/IsPublicFilter.tsx
- frontend/src/features/recommendation/DateFilter.tsx
- frontend/src/features/recommendation/LanguageFilter.tsx
- frontend/src/features/recommendation/SearchFilter.spec.tsx
part 2/3 of issue #349 (backend, **frontend**, extension)
If you lack time, don't hesitate to assign it to another reviewer.
- added an option in the component ChoicesFilterSection to enable checkboxes that can have multiple options checked at once
- added tests that cover the language filters and date filters rendering
I could also make a test for the criteria filters. But I don't know if it is really useful. It may just be inconvenient if someone ever wants to modify it. And currently the default URL parameters can be unexpectedly displayed in the URL (remark 1 below).
1 - the criteria parameters like "reliability=50" are not removed from the URL, even when they are set at their default value (50).
2 - weird but probably normal : Could not verify the attribute "checked" of the …
> Languages filter frontend

- backend/core/migrations/0005_email_unique_in_db.py
- backend/core/models/user.py
- backend/core/serializers/user.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/tests/test_api_video_rate_later.py
Closes #232 
In addition to the update in `User` model, this PR includes a migration to guarantee that no duplicated address persists in the database before the uniqueness constraint is applied. As agreed, only the account with the highest number of comparisons will keep its email address, and the others will no longer be associated with a valid address.
After this change, the uniqueness constraint on `email` will be enforced by a database index. Blank values for `email` are no longer allowed, hence the adjustments in tests.
> [backend] chore: enforce email uniqueness at the db level

- backend/README.md
- dev-env/docker-compose.yml
- infra/ansible/roles/django/handlers/main.yml
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/restore/tasks/main.yml
**important** this PR targets the feature branch `cache_public_dataset`, and must not be merged into `main`
- related to pull request #392 
- related to issue #383
---
As suggested by @amatissart , the Django command `createcachetable` was missing in our deployment routines. It is now automatically run by the development environment each time the API container is started. It is also run for each deployment made by Ansible.
> [review branch] to merge into `cache_public_dataset`

- backend/tournesol/tests/test_api_video.py
- backend/tournesol/views/video.py
**related to** https://github.com/tournesol-app/tournesol/issues/399
tasks:
---
From now, anonymous users won't be able to make POST request on `/video/` anymore, the API will returned an error 401 Unauthorized. They can still use all read-only HTTP methods, like `GET`, `HEAD` and `OPTIONS`.
I took the time to refactor a little the existing tests related to the `POST /video/` endpoint, and unfortunately it might not be that easy to make the distinction between the new feature and the refactor, I'm sorry, next time I'll do the refactor afterward.
Checking the commits one by one can help.
Here are all the tweaks I've made:
I've grouped all tests related to `POST /video/` together, instead of having them scattered between tests related to `GET /video/`. They will be easier to maintain.
I've …
> [back] feat: prevent anonymous users to add new videos to the DB

- frontend/src/features/login/Login.spec.tsx
- frontend/src/features/login/Login.tsx
- frontend/src/features/rateLater/RateLaterAddForm.tsx
- frontend/src/features/settings/account/PasswordForm.tsx
- frontend/src/features/settings/profile/ProfileForm.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/utils/api/response.ts
**related to:** #211 
**will fix the tech' debt:** #287 
**to merge before pull request:** #405 
---
In the front end not all forms handle the errors returned by the API in the same way, and it forces me to copy several times the same lines to handle properly the HTTP 429 Too Many Requests status in the PR #405.
This merge request should help by reducing the quantity of duplicated code, and will make the development of the previously mentioned PR a lot easier.
Fortunately we already have a rather generic piece of code able to treat the majority of forms as equal, so I decided to factorize it in a `src/utils/api/responses.ts` function.
This function:
- is documented
- uses `notistack`
- automatically handles `HTTP 429` with a nice " retry after X seconds "
- automatically handles all other …
> [front] refactor: simplify API responses handling in several forms

- backend/settings/settings.py
- backend/tournesol/tests/test_api_i18n.py
- backend/tournesol/utils/cache.py
- backend/tournesol/views/exports.py
Related to #329 
Basically, this PR adds the `LocaleMiddleware` provided by Django, used for language detection:
https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#how-django-discovers-language-preference
As DRF provides translated error messages for its validation errors, they will be present in API responses and displayed by frontend consistently with the current language, based on the standard `Accept-Language` that has been configured in #385.
A small side-effect of this change is about caching. `cache_page` uses the current language in its cache key. So a custom decorator `cache_page_no_i18n` has been implemented to force the default locale on API views where caching a distinct response per language would be wasteful.
> [back] feat: enable localized error messages in API

- frontend/public/locales/en/translation.json
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/pages/comparisons/ComparisonList.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/pages/videos/VideoRatings.tsx
- frontend/src/pages/videos/VideoRecommendation.tsx
**closes** #395 
---
As requested in the issue, the tooltips will be displayed only when the sidebar is not expanded.
I also added translation keys `xxx.contentHeader` that contains all page titles. I was about to use keys like `myComparisonsPage.title` but I realized they could be confounded with the actual page title display in the browser tab. What do you think @amatissart ?
I can refactor the existing keys to match this pattern if needed (`signup.title` will become `signupPage.contentHeader`). Maybe `signupPage.mainTitle` is more user-friendly for the translators.
**edit:** I finally decided to keep `key.title` as it's simple and coherent with the rest. We can use `key.tabTitle` for browser tabs.
**example of a displayed tooltip**
**the new titles**
> [front] feat: add tooltips in sidebar & add title to each pages

- backend/.gitignore
- backend/README.md
- backend/core/locale/fr/LC_MESSAGES/django.po
- backend/core/templates/accounts/register/body.txt
- backend/core/templates/accounts/register/subject.txt
- backend/core/templates/accounts/register_email/body.txt
- backend/core/templates/accounts/register_email/subject.txt
- backend/core/templates/accounts/reset_password/body.txt
- backend/core/templates/accounts/reset_password/subject.txt
- backend/dev-env/Dockerfile
- backend/requirements.txt
- backend/settings/settings.py
- dev-env/docker-compose.yml
- infra/ansible/roles/django/handlers/main.yml
- infra/ansible/roles/django/tasks/main.yml
Create templates for emails related to account registration, email update and password resets.  
The templates are derived from [rest_registration](https://github.com/apragacz/django-rest-registration/tree/0.7.0/rest_registration/templates/rest_registration), and translated in french only.
As they are the first translation and templates files introduced in our own Django app, I had to update the settings to configure the paths to these folders. And ensure that messages are compiled before deployment and during dev-env setup.
> [backend] feat: Translate registration emails

- frontend/i18next-parser.config.js
- frontend/package.json
- frontend/src/components/LanguageSelector.tsx
- frontend/src/i18n.ts
Especially on Chrome Android, it seems that language names are not provided, although `Intl.DisplayNames` API is available.
This PR defines the language name associated with each code in the `supported_languages` list.
> [front] fix: Language names could be missing due to limited support of `Intl.DisplayNames`

- frontend/package.json
- frontend/yarn.lock
- infra/ansible/roles/nginx/tasks/main.yml
- infra/ansible/roles/nginx/templates/nginx.conf.j2
original config file :
[nginx.txt](https://github.com/tournesol-app/tournesol/files/7884622/nginx.txt)
new config file :
[new_nginx.txt](https://github.com/tournesol-app/tournesol/files/7884624/new_nginx.txt)
I discussed with JST of the BREACH vulnerability. We think it is not a problem in Tournesol.
A further improvement could be to use the compression algorithm Brotli for better performances. Brotli (compared to gzip) is slower for compression, slightly slower for decompression but gives a better compression ratio, for example :
main.45fd59e7.js => 939173 bytes (uncompressed)
main.45fd59e7.js.gz => 289515 bytes (gzip)
main.45fd59e7.js.br => 212442 bytes (brotli)
precompress by default also produces brotli files. But the difficulty is that to use brotli we need to install the nginx …
> [infra] Enable gzip compression in Nginx and precompress static files

- frontend/src/features/comparisons/CriteriaSlider.tsx
- frontend/src/features/frame/components/sidebar/Footer.tsx
- frontend/src/pages/about/About.tsx
- frontend/src/utils/url.ts
"wiki.staging.tournesol.app" was used on all environments :fearful: 
Issue observed during Tournesol video tutorial.
> [front] fix: Remove hard-coded wiki hostname on About page

- browser-extension/utils.js
**related to** #426
---
This pull request doesn't fix the root cause of the issue, but it's a starting point indicating how users can solve the problem by themselves.
Here is the result below. I used short sentences to prevent the scroll bar to appear in the message box. It's still not user friendly, but it could help some users to get back on track.
We can also decide to not push those changes now, and update the front end before to not force users to hit the refresh button.
**(edit)** the typo in the word step**s** in the screenshot is fixed
> [extension] refactor: more accurate message when token is invalid

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/FormTextField.tsx
- frontend/src/pages/signup/Signup.tsx
On the signup page, and in the privacy policy.
Closes #444
> [front] feat: Add explicit messages about the username being public

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/Frame.tsx
- frontend/src/features/frame/components/StorageError.tsx
- frontend/src/utils/extension.ts
Related to #492, to help with the integration of Tournesol pages in iframes. 
When this parameter is present during the app initialization, the `<TopBar>` and `<SideBar>` will not be rendered, allowing any page to be integrated in a minimalist way.
E.g the login page:
The implementation suggested in #492 should work on most systems, without any change related to privacy or security settings on the server and on the clients. 
However some users may have configured their browser with stricter rules (e.g "Strict Mode" on Firefox, or "Block third-party cookies" on Chrome), where third-party storage (i.e tournesol.app local storage, containing user configuration and credentials) cannot be accessed or persisted from the context of an iframe embedded in another website.  
More details in the …
> [front] feat: Implement embedded mode and error messages about storage access from iframe

- frontend/src/features/login/Login.tsx
After a login request has been interrupted (e.g the tab has been closed), the token status can be persisted with the value "loading". 
In this situation, the login form should not be disabled, if no request has been submitted on the current page yet.
> [front] fix: Login form could be stuck in loading state

- browser-extension/addModal.js
- browser-extension/addRateLaterButton.js
- browser-extension/background.js
- browser-extension/browserAction/menu.js
- browser-extension/config/const.js
**related to** #426 
**complete the work of** #492 
---
The extension is now able to display the Tournesol login form from the browser action popup.
Make the `addModal.js` content script the only script responsible of displaying and hiding the modal.
Make it more explicit that the login `iframe` is by default integrated in the modal ( if we decide in the future to make the modal able to display anything ).
Make some message listeners able to return a response, instead of just silently succeed or fail.
> [extension] feat: also display login iframe from browser action

- browser-extension/addModal.js
- browser-extension/background.js
- browser-extension/config/const.js
- browser-extension/manifest.json
**related to** #426 
**complete the work of** #508 
---
This pull request makes the login `iframe` appear when the users use the context action `Rate later on Tournesol` on a YouTube video.
It also make the automatic access token refresh process available on all YouTube pages. 
After the merge, and if I'm not forgetting anything, all rate later actions of the extension will trigger the login `iframe`.
The following steps are:
- enhanced the UX by adding a close button on top of the `iframe`
- https://github.com/tournesol-app/tournesol/issues/510
- add tests!
> [extension] feat: also display login iframe from context menu

- backend/settings/settings.py
- backend/tournesol/errors.py
- backend/tournesol/models/video.py
- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/tests/test_api_video_rate_later.py
- backend/tournesol/views/video.py
- backend/tournesol/views/video_rate_later.py
- browser-extension/utils.js
- frontend/scripts/openapi.yaml
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/comparisons/ComparisonList.tsx
- frontend/src/features/rateLater/rateLaterAPI.ts
- frontend/src/features/video_selector/VideoSelector.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/pages/signup/Signup.tsx
- frontend/src/utils/video.ts
Closes #202 and Fixes #436
* Video creation is handled by `RelatedVideoSerializer` (replacing `VideoReadOnlySerializer`)
* `RelatedVideoSerializer` and `VideoSerializer` uses the same `Video.create_from_video_id()` method to create the video (and fetch metadata) if necessary.
* Custom implementations for video_rate_later and comparisons views can be simplified to take advantage of the serializers
* Bonus: the `GET /users/me/comparisons` response now includes the videos metadata  
(fix #436)
* Frontend and Browser extension are updated to avoid unnecessary API calls to check that a video exists.
> [back] feat: create video automatically in API views that require an existing video

- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/comparisons/ComparisonSliders.tsx
- frontend/src/pages/comparisons/Comparison.tsx
**related to** #327 
---
This pull request is a preliminary work, to make the #327 realizable without code duplication.
The `<ComparisonPage>` component page now uses a `<Comparison>` feature component. This allows to re-use the `<Comparison>` component everywhere in the application. Note this new component still uses the `useLocation` hook, and using it a page will also add the `videoA` and `videoB` parameters to the URL. We might want to change this, but prefer to leave it as is for now, and I'll rework the behaviour if needed when I'll add the component to the Home page.
The previous `<Comparison>` component, imported as `ComparisonSliders` is now called `<ComparisonSliders>` to avoid confusion.
> [front] refactor: move the comparison UI in its own component

- backend/requirements.txt
It fixes:
- CVE-2022-22818
- CVE-2022-23833
see: https://docs.djangoproject.com/en/3.2/releases/3.2.12
> [back] security: upgrade Django to 3.2.12

- backend/pytest.ini
- backend/requirements.txt
- backend/tests/requirements.txt
- backend/tournesol/models/video.py
I also updated a few other libraries, even that was not required.
The reason why django-language-field was replaced is discussed in #348 (use of the obsolete function ugettext_lazy)
tested with python 3.8 and 3.9
You may have to delete the tournesol-dev-api image first for it to work.
> [backend] Upgrade to Django 4.0 (#348)

- backend/requirements.txt
It fixes two security flaws re-introduced by the upgrade to Django 4.0.1
- CVE-2022-22818
- CVE-2022-23833
and several other regressions introduced by Django 4.0
see: https://docs.djangoproject.com/en/4.0/releases/4.0.2/
> [back] security: upgrade Django to 4.0.2

- backend/pytest.ini
- backend/settings/settings.py
In the previous PR (#544), I missed those pytest warnings because I was using `python manage.py test` instead of pytest
The first warning is because USE_L10N is getting deprecated. It is set to true by default anyway.
The second warning (RemovedInDjango41Warning) comes from django-rest-registration. It is not solved yet in the latest version of django-rest-registration, so I just muted the warning.
> pytest warnings

- backend/tournesol/utils/video_language.py
Following #348, the language detection mechanism could insert languages that are not included in the field "choices".  
Let's ignore these languages. (This should be marginal, it represents only 1 video in the current database in production).
> fix: ignore detected language if not in allowed choices

- backend/settings/settings.py
After upgrading to Django 4.0, CSRF checks failed due to bad "Origin" in requests, e.g when logging into the admin.
This is related to [a change related to CSRF in Django](https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf). However `CSRF_TRUSTED_ORIGINS` should not be required in our case, as we are not using cross-origin requests with CSRF. 
The root cause seems to be that requests using HTTPS are not considered "secure" by Django, as they are proxied via Nginx / Gunicorn / Uvicorn.
As verified on staging, setting `SECURE_PROXY_SSL_HEADER` fixes this issue.
---
See the origin verification in Django implementation:
https://github.com/django/django/blob/4.0.2/django/middleware/csrf.py#L252-L264
And the headers set by Nginx in the current configuration …
> Fix requests not considered 'secure' when proxied via nginx + gunicorn

- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/views/comparison.py
Comes after #556 and closes #526
> Add 'criteria' validation on comparison creation and update

- backend/tournesol/entities/__init__.py
- backend/tournesol/entities/base.py
- backend/tournesol/entities/video.py
- backend/tournesol/models/entity.py
- backend/tournesol/models/poll.py
- backend/tournesol/query_serializers.py
- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_polls.py
- backend/tournesol/tests/test_api_video.py
- backend/tournesol/urls.py
- backend/tournesol/views/polls.py
- backend/tournesol/views/video.py
Implements item **(2)** in https://github.com/tournesol-app/tournesol/issues/529
Similar to `GET /video/` to fetch a list of recommendation, with a few differences
In the **response**: 
* fields specific to a video are not present. Instead a `metadata` dict is returned (empty for now)
* `total_score` is present in the output (as a `FloatField`) and computed with a default weight of 10 for each criteria (instead of 50 in the /video/ route, to be consistent with the score currently computed by the frontend).
In the **query parameters**:
* `?criteria=50` is replaced with `?weights[criteria]=10`, as the name of the criterias are now dynamic
* filters based on video metadata (language, uploader, etc.) are not implemented.  
Maybe a generic `?metadata[key]=value` could be used instead in the …
> Implement minimal version of poll recommendations API

- backend/tournesol/models/comparisons.py
- backend/tournesol/models/entity.py
- backend/tournesol/serializers.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/urls.py
- backend/tournesol/views/comparison.py
- backend/tournesol/views/exports.py
- frontend/scripts/openapi.yaml
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/comparisons/ComparisonList.tsx
- frontend/src/features/comparisons/ComparisonSliders.tsx
- frontend/src/pages/comparisons/ComparisonList.tsx
- frontend/src/utils/constants.ts
- frontend/src/utils/video.ts
**related to** #527 
**follows the work of pull request** https://github.com/tournesol-app/tournesol/pull/563
---
This pull request refactors the comparisons API, to use entity UID in its URLs and make the front end compatible. It also changes the JSON representation of a comparison by replacing `video_a` and `video_b` keys by `entity_a` and `entity_b`.
This pull request doesn't replace the usage of `video_id` in the JSON representation of a comparison yet, I'd prefer doing this in a distinct PR as it might require few tweaks of the video serializers and maybe other part of the application. 
**back end**
**front end**
> refactor: use `uid` in comparisons URL instead of `video_id`

- frontend/package.json
- frontend/scripts/openapi.yaml
- frontend/src/features/settings/account/ExportAllDataForm.tsx
- frontend/src/features/videos/VideoCard.spec.tsx
- frontend/tsconfig.json
- frontend/yarn.lock
Upgrading openapi-typescript-codegen is necessary to handle "deepObject" query params introduced for "weights" in #577 
"openapi-typescript" was another tool to generate OpenAPI client, and is no longer used.
> Update OpenAPI schema and upgrade openapi-typescript-codegen

- frontend/src/components/CriteriaRadarChart.tsx
Context:
Scores were scaled automatically when displayed such that if the max score was very small it appeared that all scores are large. This PR fixes this issue by forcing a fixed sclae between 0 and 1.
Closes #570
> [front] fix: Clips scores between 0 and 1 on RadarChart

- backend/tournesol/serializers/entity.py
- backend/tournesol/tests/test_api_entities.py
- backend/tournesol/tests/test_api_video.py
- backend/tournesol/urls.py
- backend/tournesol/views/entities.py
Closes #529
After discussion with @GresilleSiffle, the usecase for `/polls/<poll_name>/entities/` was not clear now that recommendations provides a filter "unsafe" to include all entities rated by the current poll.
Instead this PR implements the API `GET /entities/` and `GET /entities/<uid>/` as described in #527
2 filter parameters are accepted:
* `type` to filter by entity type
* `poll_name` to include scores of a single poll  
**NB:** even if "poll_name" is present, the list will return all entities including entities that have not been rated by the given poll. Their "polls" list may be empty.
> Implement entities API

- frontend/src/components/LanguageSelector.tsx
- frontend/src/features/frame/components/sidebar/Footer.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
Context:
Language Icon is missing on the sidepanel when it is collapsed.
This PR fixes it by adding the LanguageSelector component when it is collapsed and hides the text when collapsed.
Fixes #463
> [#463][front] : adds language icon in the collapsed navigation bar

- dev-env/run-docker-compose.sh
Sometimes, the pipeline for e2e tests fails because the dev-env (especially the frontend container) does not start in time.
This PR sets the delay to wait for containers from 2 minutes (**2** * 60) to  3 minutes (**3** * 60)
> dev-env: longer timeout when waiting for frontend initialization

- frontend/src/features/frame/components/sidebar/SideBar.tsx
Related issue: https://github.com/tournesol-app/tournesol/issues/565
The problem was that the target url beneath selecting "Recommendations" has the url parameter `date=Month`
I choose to correct the logic by deleting all possibles url params when checking for the component to highlight
> Correct logic for highlighted component in navbar

- backend/tournesol/serializers/entity.py
- frontend/scripts/openapi.yaml
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/comparisons/ComparisonList.tsx
- frontend/src/features/videos/PublicStatusAction.tsx
- frontend/src/features/videos/VideoApi.tsx
- frontend/src/features/videos/VideoCard.spec.tsx
- frontend/src/features/videos/VideoCard.tsx
- frontend/src/features/videos/VideoList.tsx
- frontend/src/utils/action.tsx
- frontend/src/utils/types.ts
- frontend/src/utils/video.ts
**related to** #527 
---
This pull request make some front end components compatible with the new entity `uid` instead of the previous `video_id`. The main change is in the `<Comparison>` component which is now able to handle URLs containing UIDs (it's still compatible with the old `videoA` / `videoB` parameters, this keeps all previously shared comparison links valid).
To keep the back end backward compatible, its API responses include the `uid` field **in addition** to `video_id`.
To keep the front end backward compatible, the components **fallback** to `video_id` if there is no `uid` field in a video object.
`features.videos.VideoCard.VideoCard`
`features.comparisons.Comparison.Comparison`
`utils.action`
`features.videos.PublicStatusAction.PublicStatusAction`
> [front] refactor: `Comparison` now uses UIDs (and more)

- backend/tournesol/admin.py
I found this bug in production, the metadata update action from the admin interface was failing. 
The log from `journalctl`: 
```
Feb 21 16:51:09 tournesol gunicorn[494242]:   File "/.../tournesol/admin.py", line 43, in update_metadata
Feb 21 16:51:09 tournesol gunicorn[494242]:     if entity.type == Entity.TYPE_VIDEO:
Feb 21 16:51:09 tournesol gunicorn[494242]: AttributeError: type object 'Entity' has no attribute 'TYPE_VIDEO'
```
> [back] fix: `EntityAdmin.update_metadata` failing because of wrong import

- backend/README.md
**related to** https://github.com/tournesol-app/tournesol/issues/573
---
Following the work initiated in https://github.com/tournesol-app/tournesol/pull/590, I've re-organized the back end's `README.md` to remove as much ambiguity as possible about the installation process.
The `expect` dependency in now in the the automatic installation section, and it's now stated that the Google API key setup is common to both automatic and manual installation.
> [back] docs: describe the complete installation path

- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/views/comparison.py
Following the work of #611 , the comparisons API now uses the `PollScopedViewMixin` class.
As we are using several level of inheritance in the comparisons API class based views, I took the time to ensure the `PollScopedViewMixin` is correctly used by adding a new test for each HTTP methods.
> [back] refactor: comparisons API now uses `PollScopedViewMixin`

- backend/tournesol/models/entity.py
For example, it's no longer possible to update the "metadata" for a video without the "video_id" field (required).
> Validate entity 'metadata' content in admin form

- browser-extension/addTournesolRecommendations.css
- browser-extension/addTournesolRecommendations.js
- browser-extension/background.js
- browser-extension/fetchTournesolRecommendationsLanguages.js
- browser-extension/manifest.json
- frontend/src/utils/constants.ts
- frontend/src/utils/recommendationsLanguages.spec.ts
- frontend/src/utils/recommendationsLanguages.ts
Related to #349.
It requires either [!602](https://github.com/tournesol-app/tournesol/pull/602) to be deployed in production or a manual change of the local storage on tournsol.app.
For now this PR only includes the code that loads the recommendations languages from the website's localStorage and uses them in the recommendations request.
If the recommendations languages change on the website and you refresh the youtube home page the recommendations are still in the previous language because the iframe that refreshes the data hasn't finished yet when the recommendations are loaded. A second refresh will load recommendations in the updated languages. A solution may be to wait for the iframe to complete but it may be tricky and may add a delay. A better solution may be to trigger the …
> Use frontend recommendations languages in extension

- backend/tournesol/serializers/comparison.py
- backend/tournesol/serializers/entity.py
- backend/tournesol/serializers/rating.py
- backend/tournesol/tests/test_api_ratings.py
- frontend/scripts/openapi.yaml
- frontend/src/features/comparisons/ComparisonList.tsx
- frontend/src/features/video_selector/VideoSelector.tsx
- frontend/src/pages/videos/VideoRatings.tsx
- frontend/src/utils/types.ts
**related to** #597
**follows the work of the pull request** #623
> [back][front] refactor: ratings API uses `RelatedEntitySerializer`

- backend/tournesol/admin.py
- backend/tournesol/utils/video_language.py
As an admin, using the admin interface, I find more readable to see names of languages ("Spanish" and "Estonian") rather than codes ("es" and "et") so that I can identify and manually correct language assignments of video entities
> feat: Display language names instead of codes in EntityAdmin

- frontend/src/features/video_selector/VideoSelector.tsx
- tests/cypress/integration/frontend/comparePage.ts
- tests/cypress/integration/frontend/comparisonPage.ts
- tests/cypress/integration/frontend/myRatedVideosPage.spec.ts
Here are few end-to-end tests ensuring the comparison UI is working properly.
This test case is not exhaustive yet, but is a good starting point. It should fail easily if the comparison UI is broken during the development. 
**use cases not covered by these tests**
- pasting video URLs directly in the video selectors input fields (more details in the code)
- requesting new video with the `new video` circular button (note: this feature is subject to change)
> [tests] tests: add end-to-end tests related to the comparison page

- frontend/src/features/comparisons/Comparison.tsx
- tests/cypress/integration/frontend/comparisonPage.ts
A regression was introduced in #632  
An integration test has been added to cover this.
> Fix: legacy params in comparison URL should redirect to uids

- backend/tournesol/serializers/entity.py
- backend/tournesol/tests/factories/poll.py
- backend/tournesol/tests/test_api_ratings.py
Entities with type "video" can be created dynamically.  
For other entity types, the entity needs to be preexist in the database.
This is a prerequisite to implement a EntitySelector on frontend. For now this serializer supports videos only.
> Generalize validation in `RelatedEntitySerializer`: reject non-existing non-video entities

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/components/topbar/PollSelector.spec.tsx
- frontend/src/features/frame/components/topbar/PollSelector.tsx
- frontend/src/features/frame/components/topbar/TopBar.tsx
- frontend/src/utils/constants.ts
- frontend/src/utils/types.ts
**related to** #647 
---
This pull request adds a `<PollSelector>` component allowing users to navigate between polls.
I didn't add the requested mui badge yet. I plan to do it in another pull request.
The menu on mobile is still very light. It works, but doesn't display the selected poll name. With @amatissart we considered using the side menu on the mobile instead of the `<PollSelector>`, or we can just display the poll name in the top bar.
**new component**
**ux / ui**
**desktop / mobile**
**further improvement**
https://user-images.githubusercontent.com/39056254/157412291-4b21cc39-0781-4845-bfab-a064497d748c.mp4
> [front] feat: allow navigation between polls

- frontend/src/features/recommendation/SearchFilter.tsx
This is especially important for the "language" filter, as `?language=` parameter is explicitly used to disable the default filter based on the user languages.
> Fix "active search filter" badge: empty string should not be considered as an active filter

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/comparisons/ComparisonSliders.tsx
- frontend/src/features/comparisons/CriteriaSlider.tsx
- frontend/src/features/video_selector/AutoEntityButton.tsx
- frontend/src/features/video_selector/VideoInput.tsx
- frontend/src/features/video_selector/VideoSelector.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- tests/cypress/integration/frontend/comparisonPage.ts
* The "magic wand" button (used to select a new video automatically) is replaced with a more explicit button with text "Auto"
* The style of the criteria sliders is updated to be closer to the initial mockup.  
The name and logo of each criteria is aligned on the left.  
The checkbox used on each optional criteria is aligned on the right.  
It also makes the layout more consistent when criterias names are of different lengths.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/4726554/157901960-3f4a5680-20a3-4c7a-b573-1744258243d9.png)|![image](https://user-images.githubusercontent.com/4726554/157902235-c9e1580c-2706-46d9-9a79-4479411c344f.png)
Feedbacks are welcome :pray:
> Suggestion to adjust style of the comparison page

- frontend/src/components/entity/EntityImagery.tsx
- frontend/src/features/videos/VideoCard.tsx
Following #672  and #661, the player "controls" were not visible where created from the  `EntityCard`.  
Let's keep a single implementation of the player, where "controls" can be enabled/disabled.
> Single component `VideoPlayer` with "controls" prop

- frontend/src/features/comparisons/CriteriaSlider.tsx
- frontend/src/features/entity_selector/AutoEntityButton.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
* Disable the "auto" button to avoid repeated requests for new entities to compare (can also trigger unexpected flickers in the UI)
* Solve several warnings on this page:
* the `Tooltip` child cannot be a disabled button, hence a "<span>" used as a wrapper
* a `Chip` was used inside a `<p>` and should be inserted as a `<span>` instead of a `<div>` (by default)
> Disable 'auto' button on loading and solve warnings related to MUI components

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/app/PollRoutes.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/features/frame/components/topbar/PollSelector.spec.tsx
- frontend/src/utils/constants.ts
- frontend/src/utils/types.ts
**related to** #659 
---
I temporarily activated the poll `presidentielle2022` in the front end configuration just to make the branch testable. I'll revert it before merging.
This pull request makes the router `<PollRoutes>` and the component `<SideBar>` aware of the currently selected poll and its configuration.
To achieve this, these components use ids allowing them to identify which routes must be enabled and which must be disabled.  
Making the sidebar items translations more generic simplified a lot the code, but as a drawback items are less precise than before.
- `Compare videos` becomes `Compare`
- `My rated videos` becomes `Compared items`
`Compare` is less appealing than `Compare videos` as the user may not be able to know what he/she is invited to compare. So as a proposition I …
> [front] feat: make sidebar aware of the selected poll

- frontend/src/features/comparisons/Comparison.tsx
Due to how the location was memoized by the callback `onChange`, the URL change could fall in a race condition when the 2 "auto" buttons were activated simultaneously. Only one of the 2 changes would be persisted in the URL.
Reading `window.location` just in time should solve the issue.
> Fix a race condition when the 2 entity selectors are updated concurrently

- frontend/src/features/entity_selector/EntityInput.tsx
Fix missing selected inputs after refreshing a comparison page
> fix: selected values appear in EntityInput when refreshing

- browser-extension/README.md
This pull request adds a `Development guidelines` section to the extension's `README.md`.
It mentions the existence of the `yarn lint` command and kindly ask the developers to run this command before opening new pull requests.
Preview the file here: https://github.com/tournesol-app/tournesol/blob/f18bd5f20fdb3b55a2ec404d26757787d85765ac/browser-extension/README.md
> [extension] docs: add development guidelines section in the `README.md`

- .gitignore
I finally took the time to add more files to the  `.gitignore`. The `git diff` commands should be less talkative now, at last on my laptop.
All sources come from the https://github.com/github/gitignore project.
Concerning JetBrains, as we don't plan for now to share configurations and as we use different IDEs I simply ignored all files specific to JetBrains IDEs.
> chore: include Linux and JetBrains specific files in .gitignore

- backend/tournesol/entities/base.py
- backend/tournesol/entities/candidate.py
- backend/tournesol/entities/video.py
First simple pr.
Almost nothing, I read the code and saw some stuff I can improve.
The only "big" change is the returned type of `get_uid_regex` that now return `str` instead of `str | None`.
AFAIK Only used in backend/tournesol/serializers/entity.py:L241, type truthiness is used.
I like simpler signature. PEP20, simple is better than complex. Optional[str] is more complex than str.
> backend/tournesol/entities annotations, code layout and type homogenization

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/recommendation/DateFilter.tsx
- frontend/src/features/recommendation/LanguageFilter.tsx
- frontend/src/features/recommendation/SearchFilter.spec.tsx
Related issue: #689 
I tried the small "x" but it doesn't look good when it's warped on a new line on some window widths, so I added an "All time" option instead.
For the languages I shortened the French version to "Toutes" because the input is not long enough for "Toutes les langues".
> Explicit "everything" filter

- backend/tests/requirements.txt
The issue of jinja2 new version is already fixed but not released: https://github.com/lordmauve/flake8-html/commit/edef580c6d5e0ccb3ab54aa31b42b4359f7b9235
> add jinja2 maximum version until flake8-html next release

- frontend/src/components/Card.tsx
- frontend/src/components/CriteriaBarChart.tsx
- frontend/src/pages/videos/VideoAnalysis.tsx
Related issue: #626
Initial attempt to add the Bar chart:
Moving the ticks in the middle doesn't seem possible with recharts. It may be possible to solve that by making 2 aligned charts.
Most of the code is copied from the Radar chart. Some of it should be refactored if both charts are going to stay.
> Add Bar chart on video analysis page

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/utils/constants.ts
- frontend/src/utils/entity.ts
- frontend/src/utils/polls/presidentielle2022.ts
- frontend/src/utils/types.ts
**is subtask of** #681 
close #706 and #707
---
This PR add the possibility to translate the tutorial of each poll. It comes with a dialog proposition that could be updated at any moment. It also makes the `<ComparisonSeries>` component aware of the existing comparisons made by the user (see the commit c2b5e97, I accidentally pushed two features in the same branch, tell me if you prefer two PR @amatissart). 
I use several sub-keys in the translation so that we can add dialog for more than one series in a given poll.
The keys are " generic " and not talkative, but they help to add and remove paragraph rather than easily. Contrary to even more generic keys containing several paragraphs inside on string, which makes working on the translations uncomfortable.
**known limitations**
**(1)** …
> [front] feat: add translations for the `presidentielle2022` tuto

- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/pages/comparisons/Comparison.tsx
must be rebased on main when #721 is merged
---
If a user that has already finished the tutorial manually add the `?series` in the presidentielle 2022 comparison page, he/she will arrive on the comparison series page, with the stepper showing everything is finished. From here, it will be possible to continue adding more comparisons, the UI automatically suggestion new a candidate after each submit.
I think it's a good feature to be able to follow an infinite chain of suggested comparisons. This allows users to not be forced to click on the drop down menus to select new candidates. But this feature might be removed when we will add the result page.
> [front] feat: make `ComparisonSeries` "resumable"

- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/features/videos/PublicStatusAction.tsx
- frontend/src/pages/videos/VideoRatings.tsx
- frontend/src/utils/constants.ts
- frontend/src/utils/types.ts
**related to** #726 
---
Following our "private by default" policy, polls must be explicitly configured to allow users to set their comparisons public.
A poll with the `comparisonsCanBePublic` set to true, will have its entity card display the public / private checkbox. The front end page `/ratings/` will also display the filter by visibility option and update visibility buttons.
For now it's a front end only configuration, but it will be easy to make it a back configuration (a field in the Poll model for instance).
| a poll configured with `comparisonsCanBePublic` = true | a poll without `comparisonsCanBePublic`  |
|---|---|
| ![capture2](https://user-images.githubusercontent.com/39056254/160583544-437cfff7-3b06-4953-8f5f-896f2331d2b2.png) | …
> [front] feat: polls must be configured to allow public comparisons

- backend/ml/inputs.py
- backend/ml/management/commands/ml_train.py
- backend/ml/management/commands/ml_train_dev.py
- backend/ml/mehestan/global_scores.py
- backend/ml/mehestan/individual.py
- backend/ml/mehestan/primitives.py
- backend/ml/mehestan/run.py
- backend/ml/ml_requirements.txt
- backend/tournesol/models/poll.py
Based on the ongoing paper "Tournesol’s algorithms" by @lenhoanglnh 
Contrary to the previous algorithm that computes individual and global scores together, these scores are now computed in separate steps:
1. Compute **individual scores** for each (user, criteria),  based on raw comparisons scores submitted on Tournesol
2. Apply a **collaborative score scaling**. This is currently implemented in 2 substeps    
* initialize the scalings for a set of "supertrusted" users
* compute the scaling for the remaining users
3. Compute the **global scores** for each (entity, criteria) after the individual scores have been scaled + translated
4. Compute the **Tournesol score** as an aggregation of all criteria. Here we'll try to predict a global score for the main criterion, based on all criteria …
> First implementation of "Mehestan" algorithm

- frontend/.env.development
- frontend/.env.test
- frontend/src/utils/constants.ts
- infra/ansible/inventory.yml
- infra/ansible/roles/frontend/templates/.env.j2
A custom environment variable is used to add the poll `presidentielle2022` to the list of selectable polls in frontend.
This mechanism relies on variables that are embedded during the build time: 
see https://create-react-app.dev/docs/adding-custom-environment-variables/ for more details.
This new poll will be enabled in development environment, in tournesol-vm, and on staging. (Not on production for the moment).
This way, the "main" branch remains deployable on all environments at any time. And the feature can easily be disabled at deploy time if necessary.
> Define feature flag to enable poll presidentielle2022 per environment

- backend/tournesol/views/exports.py
A small change to ensure that only videos comparisons are included in the public dataset.
2 motivations: 
* the format of the public dataset is specific to videos, with columns `video_a` and `video_b` containing YouTube video ids.  
And updating it would be a breaking change for potential external reusers.
* the poll "videos" is currently the only poll that will accept public comparisons
A wider question about how to extend the format of exports is to be discussed in #697
> Build public dataset on poll 'videos' only

- frontend/src/index.css
- frontend/src/index.tsx
**Context** 
The snackbars were displayed at the bottom center of the screen, which could hide the submit button in the `<Comparison>` component and other UI components depending on the page.
As there is already the side bar on the left, I excluded the anchors bottom left, center left and top left.
As on mobile the bottom center is very similar to the bottom right I chose the top right position. I also excluded center top to avoid hiding potential important UI components as most of our pages display their content in a centered container
> [front] refactor: snackbars are now displayed in the top right corner

- backend/ml/inputs.py
- backend/ml/mehestan/run.py
- backend/ml/outputs.py
- backend/tournesol/entities/candidate.py
- backend/tournesol/entities/video.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/views/comparison.py
- backend/tournesol/views/contributor_recommendations.py
For polls using the new "Mehestan" algorithm, individual scores are quite cheap to compute and can be updated every time a comparison is created, updated or deleted.
Moreover, it's a prerequisite to implement the "results" page described in #740
> Recompute individual scores on comparison submit, for Mehestan only

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/features/feedback/StackedCandidatesPaper.tsx
- frontend/src/pages/comparisons/Comparison.tsx
**related to** #740 
---
This pull request allows developers to add a redirection after a comparison series.
It also makes the `presidentielle2022` tutorial to redirect the user after the last comparison.
If a user tries to manually access the tutorial after having made 7 or more comparisons, the component `<ComparisonSeries>` automatically redirects the user to the feedback page. 
**bonus** it also adds a missing translation in `<StackedCandidatesPaper>`
> [front] feat: `ComparisonSeries` may redirect the user at the end of a series

- frontend/src/features/login/Login.tsx
When a user logs in, the current poll should be preserved, instead of redirecting systematically to the "videos" home page.
> Redirect to the current poll home page after login

- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
The `submitted` prop (used to notify the selector that a new comparison has been submitted) is replaced with a flag `ratingIsExpired` in the `SelectorValue`.
I am not sure that's much more elegant from a React point of view, but at least it's flexible enough to handle the case of a comparison series, where each selector needs to be updated separately.
> Fix nb of comparisons not being updated during comparison series

- backend/tournesol/tests/test_api_criteria_correlation.py
- backend/tournesol/views/criteria_correlations.py
- frontend/scripts/openapi.yaml
Fixes server error for some criteria scores distributions.
Also makes the fields in the response required, to help with the frontend integration.
> correlations: catch ValueError when linear regression is undefined

- backend/tournesol/tests/test_api_criteria_correlation.py
- backend/tournesol/views/criteria_correlations.py
This fixes a bug that occured for me because I had version 1.7 of scipy. Although the bug does not occur anymore with scipy 1.8. I still think the fix is valuable because NaN values may occur for yet unforseen reasons.
> fix: Remove NaNs from dictionary before JSON encoding in correlation API

- backend/tournesol/tests/test_api_criteria_correlation.py
- backend/tournesol/views/criteria_correlations.py
I am not completely sure about this change, but intuitively it will be better than the original proposition.
The reasonning would be that a criteria that influence more the main criteria would also be nearly always on the same side as the main criteria thus be positively correlated. Other less important criteria will less often be on the same side, thus will have a correlation closer to 0.
> fix: Compute correlations on comparisons instead of ratings

- frontend/src/features/comparisons/CriteriaSlider.tsx
The `Chip` was displayed on a new line when a Tooltip was defined on the criteria
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/4726554/161507180-6c99b70c-9c9c-4f9f-b528-a3325df39028.png)|![image](https://user-images.githubusercontent.com/4726554/161507327-e3aa2136-1633-4b8d-b505-d236f0890ecb.png)
> Fix Chip position when a criteria is skipped

- frontend/src/features/comparisons/ComparisonHelperPresidentielle2022.tsx
This pull request adds a `Analyses des mesures climat` section in the comparison helper component.
It also:
- makes the text more compact on desktop, using two columns Grid
- adds a bit of CSS to make the component more welcoming
- makes the titles gender-friendly
> [front] feat: add climate analysis tools in the comparison helper

- backend/settings/urls.py
`reset_password` is used to update the email in database, after the link has been sent.
> Apply throttle on all rest_registration views sending emails

- backend/core/templates/accounts/register/body.html
- backend/core/templates/accounts/register_email/body.html
- backend/core/templates/accounts/reset_password/body.html
- backend/core/utils/converters.py
- backend/settings/settings.py
Following #792 
It should help in some cases where the validation link is rendered as decoded html
> emails: Use convert_html_to_text directly and encode link text

- frontend/src/features/comparisons/ComparisonSliders.tsx
This pull request prevents a single comparison to be submitted a second time before the first request has been fully processed by the back end.
This will greatly reduce the nuisance power of the submit button, and will very very very slightly reduce the number of requests sent to the back end.
> [front] fix: prevent comparison to be submitted several times in row

- backend/tournesol/admin.py
* Display meaningful columns for ComparisonCS and ContributorRatingCS admins
* Enable filtering ComparisonCS and ContributorRatingCS by Poll
* Show total number of Comparison and ComparisonCriteriaScores on PollAdmin
Screenshot:
> feat: Multiple small improvements to Django admin

- backend/settings/settings.py
- backend/settings/urls.py
- backend/tournesol/tests/test_api_user.py
- backend/tournesol/throttling.py
Also rename `EmailThrottle` into `GlobalEmailScopeThrottle` to make it clear to all developers that the limit is shared globally by all clients (contrary to the other throttles that don't use the world `Global` in their name).
It also fixes few typo made by the me of the past.
> [back] refactor: reset `user_burst` limit to 120/min instead of 1200

- backend/requirements.txt
- backend/tournesol/admin.py
Using Django only with the strategy `Count(..., dinstinct=True)`
```python
def get_queryset(self, request):
qst = super().get_queryset(request)
qst = qst.annotate(_n_criteria=Count("criterias", distinct=True))
qst = qst.annotate(_n_comparisons=Count("comparisons", distinct=True))
qst = qst.annotate(
_n_comparisons_per_criteria=Count(
"comparisons__criteria_scores", distinct=True
)
)
return qst
```
Generates the following SQL query (with three expensive `LEFT OUTER JOIN`):
```sql
SELECT 
"tournesol_poll"."id", 
"tournesol_poll"."name", 
"tournesol_poll"."entity_type", 
"tournesol_poll"."algorithm", 
COUNT(
DISTINCT "tournesol_criteriarank"."criteria_id"
) AS "_n_criteria", 
COUNT(
DISTINCT "tournesol_comparison"."id"
) AS "_n_comparisons", 
COUNT(
DISTINCT …
```
> [back] perf: prevent extra queries per row in the poll admin UI

- infra/ansible/roles/mediawiki/templates/LocalSettings.php.j2
**related to** #205 and #557
---
This pull request makes the Wiki non-editable for the anonymous users.
My motivation comes from the fact that the current Wiki describes the Tournesol project, by giving precise information about the association, how criteria for videos were designed, the problems we are trying to solve, etc. This is more a documentation made by the association rather than a tool for the community to organize its knowledge.
To prevent any misinformation, I disabled the anonymous editing, and the possibility for anonymous users to create account (even if it was not working before, now the button is properly hidden).
As anonymous users are not able to edit anything, does this PR close the issue #205? @lfaucon
> [infra] fix: prevent anonymous users to edit the Wiki

- backend/requirements.txt
It fixes two vulnerabilities and few bugs:
- CVE-2022-28346
- CVE-2022-28347
See the full release note: https://docs.djangoproject.com/en/4.0/releases/4.0.4/
> [back] sec: upgrate django to 4.0.4 (from 4.0.3)

- backend/core/management/commands/delete_inactive_users.py
- backend/core/tests/management/test_delete_inactive_users.py
- backend/documentation/settings-tournesol.yaml
- backend/settings/settings.py
- infra/ansible/inventory.yml
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/django/templates/discord-tournesolapi-deleteinactiveusers-fail-alert.sh.j2
- infra/ansible/roles/django/templates/tournesol-api-delete-inactive-users.service.j2
- infra/ansible/roles/django/templates/tournesol-api-delete-inactive-users.timer.j2
This pull request adds a new management command to delete old inactive users.
Inactive users are user with the `is_active` field set to `False`. Old inactive are inactive users who have created their account a certain amount a days ago.
This amount is define by the new setting `APP_CORE["MGMT_DELETE_INACTIVE_USERS_PERIO"']`. This setting is automatically configured to use by default the `REST_REGISTRATION.REGISTER_VERIFICATION_PERIOD` value, so that it equals the lifetime of an activation email. The objective of this configuration is to avoid having valid activation emails linked to deleted users.
The PR also adds a new systemd unit responsible of running daily at 2:20am the management command.
Bonus: when ran in a terminal supporting ANSI-colored output, the command will use fancy …
> [back] feat: add a mgmt cmd to delete inactive users

- backend/ml/mehestan/run.py
- backend/ml/outputs.py
- backend/tournesol/tests/test_api_comparison.py
It's just an idea, I haven't tested it yet against a big database.
**(1)**
There is currently a bug when running `python manage.py test` or `pytest` locally on my laptop, the following exceptions are raised by the test `ComparisonWithMehestanTest.test_update_individual_scores_after_new_comparison`:
```
psycopg2.OperationalError: SSL error: decryption failed or bad record mac
django.db.utils.OperationalError: SSL error: decryption failed or bad record mac
```
They may be related to this: https://code.djangoproject.com/ticket/31637
**(2)**
The `Pyscopg` documentation says the connection to the database must be created after forks.
> **libpq** connections [shouldn’t be used by a forked processes](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNECT), so when using …
> [back] perf: speed-up Mehestan criteria processing with multiprocesses

- backend/core/locale/fr/LC_MESSAGES/django.po
- backend/core/models/user.py
- backend/core/serializers/user.py
- backend/core/tests/test_api_accounts.py
- backend/core/tests/test_reset_password.py
This pull request prevents users to create several account by using lower/upper variant of the same email address.
The front end doesn't enforce using only lower case email addresses as some providers might use case sensitive ones. 
I also added a `clean()` method on the `User` model so that we cannot create inconsistencies from the admin interface.
**to-do**
> [back] fix: possible email duplication

- tests/cypress/integration/browser-extension/extension.spec.ts
This is an attempt to workaround the regular failures observed on GitHub CI, during the tests of the browser extension.  
Due to a banner visible on Youtube US in some cases, the "rate later" button could be hidden.
In this PR, we are trying to "dismiss" this banner if it's present
> e2e extension: dismiss Youtube ad before checking 'Rate Later' button visibility

- backend/core/oauth_validator.py
- tests/cypress/integration/frontend/login.ts
**related to** https://github.com/tournesol-app/tournesol/issues/811
follows the work of #812
---
The new login strategy is the following:
- consider the input as a username, try to fetch the user by username
- if no user is found, and a `@` is present in the username, try to fetch the user by email
- email are matched case insensitively **(new)**
- if no user is found, or if several users are found (inconsistent database), return bad credentials
I wanted to add a test directly in the back end, to be sure the `/o/token` endpoint correctly returns a token when a user tries to login with a lower/upper variant of its email, and to cover our `CustomOAuth2Validator` code. But to save a bit of time to work on the new presidentielle features I finally added an end-to-end test.
The request I …
> [back] feat: allow case insensitive login with email

- infra/ansible/roles/django/templates/tournesol.j2
When deploying a new version of the frontend, browsers may continue to use an expired cached version of the html content. Then, other resources that may have been updated (.css, .js, etc) are not reloaded even if their URL has changed. So we need to set an explicit cache policy for resources whose URL does not change.
This change will force browsers to revalidate the frontend responses with html or json content, including the translation files.
Fixes #566
> Set cache headers to avoid stale version of the app or translations being loaded

- frontend/src/components/CriteriaBarChart.tsx
- frontend/src/components/CriteriaRadarChart.tsx
- frontend/src/pages/videos/VideoAnalysis.tsx
Related comment: https://github.com/tournesol-app/tournesol/pull/828#issuecomment-1106376425
The charts are now responsive and the same size. They work well down to a window width of 420px.
> Improve charts on smaller screens

- backend/tournesol/entities/base.py
- backend/tournesol/tests/test_api_polls.py
- backend/tournesol/views/polls.py
**related to** #833 
will unlock #838 
---
The objective is to upgrade the poll API recommendations endpoint so that it provides as much features as the video API recommendations.
This should ease the development of a recommendations page in the front end that works with different entity type.
**to-do**
> [back] feat: recommendations can be filtered by metadata

- frontend/src/app/PollRoutes.tsx
- frontend/src/features/recommendation/RecommendationApi.tsx
- frontend/src/pages/recommendations/RecommendationPage.spec.tsx
- frontend/src/pages/recommendations/RecommendationPage.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/entity.ts
**related to** #833 
---
First step of the issue #833.
The recommendation page now uses the new poll API instead of the legacy video API to retrieve the recommended entities.
It still only works with videos for now, but I'll make it even more generic in the next PR. I also want to update `getRecommendedVideos` to make it work with any type of entity.
**bonus**
There is now a `videoWithCriteriaFromRecommendation` function able to build a `VideoSerializerWithCriteria` object from a `Recommendation` object. Useful to rework the high level components, like the recommendation page, which are using child components that still use legacy video types.  
The limit parameter of the recommendation API is now a parameter of the `getRecommendedVideos` function.
> [front] refactor: reco. page uses polls API instead of the legacy video

- frontend/src/features/entities/EntityList.tsx
- frontend/src/features/recommendation/RecommendationApi.tsx
- frontend/src/pages/recommendations/RecommendationPage.spec.tsx
- frontend/src/pages/recommendations/RecommendationPage.tsx
- frontend/src/pages/videos/VideoRatings.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/entity.ts
**related to** #833
---
**(1)**
The pages recommendation and ratings now uses the new `EntityList` component. This component is simply a wrapper around a `VideoList` but step by step will become generic.
The very specific component `RateLater` uses directly the `VideoList` instead, as the rate later API only works with video (and not entity) JSON object.
**(2)**
The feature `RecommendationApi` is now generic and can retrieve recommendations from any poll.
The `VideoRatings` could be refactored into an `EntityRatings`, because it currently works with entities but is still called `VideoRatings`.
> [front] refactor: add an `EntityList` component (2/3)

- frontend/yarn.lock
It should fix the security warning about `async`, raised by GitHub Dependabot
> Run `yarn upgrade` to upgrade frontend dependencies

- backend/tournesol/entities/base.py
- backend/tournesol/migrations/0038_fix_metadata_views.py
- backend/tournesol/tests/test_api_comparison.py
When the video metadata are refreshed on comparison submit, the metadata serializer was not called. 
And the number of views was stored as a string instead of an integer in the "metadata" JSON field.
> Fix video metadata not being serialized correctly on refresh

- frontend/src/features/frame/Frame.tsx
- frontend/src/index.css
**related to** #857 
---
The majority of our components used a white background, and the main background of the application was white too. This absence of contrast made hard to distinguish foreground components from background ones.
It also removed the benefits of using MUI `<Paper>` and similar components, which have a drop shadow that makes them look like a paper displayed on top on something else. Cast on a white background this shadow is less clear-cut, and acts more as a simple delimiter rather than a proper invitation to consider the component more important than underlying surface.
Having different contrast between foreground and background component helps to understand what's going on on the screen (modals are usually display on top of a greyed background), and should help the …
> [front] style: set background to light grey instead of white

- backend/core/utils/constants.py
- backend/settings/settings.py
- backend/tournesol/models/comparisons.py
- backend/tournesol/serializers/inconsistencies.py
- backend/tournesol/tests/test_api_inconsistencies.py
- backend/tournesol/urls.py
- backend/tournesol/views/inconsistencies.py
The score inconsistencies measure the difference between the rating scores calculated by the machine learning and the comparisons.
I decided to allow low threshold values (even 0), but to limit the number of results in the response to 100 (even if the count can get higher) to limit the size of the response.
A potential issue us that the machine learning rating scores may not have been updated with the latest comparisons. This is quite problematic that the ContributorRatingCriteriaScores can't be updated directly after each modification, which would also allow for quick feedback, notably in the contributor recommendations.
The next part is on cyclic inconsistencies, which is trickier in terms of algorithms and computation time.
Feel free to suggest corrections or improvements.
> part 1/2 : score inconsistencies (next: cyclic inconsistencies) (#671)

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/about/TrustedDomains.tsx
Found a page that was clearly written by @lfaucon : https://tournesol.app/about/trusted_domains ;)
> [front] fix: missing traduction on about/trusted_domains page

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/ChoicesFilterSection.tsx
- frontend/src/components/entity/EntityCard.tsx
- frontend/src/components/entity/EntityCardScores.tsx
- frontend/src/components/entity/EntityImagery.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/features/recommendation/CriteriaFilter.tsx
- frontend/src/features/recommendation/RecommendationApi.tsx
- frontend/src/features/recommendation/ScoreModeFilter.tsx
- frontend/src/features/recommendation/SearchFilter.tsx
- frontend/src/pages/home/presidentielle2022/HomePresidentielle2022.tsx
- frontend/src/pages/recommendations/RecommendationPage.spec.tsx
- frontend/src/pages/recommendations/RecommendationPage.tsx
- frontend/src/utils/action.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/types.ts
There are a few ugly workarounds in this PR to handle some differences between the videos recommendations and the candidate results:
* "total_score" are displayed in the entity card instead of tournesol score, to adapt dynamically with the selected criteria
* the default value for the `CriteriaFilter` is the main criterion, and the request parameters to the recommendations API have to be tweaked as the filter is currently only applied after the filter section is visible and its value changes.
* a new filter "Voting rights" is present (only for this poll for now)
It should close #833
> Candidates ranking page with total_score in card and multiple score modes 

- backend/tournesol/admin.py
- backend/tournesol/models/poll.py
- backend/tournesol/serializers/proof_of_vote.py
- backend/tournesol/tests/test_proof_of_vote.py
- backend/tournesol/urls.py
- backend/tournesol/views/exports.py
- backend/tournesol/views/proof_of_vote.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/scripts/openapi.yaml
- frontend/src/pages/personal/feedback/FeedbackPagePresidentielle2022.tsx
- frontend/src/pages/personal/feedback/ProofOfVote.tsx
* New API route `GET /users/me/proof_of_votes/{poll_name}/`
The signature is computed by a Django [`Signer`](https://docs.djangoproject.com/en/4.0/topics/signing/#module-django.core.signing), derived from the server `SECRET_KEY`, the poll name and the user id.
* Link on polls list for admins to download a .csv file with all signatures
* The code is visible at the top of the personal feedback page
> API for "proof of vote", add the signature on the personal feedback page

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/App.tsx
- frontend/src/app/PollRoutes.tsx
- frontend/src/pages/entities/CandidateAnalysisPage.tsx
- frontend/src/pages/entities/EntityAnalysisPage.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
- frontend/src/utils/action.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/types.ts
**related to** #830
---
Done:
- wiring the router for the entity analysis page
Todo:
> [front] feat: add the candidate analysis page

- frontend/src/features/feedback/StackedCandidatesPaper.tsx
- frontend/src/features/feedback/StackedCriteriaPaper.tsx
This PR disables the `Make new comparisons` buttons on the personal feedback page when the poll is inactive.
> [front] feat: do not invite people to compare in inactive poll

- CONTRIBUTING.md
- dev-env/update-openapi.sh
Updating openapi when using dev-env is not easy. The `yarn update-schema` command doesn't work within the container (`wget` is not installed and the API is not accessible through the default `localhost:8000`). So I made a small script to do it.
It may be better to make `update-schema` work in the container, but this solution is simple (and `curl` is already a requirement). I'm not sure where it should be documented though.
> Add script to update openapi with dev-env

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/entity/style.ts
- frontend/src/pages/entities/CandidateAnalysisPage.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
This small PR aims to harmonize the look and feel of the analysis page of all polls.
**(1)**
The pages have now a dedicated section for the main actions they provide. The candidate page slightly invite the users to check the global ranking (using an outlined button), while the video page invite more frankly the users to compare the video (using a contained button).
**idea**: what about adding a share button next the compare button in the top right corner of the video analysis page? This will allow users to quickly copy / paste link (maybe share the page on social network), and may create a virtuous circle where people share & compare videos more easily.
**(2)**
The candidate and video analysis pages now use the same `<Container>`, the same width, and the same global padding. Both page are …
> [front] refactor: sync' the style of candidate & video analysis page

- infra/ansible/roles/base/tasks/main.yml
Required by #702, to read the server configuration in a more robust way, instead of parsing the .yml file manually.
> Add `jq` into infra base packages

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/components/entity/EntityImagery.tsx
The commit 3d2e33e seems to have broken the display of the video player for mobile.
I verified this new code both for presidentielle2022 and videos polls on both laptop and mobile. Only the presidentielle2022 page my comparisons page on mobile is still not working well, but it is less pressing to fix.
> [front] fix: video card aspect ratio on most mobile layout

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/features/videos/VideoCard.tsx
I've been able to use Tournesol on mobile, and I found it difficult to click on the correct entity card actions. These action buttons are rather small, and it causes problem when their are close to each other.
I followed the design of the common action bar available on Android at the bottom of the screen (action previous / menu / all window).
|-------------|-----------|
| ![screencapture-localhost-3000-recommendations-2022-05-16-10_24_33](https://user-images.githubusercontent.com/39056254/168551422-ab825f9c-30e8-4cae-8353-0f73f44f675a.png) | ![screencapture-localhost-3000-recommendations-2022-05-16-10_24_49](https://user-images.githubusercontent.com/39056254/168551455-7029786d-60d3-46e2-940a-a6f3f55d3c2e.png) |
|-------------|-----------|
| …
> [front] style: `EntityCard` actions are now more accessible on mobile

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/components/entity/EntityCardTitle.tsx
- frontend/src/features/videos/VideoCard.tsx
- frontend/src/pages/entities/CandidateAnalysisPage.tsx
**related to** #931
---
This PR is the first step of the issue #931 , making the entities' titles clickable.
The following steps will be to make the thumbnail clickable, remove the analysis action and add a e2e tests.
> [front] feat: entities' titles are now clickable

- backend/README.md
I followed the YouTube API key installation procedure from the back end's `README.md` to work on #931, and I took the time to update it to make it more explicit.
a ~ the requirements are now clear and more exhaustive
b ~ it is described when an action needs to be performed from a specific page of the Google Cloud dashboard
c ~ I didn't need to create a "test" user by visiting https://console.cloud.google.com/apis/credentials/consent as described before, so I didn't seem required I deleted this step (also it wasn't clear what kind of user it was... was it a Google Account? is it required if we already have a Google Account?)
d ~ nevertheless I needed to enable the API key by visiting a specific URL, so I added this step
You can see the rendered `README.md` here: …
> [back] docs: make the YT API key setup more explicit

- backend/README.md
This pull requests revamps the YouTube API key installation, by fixing problems we encountered with @adrausch .
The procedure should now follow a more natural flow.
To avoid back and forth between the Google Cloud console and the code source, every steps related to the console are grouped together, and the back end configuration is done at the end.
See:
https://github.com/tournesol-app/tournesol/blob/back-update_ytapi_install/backend/README.md#set-up-a-google-api-key
> [back] docs: rework the YT API key installation procedure

- browser-extension/src/background.js
Following #913 the preferred languages were ignored in the extension recommendations.  
`metadata[language]` needs to be used instead of `language` and the separator `,` is no longer supported to pass multiple values.
> Fix metadata language filter in browser extension requests

- frontend/src/components/entity/EntityImagery.tsx
- frontend/src/features/videos/VideoCard.tsx
**related to** #931 
---
The `<PlayerWrapper>` is now a `<DurationWrapper>` able to display the video duration on top of both players and thumbnails.
> [front] fix: duration not displayed on videos' thumbnails

- frontend/src/features/videos/VideoList.tsx
- frontend/src/utils/constants.tsx
**related to** #931
---
The analysis page is now accessible by clicking on the videos' thumbnails and titles, so the analysis button in the entity lists is not required anymore.
> [front] refactor: hide the non-required `AnalysisPageLink`

- frontend/package.json
- frontend/src/pages/videos/VideoAnalysisPage.tsx
- frontend/yarn.lock
Related to #948 
After a discussion with @amatissart linkify-string is a library which produce harmless links and convert HTML entities in encoded characters compared to linkify-html library (https://linkify.js.org/docs/xss.html)
> [front] fix: do not interpret HTML tags from YT videos description

- backend/tournesol/suggestions/suggested_video.py
As discussed with @Foebus, in the previous implementation the denominator could equal 0.
And I think there is another typo in the numerator : 
```python
self.score_uncertainty + reference.score_uncertainty / ( ... )
```
should be
```python
(self.score_uncertainty + reference.score_uncertainty) / ( ... )
```
> suggestions: Fix score for suggested videos with video reference

- frontend/src/components/CriteriaBarChart.tsx
- frontend/src/features/charts/CriteriaScoresDistribution.tsx
- frontend/src/hooks/useCriteriaChartData.ts
- frontend/src/hooks/useSelectedCriterion.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
- frontend/src/utils/criteria.ts
Related issue: #933 
This branch and PR are made on top of https://github.com/tournesol-app/tournesol/pull/958. I didn't add the commits directly to the previous PR because it has already been reviewed.
It makes the criterion selectable in the bar chart. When selected the criterion chart has a light grey background (the same grey as in the paper title).
I also made a few extra changes:
- the "largely recommended" criteria is now yellow (the same yellow as in the main title bar)
- the bar color on the criteria scores distribution chart is now the criterion color
- fixed the criteria order in the bar chart to match the order in the comparison form. It also makes all the criteria listed even if some of them do not have a score
> Selectable criterion on bar chart

- backend/tournesol/models/entity.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_api_video_rate_later.py
- backend/tournesol/views/comparison.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
My rate later list is growing unsustainably which makes it lose its purpose. I propose to automatically remove the videos after 4 or more comparisons.
> [back] feat: automatically remove videos from rate later list

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/entity/EntityCard.tsx
- frontend/src/components/entity/EntityCardScores.tsx
- frontend/src/components/entity/EntityCardTitle.tsx
- frontend/src/components/entity/EntityImagery.tsx
- frontend/src/components/entity/EntityMetadata.tsx
- frontend/src/components/entity/style.ts
- frontend/src/features/entity_selector/EntityTabsBox.tsx
- frontend/src/features/videos/VideoCard.tsx
- frontend/src/utils/video.ts
This adds a new component `EntityTabsBox`
Accepts a list of `EntityTab` in props, to define how to fetch the different lists of entities.
A few limitations:
* uses `RowVideoCard` (to be made more generic in the future)
* tabs style is based on MUI `Tabs` (could be customized?)
The first use-case will be to enrich the VideoInput, with the possibility to pick a video from multiple tabs (see #856)
> Implement `EntityTabsBox` to use in video selector and analysis page

- dev-env/README.md
- dev-env/run-docker-compose.sh
Docker has released a V2 for Docker compose, integrated in Docker CLI, instead of the previous docker-compose binary.
https://docs.docker.com/compose/
By default, Docker suggest to install the docker compose plugin, like in this tutorial : 
https://docs.docker.com/engine/install/ubuntu/
Tournesol's dev_env sh script use the docker-compose binary to set up the dev env. The script can be adapted to automatically detect if that binary is either present or either docker compose plugin is.
enhancements :
* auto detection user's config :
* A docker-compose is present
* docker compose plugin is installed
* None, script should advise to install one
* tear down command
> [dev-env] feat: support docker-compose-plugin in addition to docker-compose

- browser-extension/src/addVideoStatistics.js
- browser-extension/src/browserAction/menu.js
- browser-extension/src/manifest.json
The browser extension now uses the new `/entities/` front end's URL instead of the legacy `/video/`.
> [ext] refactor: use the new `/entities/` URL instead of `/video/`

- backend/tournesol/suggestions/suggested_user_video.py
- backend/tournesol/suggestions/suggestionprovider.py
- backend/tournesol/tests/test_suggestions.py
A server error could be raised when a new video is present in the database with comparisons, but without contributor score.
This should fix the error reported by @GresilleSiffle in #856.
@Foebus Is `0.0` an appropriate default value for the `score_uncertainty` in `SuggestedUserVideo` ?
> [back] fix: server error on `entities_to_compare` 

- backend/twitterbot/tests/test_tournesolbot.py
- backend/twitterbot/tournesolbot.py
When there was a "." in between words in a video title, it was detected as a link by Twitter (and use 23 characters) which leads to too long tweet. Now, this kind dot in between words is replace by a character which look link a dot --> "｡"
> [twitterbot] fix unwanted link in video title

- backend/tournesol/serializers/inconsistencies.py
- backend/tournesol/tests/test_api_contributor_recommendations.py
- backend/tournesol/tests/test_api_inconsistencies.py
- backend/tournesol/urls.py
- backend/tournesol/views/inconsistencies.py
- frontend/scripts/openapi.yaml
Please double-check that there is no mistake in the function _count_cycles_and_comparison_trios.
I actually prefer to avoid also implementing an API endpoint that returns a single cycle, but of possibly longer length, because:
- it requires time and effort, and complicates things
- It would be complicated to display on the frontend
- It doesn't provide overview on how many cycles are left (we can't computationally count the cycles of any length, this would be NP-complex)
> inconsistencies part 2/2 : cyclic inconsistencies (#671)

- backend/tournesol/suggestions/suggestionprovider.py
- backend/tournesol/tests/test_suggestions.py
Although a "staff" user was created in the setup of `SuggestionAPITestCase`, it was not correctly configured as a super-trusted (no trusted email).  The usage of `self._entity_to_video` should be safe now and is covered by the unit tests.
Thanks @GresilleSiffle for reporting this bug.
> [back] fix: entities_to_compare fails after a new video is compared by a supertrusted

- backend/tournesol/tests/test_api_unconnected_entities.py
- backend/tournesol/views/unconnected_entities.py
Some of the data structures (including the set of "visited nodes") would persist across requests. This is due to how in Python, attributes initialized in the class definition are owned by the Class object itself, and not by the instances.
These attributes initialization were expected to be reset for each request (i.e view instances)
```python
_already_visited_node_ = set()
_all_connections_ = defaultdict(set)
```
Here it seems less error-prone to instead move the algorithm inside `get_queryset()` and make the scope of these structures more explicit.
> [back] fix: Unexpected side-effect in unconnected_entities view

- frontend/src/components/CriteriaBarChart.tsx
Continued from https://github.com/tournesol-app/tournesol/pull/958.
* moves the score tooltip above the bar on mobile
* removes the blue highlight that appears when clicking on a criterion on Chrome mobile
> [front] style: improve the bar chart on mobile

- frontend/src/components/LoaderWrapper.tsx
- frontend/src/features/entity_selector/EntityTabsBox.tsx
The scroll on the mobile view was broken after the list have been wrapped inside `LoaderWrapper` in #856
> [front] Fix scroll on mobile in EntityTabsBox

- frontend/src/features/entity_selector/EntityTabsBox.tsx
The `useEffect` cleanup function is used to ignore the response if the tab value has changed.
> [front] fix: ignore request results after moving to another tab in EntityTabsBox

- backend/tournesol/entities/base.py
- backend/tournesol/tests/test_api_polls.py
...instead of the previous HTTP 500.
If the `detail` parameter of the `rest_framework.exceptions.ValidationError` is dict, the view will consider it as a JSON response with a HTTP 400 code, else HTTP 500.
I prefixed the key by `_url_` to make it more clear that the error is not related to a form field, but to a URL parameter.
> [back] fix: `validate_meta_filter_field` now raises an HTTP 400 error

- backend/tournesol/lib/public_dataset.py
- backend/tournesol/views/exports.py
**related to** #988 
---
The PR reworks the way the `ExportPublicComparisonsView` used to retrieve the public dataset.
Instead of doing several non-optimized SQL queries due to the Django's ORM limitations, I used a raw SQL query to directly retrieve the public comparisons.
I created a folder `lib`, to avoid storing the raw SQL query in the view, and to invite us to factorize similar functions when relevant.
> [back] perf: speedup `ExportPublicComparisonsView` with raw SQL

- LICENSE.md
- README.md
- analytics/README.md
- backend/README.md
- browser-extension/README.md
- frontend/README.md
- infra/README.md
This PR adds, for each sub-folder having a license, a Copyright notice, license disclaimer and a direct link to the license.
I didn't update the `README.md` of sub-folders without license, like the `dev-env` and the `tests`. I'd like to think about what license is appropriate for those folders, even if I think the AGPL will be a very good candidate.
See the main `README.md` here: https://github.com/tournesol-app/tournesol/blob/chore-copyright/README.md#copyright--licenses
See the back end's `README.md` here: https://github.com/tournesol-app/tournesol/blob/chore-copyright/backend/README.md#copyright--license
> [all] chore: add copyright notices and license disclaimers

- frontend/src/features/frame/components/topbar/AccountInfo.tsx
- frontend/src/features/frame/components/topbar/PersonalMenu.tsx
- frontend/src/features/settings/SettingsMenu.tsx
- frontend/src/utils/menus.tsx
- tests/cypress/integration/frontend/login.ts
- tests/cypress/integration/frontend/resetPassword.ts
- tests/cypress/integration/frontend/settingsAccountPage.spec.ts
- tests/cypress/integration/frontend/settingsProfilePage.spec.ts
**related to** #998 
---
This PR adds a personal menu, displayed when the logged user click on its profile button.
I deleted the logout button to included it directly in the personal menu:
- it saves space in the top bar, especially on mobile, could be useful for other things (a comparison cart ?)
- the logout action is not part of the main use cases of the application
**to-do**
> [front] feat: add a top-right menu

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/entity/EntityCard.tsx
- frontend/src/features/entity_selector/EntityInput.tsx
- frontend/src/features/entity_selector/EntityTabsBox.tsx
- frontend/src/features/recommendation/ContextualRecommendations.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
Related issue: #938 
It adds a side panel to the video analysis page with 2 tabs : videos of the same channel and videos it has already been compared to.
Some notes:
* I added `unsafe: true` to the same channel request to get results in dev-env, but I don't know if it should be used in production.
* I added some style props to `EntityTabsBox` to have a correct width and height. You may prefer another way to do it.
* I also added a `withLink` prop to `EntityTabsBox` to have real links (instead of a `onClick` that would change the URL). The link is only on the thumbnail and title like in video cards.
* The layout is not exactly the one in #928. I made the side panel continue on the whole page instead of only up to the collapsible description, because doing it like in #928 is more difficult …
> Contextual recommendations on video analysis page

- frontend/src/pages/videos/VideoAnalysisPage.tsx
This PR removes the horizontal scroll of the analysis page when displayed on mobile.
The usage of `<Box>` instead of `<Grid>` did the trick.
The width definition of the two flex items are a bit verbose. I wanted to make the first item (the video) take approx 65 % and I expected the second item (the contextual recommendations) to take the remaining space thanks to `flexGrow={1}` but I didn't manage to make it work.
Without the `flexGrow` the layout is still nice but there is and extra blank space at the end of the flex container that could be used by the contextual recommendations (for now, I moved this space between the items with `justifyContent="space-between"`, but it doesn't solve the problem).
> [front] fix: flex layout on analysis page not good on mobile

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/buttons/CopyToClipboardButton.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
**related to** #915
**estimated BL** 10 per year
---
This PR adds a button on the video analysis page, that allows to directly copy the current URI to the browser clipboard.
This is the first step of the issue #915. This button could be replaced in the future by a proper share button, as described in the issue.
https://user-images.githubusercontent.com/39056254/176186724-022f58a7-a3cb-4ca9-99d7-31ea33abb3d1.mp4
> [front] feat: add a copy URI button on the analysis page

- analytics/requirements.txt
The version 1.22.4 includes several bug fixes.
Release notes:
- 1.22.1: https://github.com/numpy/numpy/releases/tag/v1.22.1
- 1.22.2: https://github.com/numpy/numpy/releases/tag/v1.22.2
- 1.22.3: https://github.com/numpy/numpy/releases/tag/v1.22.3
- 1.22.4: https://github.com/numpy/numpy/releases/tag/v1.22.4
> [analytics] chore: bump `numpy` from v1.22.0 to v1.22.4

- backend/vouch/tests/test_trust_algo.py
- backend/vouch/trust_algo.py
I rewrote the code to make it more human-readable. I verified that it successfully pass the tests.
There may be a need to go further to avoid ambiguities, as the word "trust" is used with too many slightly different meanings.
In particular, I would suggest:
1. The user's field "trust_score" could be replaced with "voting_right".
2. The vouch's field "trust_value" could be replaced by "vouch_value".
3. The vouch's field "by" could be replaced by "from".
As a result, while "trust" remains not fully well defined (currently, in the code, it only matters if it is > 0), the word "relative_trust" implies a sum of all users' relative trusts equals 1. Conversely, a user's "voting_right" an take any positive number. Moreover pretrusted users (by email domains) are guaranteed to have a voting right …
> [back] fix: vouching made more human-readable

- frontend/src/features/recommendation/SearchFilter.spec.tsx
- frontend/src/features/recommendation/SearchFilter.tsx
* the min field doesn't work on Firefox desktop
* the pagination doesn't work when the duration filter is active
> [front] fix: disable the duration filter

- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/entity.ts
- frontend/src/utils/polls/videos.ts
- frontend/src/utils/types.ts
**related to** #844 
---
This PR changes the type of entity recommended by the `videos` tutorial.
Suggested entities:
- are now **safe recommendations**
- are in the **top 40 of all-time** recommendations...
- ...having a maximum duration of **5 minutes**
After having submitted their last comparison in the `videos` tutorial, the users were abruptly redirected to a blank comparison page, without any message or feedback of any kind. Even for me, as a confirmed user, it was unexpected and confusing. I didn't know if my last comparison was successfully submitted or not.
In this PR I decided to redirect the users to their own comparisons page, to allow them to see their progress, and to confirm their last comparison was correctly saved.
To create a virtuous circle, we could add the same …
> [front] feat: use only 5 min. max videos for the tutorial

- backend/settings/settings.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/views/comparison.py
With the current implementation, computing and writing all individual scores may be a bit slow (up to a few seconds) for users with a large number of comparisons. 
As a lighter implementation is being worked on in #1010 to update the scores "online", this PR disables this mechanism temporarily (controlled by a new setting `UPDATE_MEHESTAN_SCORES_ON_COMPARISON`).
In the future, we could also consider running this kind of update in a background task (ideally with minimal additional complexity in the architecture).
> mehestan: Disable individual scores update on comparison submission

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/app/PollRoutes.tsx
- frontend/src/components/ContentHeader.tsx
- frontend/src/features/entity_selector/EntityInput.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/features/frame/components/topbar/PersonalMenu.tsx
- frontend/src/features/ratings/RatingsFilter.tsx
- frontend/src/features/recommendation/ScoreModeFilter.tsx
- frontend/src/features/recommendation/SearchFilter.tsx
- frontend/src/pages/recommendations/RecommendationPage.spec.tsx
- frontend/src/pages/recommendations/RecommendationPage.tsx
- frontend/src/pages/videos/VideoRatings.tsx
- frontend/src/utils/api/comparisons.ts
- frontend/src/utils/api/recommendations.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/types.ts
- tests/cypress/integration/frontend/publicPersonalRecommendationsPage.ts
- tests/cypress/integration/frontend/recommendationsPage.ts
**related to** #1003 
---
This pull request adds the public personal recommendations page.
This page is only accessible if the poll explicitly enables the personal reco. feature. Contrary to the `videos` poll, the `presidentielle2022` poll doesn't allow the users to display personal recommendations. 
**next step:** make the URL easily share-able. 
**note:** Due to a JSON payload difference between the recommendations API and the personal recommendations API, it's not possible to display the notice  `The relevance of this score is uncertain, due to too few contributors.` on the personal recommendations page. We should harmonize those two API to avoid displaying misleading Tournesol score.
**(a)** the `RecommendationPage` must be able to retrieve public personal reco.
**(b)** the UI must …
> [front] feat: make `RecommendationPage` able to display personal reco.

- backend/tournesol/tests/test_api_unconnected_entities.py
- backend/tournesol/views/unconnected_entities.py
The goal is to invite the users to compare the entities with the least comparisons first, and to make the list of unconnected entities dynamic.
Before, the front end tab "to connect" always displayed the same videos, when called with a never compared video. This was not satisfying, as it could suggest videos that have been already compared several times by the user. Now the users will see a more diverse list of videos, as its order will change after each new comparison with an unconnected entity.
I took the time to add more comments in the tests and to rename some methods, so it's now explicit what the test cases are testing: a single well connected graph, two isolated graphs, a single graph with too distant entities, etc.
**to-do**
> [back] feat: unconnected entities are now ordered by n_comparisons

- frontend/src/features/recommendation/DurationFilter.tsx
- frontend/src/features/recommendation/SearchFilter.spec.tsx
- frontend/src/features/recommendation/SearchFilter.tsx
- frontend/src/hooks/useListFilter.ts
This PR fixes the infinite rendering loop caused by the `<DurationFilter>`.
This should fix:
- the `<DurationFilter>` filter on Firefox
- the reset pagination bug, when clicking on next with a duration filter active
To achieve this I removed the `onChangeCallback` from the `<DurationFilter>` effects' dependencies.
(I also moved the code responsible of the state `min` before the state `max` just to please my brain.)
> [front] fix: prevent `DurationFilter` infinite rendering

- backend/ml/mehestan/global_scores.py
- backend/ml/mehestan/individual.py
- backend/ml/mehestan/run.py
PR goal : fix raw_scores save in Mehestan Algorithm
Currently, individual scaled scores are saved into raw_scores (along with uncertainty) [tournesol_contributorratingcriteriascore] when computing post scaling operations 
(see https://github.com/tournesol-app/tournesol/blob/main/backend/ml/mehestan/run.py#L134)
As discussed with @amatissart , these two lines are not intended in the poll scaling mehestan algorithm.
In order to save properly the individual contributions [tournesol_contributorratingcriteriascore] , 
the function "save_contributor_scores" need as input a dataframe with raw_score and raw_uncertainty
(see https://github.com/tournesol-app/tournesol/blob/main/backend/ml/outputs.py#L135)
However, in the mehestan algorithm, the steps are the following for each criteria: 
1 - …
> [back][ml] Fix raw scores mehestan

- frontend/src/utils/video.ts
**related to** #1013
---
I kept the original way, just improved the RegExp in `./frontend/src/utils/video.ts`
You can visualize the new RegExp workflow [here](https://regexper.com/#%2F%28%3F%3Ahttps%3F%3A%5C%2F%5C%2F%29%3F%28%3F%3Awww%5C.%29%3F%28%3F%3Ayoutube%5C.com%5C%2Fwatch%5C%3Fv%3D%7Cyoutu.be%5C%2F%7Ctournesol%5C.app%5C%2Fentities%5C%2Fyt%3A%29%28%5BA-Za-z0-9-_%5D%2B%29%2F)  on [RegExper.com](url)
> [front] feat: analysis URLs are now accepted by the entity selector

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/home/presidentielle2022/HomePresidentielle2022.tsx
- frontend/src/pages/home/videos/HomeVideos.tsx
- frontend/src/utils/constants.tsx
- tests/cypress/integration/frontend/home.ts
**related to** #1046 
---
The behaviour matches the `presidentielle2022`:
- users are always invited to contribute thanks to the button Start
- anonymous users are invited to create an account
- if the poll is closed, a message is displayed and a link to the recommendations 
I finally reverted my change concerning the redirection. I didn't want users having already a lot of comparisons, being redirected  to their own list of comparisons when they click on `Start`. The start button should allow them to start to compare quickly, not to see their previous comparisons, having to expand the menu and click on Compare (3 clicks).
Drawback of this revert: new users are abruptly redirected to an empty comparison page after having submitted the last comparison of the tutorial. This was the main …
> [front] feat: `videos` tuto accessible on Home

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/buttons/CopyToClipboardButton.tsx
- frontend/src/features/menus/ShareMenu.tsx
- frontend/src/features/menus/ShareMenuButton.tsx
- frontend/src/pages/recommendations/RecommendationPage.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
**related to** #1056 
---
This PR adds a `ShareMenuButton` that can be used everywhere in the application.
This new component uses and intern `ShareMenu` that can display several sharing options. For now, only `Copy the page address` is available.
The share menu is displayed:
- on the collective recommendations page
- on the public personal recommendations page
- and on the video analysis page
> [front] feat: add copy to clipboard action on the reco. pages

- backend/tournesol/views/stats.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/statistics/UsageStatsSection.tsx
The front end used to display the metric active users.
Active users could be:
- users that have done comparisons on a regular basis
- users that still do comparisons on a regular basis
- users with a least few comparisons
- etc.
It was a bit misleading and I remember Lê asking for the meaning of this metric during a live on Discord or YouTube.
I think **activated accounts** is more appropriate.
> [front] fix: misleading "Active users" metric name

- infra/ansible/inventory.yml
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/django/templates/discord-twitterbot-fail-alert.sh.j2
- infra/ansible/roles/django/templates/tournesol-twitterbot.service.j2
- infra/ansible/roles/django/templates/tournesol-twitterbot.timer.j2
The new "oneshot service" will run daily at 18:03 (Swiss time).  
On Monday, Tuesday, Thursday, Friday a tweet will be sent in French.
On Wednesday, a tweet will be sent in English. 
This new schedule is defined for production only. The timer is inactive on other environments (where twitter credentials are unavailable anyway).
> [twitterbot] create systemd service and define schedule for automated tweets

- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_api_rate_later.py
Overriding YOUTUBE_API_KEY was not sufficient, because it does not cause the "youtube" variable in api_youtube.py to be recreated.
> 2 backend tests were failing when YOUTUBE_API_KEY was set (#1044)

- dev-env/README.md
- dev-env/run-docker-compose.sh
1 - Not using realpath, which can give problematic results in Windows (e.g. paths that start with "C:/" instead of "/c/" in MinGW)
2 - Exporting DB_UID and DB_GID, to simplify the code => check that it doesn't have side effects on child scripts
3 - Changing the position of the "", just because it looks cleaner
It's very possible that it doesn't work on every environment, or that there still are bugs, or that it's not a clean solution.
I'll first call JST as a reviewer for his opinion, then ask someone with other OS (Mac, Windows), to see if it's an improvements and if there is no regression.
**Don't hesitate to report any remaining issue with dev-env.**
In Windows, the postgres uid and gid are fixed to 999, and can't be easily changed. So, if `$(id -u)` and `$(id -g)` were returning …
> Update of dev-env, notably for Windows compatibility (#993)

- backend/twitterbot/tests/test_get_twitter_account.py
- backend/twitterbot/uploader_twitter_account.py
On a YT channel page, the link to twitter account may contain extra params, which should be ignored to extract to the twitter account handle. (See unit test for details).
> [twitterbot] fix: incorrect handle when twitter link has extra params

- backend/twitterbot/uploader_twitter_account.py
* accept optional "www" subdomain in twitter URLs
* use /about page instead of channel home page (which may contain more noise, including the description of a featured video)
> [twitterbot] fix: robustify twitter account extraction

- browser-extension/src/manifest.json
- browser-extension/src/utils.js
**indirectly related to** #606
---
This PR makes the extension use the new generic rate later API instead of the deprecated one.
> [ext] refactor: use the generic rate later API

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
**related to** #1099
This small PR adds few words in the tutorial to make it clear that:
- a **comparison is actually a contribution** to the project
- Tournesol uses comparisons **to make recommendations**
- going through the tutorial **helps** the Tournesol project
We might want one day to review the tutorial texts in details, in the meantime this is my subjective attempt to make the tutorial more clear without increasing its size and without adding too much text.
Hope it helps : )
> [front] fix: more involving tutorial messages

- frontend/package.json
- frontend/scripts/generate-services-from-openapi.sh
- frontend/src/pages/personal/vouchers/VouchersPage.spec.tsx
- frontend/yarn.lock
The bug related to single quotes has been fixed in recent versions of "openapi-typescript-codegen"  
See: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/v0.23.0/CHANGELOG.md
This change also removes the usage of `sed` in "generate-services-from-openapi.sh", which was known to cause compatibility issues on MacOS.
> [front] chore: upgrade lib and remove workaround related to single quotes in openapi.yml

- backend/core/locale/fr/LC_MESSAGES/django.po
- backend/tournesol/locale/fr/LC_MESSAGES/django.po
- backend/vouch/models.py
- backend/vouch/tests/test_model_voucher.py
It should not be possible for a user to vouch for him/herself.
The `clean()` method will ensure saving a model through the administration interface, of by code, will raise a proper `ValidationError` with a translated message.
> [back] fix: prevent a `Voucher` to be saved with the same `by` and `to`

- backend/scripts/ci/lint.sh
- backend/vouch/trust_algo.py
Now that `Pylint` has been upgraded the code cleaned, we can easily add the `vouch` app to the list of folders monitored by our linters.
I had to rename an annotation to get rid of the starting underscore. I changed the name of the variable to avoid shadowing the `User.is_trusted` property.
> [back] ci: apply the linters on the `vouch` app

- backend/scripts/ci/lint-fix.sh
- backend/vouch/tests/test_trust_algo.py
- backend/vouch/trust_algo.py
* split tests about trust_algo into 2 classes
* ensute that at lest 1 pretrusted user exists in "pretrusts" vector used in unit tests
* cover edge cases in tests: no pretrusted user, no voucher in database
> [back] tests: fix flaky tests about trust_algo and cover edge cases

- backend/tournesol/tests/test_api_preview.py
- backend/tournesol/views/preview.py
A small regression introduced in #1084 about the default preview image.  
It went unnoticed as the response content was not covered by tests.
The documentation about `FileResponse` explains why a context manager should not be used in this case:
https://docs.djangoproject.com/en/4.0/ref/request-response/#fileresponse-objects
So ignoring the pylint warning should be ok here.
> [back] fix: file used as default preview image was closed when used in `FileResponse`

- CONTRIBUTING.md
Our current `CONTRIBUTING.md` file is focused on how to help while being a programmer, but Tournesol is not only a programming project. It's also collective research project involving comparing videos and creating an open database of users' judgement.
This `CONTRIBUTING.md` rework aims to explain how to contribute to Tournesol, by making comparison, by considering giving money, by reporting bugs, making suggestions, etc. It also aims to clearly state where to ask what: bugs should be on GitHub, general purpose questions on Discord.
In this first step I didn't add the code of conduct, to keep the PR small, but I'd like to propose the team to add one. As it implies some governance considerations, we should talk about it separately.
In a future PR I plan to rework the content of the …
> [all] docs: rework CONTRIBUTING.md

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/App.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/pages/faq/FAQ.tsx
- frontend/src/pages/faq/FAQEntryList.tsx
- frontend/src/pages/faq/FAQTableOfContent.tsx
- frontend/src/utils/types.ts
**related to** #1140
---
This PR adds a FAQ and a link to it in the sidebar. If no entries are returned by the back end the page invites the users to ask their questions on Discord.
**to do**
Regardless of the number of FAQ entry, users are always invited to join Discord if they didn't find the answer to their questions.
(On the following capture is old, that is why the Discord button is not displayed)
> [front] feat: display the FAQ

- frontend/src/features/charts/CriteriaScoresDistribution.tsx
- frontend/yarn.lock
Update `recharts` version from `2.1.9` to `2.1.14`.
This also updates the problematic dependency `d3-color` from its vulnerable version `2.0.9` to its fixed version `3.1.0`
See:
- https://github.com/advisories/GHSA-36jr-mh4h-2g58
- https://github.com/tournesol-app/tournesol/security/dependabot/53
> [front] sec: update `recharts` and its vulnerable dep `d3-color`

- backend/requirements.txt
Fix:
- CVE-2022-41323
See: https://docs.djangoproject.com/en/4.1/releases/4.0.8/
> [back] sec: upgrade django to 4.0.8 (from 4.0.7)

- browser-extension/src/browserAction/menu.html
- browser-extension/src/browserAction/menu.js
- browser-extension/src/manifest.json
Extension can now reach tournesol.app website while on (non-)youtube page with now clickable logo to `https://tournesol.app`
as issued in #339
> [ext] add tournesol.app link to clickable tournesol logo

- README.md
This PR is a proposition to make the introduction in the `README.md` more user friendly and accurate. It's secondary objective is to deprecate the usage of "public utility".
As we have gained some experience in shortening ideas, I tried to be as short as possible while adding some important information. Two paragraphs maximum, one medium sentence each, but full of meaning : )
**(a)** I replaced the usage of "public utility" by "public interest" here, as public utility doesn't seem to have the meaning we expected.
**(b)** I described what we consider to be public interest by simply adding "videos that should be largely recommended". These few words make the connection between the concept of public interest and what kind of judgement the participants will make in the front end.
**(c)** I …
> [all] chore: make the `README.md` intro more friendly

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/faq/FAQEntryList.tsx
- frontend/src/pages/faq/FAQTableOfContent.tsx
- frontend/src/utils/notifications.ts
The look and feel of the FAQ page was a bit raw, and its text not very pleasant to read.
In order to ease the reading I added a white `<Paper>` for each question, increasing the contrast between the text and the brackground.
| before                                                                                                             | after                                                                                                             |
|--------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|
| ![capture2](https://user-images.githubusercontent.com/39056254/195390014-6a958e38-2869-470d-ad5e-987016 …
> [front] feat: better contrast between text and bg in the FAQ page

- backend/tournesol/utils/cache.py
- backend/tournesol/views/preview.py
This PR enable a 2 hours cache for the entity preview endpoint. 
To be sure we are not merging something we don't want: @lfaucon did we have a good reason to disable the cache in the preview API? Or was it just a leftover of a development configuration?
> [back] fix: enable the previously disabled cache for the entity preview

- backend/tournesol/entities/base.py
- backend/tournesol/entities/video.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/views/ratings.py
**related to** #1174 
---
This PR allows the results of the ratings API to be ordered by `duration` and `publication_date`.
As requested by some users, the default order has changed and is now `-last_compared_at` instead of the video metadata `publication_date`. This change will automatically be visible in the front end when the API will be updated.
Following the "never trust user input" principle, the available metadata fields that can be used to order a entity list through the ratings API are defined in a fixed allow list, per entity type. A `video` can be ordered by `duration`, a candidate no.
> [back] feat: ratings are now order-able by some entity metadata fields

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/home/AlternatingBackgroundColorSectionList.tsx
- frontend/src/pages/home/videos/ComparisonSection.tsx
- frontend/src/pages/home/videos/HomeVideos.tsx
- frontend/src/theme.ts
This section was redundant with the recent `ComparisonSection`.
This PR also:
* Increases the vertical padding of each section of the home page from 32 pixels to 48. This allows the home page to feel less "squashed" and more "modern", especially on mobile. I also tested 64 pixels, which is nice too but I'd prefer to wait for the complete home page refactor before proposing 64. 
* Updates the `AlternatingBackgroundColorSectionList` component to use the app palette instead of defining hard-coded custom colors. Also update this component to be able to choose the color of its last item displayed.
* Adds a title `ComparisonSection` has now a proper title.
The important part are the new contribute title, the color of the last sections (stats and polls) and the vertical padding of each section …
> [front] refactor: delete the `ContributeSection` from the videos home

- README.md
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/home/videos/HomeVideos.tsx
**related to** #1166
---
This PR reworks the first paragraphs of the Tournesol home page. It aims to make them more user friendly by reducing their complexity: less topics ; less words ; more assertive ; slightly bigger font.
The two questions answered by these paragraphs are:
- What is the Tournesol project?
- Why should I contribute?
The answers are of course not exhaustive, as they are discussed with more details in the About and the FAQ pages.
The new French version now contains 48 words instead of 83. The English 40 instead of 78.
**subjective opinion** I didn't explained that the comparisons will improve the recommendations, as this objective has been deferred to the future section "recommendations preview" designed in Miro. In the same way I didn't talk about the public database …
> [front] refactor: simplify the first home page paragraphs

- backend/tournesol/views/ratings.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/scripts/openapi.yaml
- frontend/src/features/ratings/RatingOrderByInput.tsx
- frontend/src/features/ratings/RatingsFilter.tsx
- frontend/src/hooks/useListFilter.ts
- frontend/src/pages/videos/VideoRatings.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/types.ts
- tests/cypress/integration/frontend/myRatedVideosPage.spec.ts
**follow the work of** #1174 
---
This PR adds an orderBy input in the front end's My rated elements page.
This input contains two generic values available for all entity type: `last_compared_at` and `n_comparisons`. On the poll `videos` two additional parameters are available: `duration` and `publication_date`.
The maximum width of the ratings page has been increased to match the recommendations page width, and to have more space to display the new input.
At first I wanted to create full and exhaustive tests for each ordering parameter. I then realized the front end only displays the results returned by the back end without altering the order. While the back end's tests doesn't 100% ensure the front end will work, the absence of complexity in the front end makes me feel that it might not …
> [front] feat: add an order by input in the ratings page

- frontend/package.json
- frontend/yarn.lock
Upgraded via `yarn upgrade`
An explicit resolution about "@types/react" had to be specified to avoid mixing multiple versions of React, which would break the TypeScript build.
This should also resolve the alert about a ReDos vulnerability in "minimatch".
> [front] chore: upgrade dependencies, including mimimatch

- frontend/src/components/CriteriaBarChart.tsx
- frontend/src/components/entity/EntityCardScores.tsx
- frontend/src/features/charts/CriteriaScoresDistribution.tsx
- frontend/src/features/videos/VideoCardScores.tsx
- frontend/src/utils/criteria.ts
**related to** #1157
Changes:
* Scores on CriteriaBarChart and tooltips are rounded to the nearest integer
* Removed the `displayScore`methods as they were duplicated and felt unnecessary
> [front] fix: round the criteria scores to the nearest integer

- backend/ml/mehestan/run.py
- backend/tournesol/tests/test_ml_run.py
As discussed in #1200 and on Discord, this PR splits the tests used to validate the behavior of the `ml_train` command.
Instead of using a single complex `setUp()`, each test case will define the relevant comparisons and other data needed to cover of aspect of the algorithms.
The new tests cases are:
* `test_individual_scaling_are_computed`
* `test_tournesol_scores_different_trust`
* `test_tournesol_scores_different_uncertainty`
* `test_tournesol_scores_different_privacy_status`
> [back] test: split tests about `ml_train` and simplify their setup

- frontend/src/App.tsx
- frontend/src/utils/ui.ts
When navigating to another page via a React Router link, the scroll position persisted to the previous position. Especially visible when clicking on "see more" in the Recommendations section on the home page.
The implementation is similar to the approach described on https://v5.reactrouter.com/web/guides/scroll-restoration/scroll-to-top
> [front] fix: reset scroll position on page change

- frontend/src/pages/home/videos/sections/ComparisonSection.tsx
- frontend/src/pages/home/videos/sections/SectionTitle.tsx
The goal is to display the instructions before the comparison on mobile, which is more coherent.
(The end of the capture is a bit glitched, sorry)
> [front] style: move the contribute description text to the left

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/about/TrustedDomains.tsx
- frontend/src/pages/personal/vouchers/TrustScore.tsx
As suggested by @sigmike , I propose to use this PR to update the translations in order to use trust score instead of voting right when it's appropriate.
Here are the translations we may want to update:
- **(wont fix, it's the correct terms)** https://github.com/tournesol-app/tournesol/blob/main/frontend/public/locales/en/translation.json#L239
Proposition for the key `howToChangeIt`:
Original
> You can increase it by using a certified email and when other users vouch for you.
Proposition
> You can gain more trust by using an email from a trusted domain or when other users vouch for you.
As discussed with Adrien, trusted domain is more accurate.
Additional proposition for the key `explanation`:
Original
> Your trust score changes how your comparisons count in Tournesol's recommendations. …
> [front] trans: use trust score instead of voting right in vouching page

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/components/footer/Footer.tsx
- frontend/src/utils/url.ts
This PR adds more social links in the footer (Tournesol Talks mailing list included).
The Follow Us section order is the following:
- the networks where we are the most active first (Twitter & Discord)
- the networks where we are less active after (Twitch & LinkedIn)
- the less social networks at the end (GitHub)
Note that the Tournesol Talks mailing list will also be included in the home page research section as requested by @lenhoanglnh.
> [front] feat: more social links in the footer + add the mailing list

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/TitledPaper.tsx
- frontend/src/pages/home/videos/sections/research/PublicDataPublicCodeBox.tsx
- frontend/src/pages/home/videos/sections/research/ScientificLiteratureBox.tsx
- frontend/src/pages/home/videos/sections/research/VisualizeDataBox.tsx
**related to** #1219 
---
The previously isolated buttons Download the database and Access the source code have been moved into the MUI papers for a better consistency with the rest of the app. A little paragraph has been to introduce the source code.
> [front] refactor: add a reusable `<TitledPaper>` component

- backend/tournesol/views/preview.py
**related to** #1230
---
The images returned by the preview API could be broken if one of the two videos didn't have a `maxres` thumbnail. For now, only `mq` will be use.
In the future, we could check if both videos have `maxres` thumbnails to determine the preview quality.
> [back] fix: temporarily downgrade the previews quality

- backend/ml/mehestan/primitives.py
- backend/ml/tests/test_mehestan_primitives.py
- backend/tournesol/tests/test_ml_run.py
Updates the algorithm computing the quadratically regularized uncertainty `QrUnc`. 
From **Section C.4** in supplementary material, the individual contributions to the second derivative used in the computation should be capped to 1/W, instead of 1.
>
> [back] fix: update `QrUnc` in ml primitives, as defined in reference paper

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
In order to harmonize the community rules, this PR adds a code of conduct that applies in Discord, GitHub, and other spaces where the Tournesol community is likely to interact.
It contains obligations for both regular users and community leaders. Are considered leaders all moderators, maintainers, members of the association committee and all other person that represent the Tournesol Association or the Tournesol Project.
It's a copy paste of the standard Contributor Covenant v2.1 with three little changes:
- the mention of race has been removed to avoid any kind of confusion, ethnicity seems to be enough 
- the mention of "any other dimension of human diversity" has been added 
- a simplified email address to contact the tournesol team has been added 
See …
> [meta] chore: add a `CODE_OF_CONDUCT`

- infra/ansible/roles/monitoring/templates/external-urls-monitoring.sh.j2
Instead of `wget`, let's use `curl` with these options:
* `-s`: Silent or quiet mode. Don't show progress meter .
* `--show-error`: when used with -s, it makes curl show an error message if it fails.
* `--fail`: Fail in case of non successful HTTP responses, including server errors.
This should help us to understand the false alerts that have been observed recently.
> [infra] fix: update external-urls-monitoring to show error message when failing

- backend/tournesol/views/preview.py
Related issue: #1230
For both previews the `maxres` quality is tried first. If it returns a 404 placeholder we try the cropped `hq` version, and if it still fails we return the `mq` thumbnail. If the `mq` thumbnail is still a placeholder we crop it to return the expected aspect ratio.
It may be better to fetch the list of available thumbnails with the YouTube API, but since the `maxres` version seems to exist on most videos this implementation doesn't add an extra request most of the time.
I'm not sure if a test is relevant here. Writing a good one seems to be difficult.
> `maxres` previews with fallback

- infra/ansible/inventory.yml
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/django/templates/tournesol-api-clearsessions.service.j2
- infra/ansible/roles/django/templates/tournesol-api-clearsessions.timer.j2
Our back end's admin interface saves the session data of logged users in the database. Django doesn't automatically clear the expired sessions, thus the `django_session` table slowly grows (very very slowly in fact).
The same way we manually clear the expired API refresh tokens every day, we should manually clear the expired sessions created when users log in the admin interface.
This PR adds a systemd timer that will delete all expired back end's sessions every day at 02:40am. We currently have 224 expired sessions in production.
```sql
SELECT count(1) FROM django_session WHERE expire_date < current_timestamp;
```
See: https://docs.djangoproject.com/en/4.0/topics/http/sessions/#clearing-the-session-store
> [infra] feat: set up a daily clean-up of expired back end's sessions

- frontend/src/index.css
This PR fix the typo `snackback` -> `snackbar`.
The application was literally u.n.u.s.a.b.l.e.
> [front] docs: fix a typo in a CSS comment

- infra/ansible/inventory.yml
- infra/ansible/roles/django/handlers/main.yml
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/monitoring/handlers/main.yml
- infra/ansible/roles/monitoring/tasks/main.yml
- infra/base-image/fetch-debian-image.sh
* "Populate Django DB" task was broken now that the dev-env uses a public database embedeed in a Docker image, et no dump is available in the repository.  
I think it can be removed. If needed, the database can be populated by either loading a backup (that should be tested regularly anyway) or by using the management command "load_public_dataset".
* Workaround a bug in Granafa when initializing admin password
* Update Debian base image version
> [infra] fix: VM provisioning

- backend/tournesol/models/poll.py
- backend/tournesol/tests/test_api_proof.py
- backend/tournesol/tests/test_proof_of_vote.py
- backend/tournesol/urls.py
- backend/tournesol/views/exports.py
- backend/tournesol/views/proof.py
- backend/tournesol/views/proof_of_vote.py
- frontend/scripts/openapi.yaml
- frontend/src/pages/personal/feedback/ProofOfVote.tsx
This PR enhances the previous proof of vote API to make it more generic and able to provide different kind of proof.
This need comes from our future study about the browser extension. Previously a proof was only provided for users having at least one comparison. This behaviour still exists but the API is now also able to provide a proof of "activated account" for users without comparison.
The proof view now accepts a keyword query parameter identifying the requested proof. It is used as an input by the signing algorithm, making the API able to provide a proof per poll per user per keyword. A keyword can be any string.
For instance, the `presidentielle2022` uses the keyword `proof_of_vote` to generate for each user a proof of participation.
The poll `videos` can now give to each user a …
> [back] feat: the proof of vote API is now a more generic proof API

- infra/ansible/roles/django/tasks/main.yml
Related to #1239 
With this [`backup`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#parameter-backup) option, a backup file with timestamp will be writen when the settings file have changed, such as:  
`/etc/tournesol/settings.yaml.77910.2022-12-20@00:19:07~`
> [infra] feat: keep backup of settings.yaml when it's updated by ansible

- backend/tournesol/tests/test_exports.py
- backend/tournesol/views/exports.py
The SQL query takes too much time to run, leading to HTTP timeout when downloading the full dataset from the front end.
> [back] fix: disable the individual criteria scores in the export

- infra/ansible/roles/logging/templates/alerting-dashboard.json.j2
False alerts could be triggered about the server latency, due to Grafana using long pending requests to fetch live data in some dashboards.
This is especially unfortunate to see these alerts when we are debugging unrelated errors on Grafana. So this change should reduce the noise and confusion.
> [infra] fix: exclude requests to grafana to compute 95th percentile in alert definition

- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/scripts/get-vm-secrets.sh
The back end's secrets are currently readable by all regular users on the server, no admin privilege is required.
This includes sensitive secrets like the database password, the Django secret key, the OpenID Connect private key and more. It should be a good idea to restrict the access to these secrets only to `root` and `gunicorn` user. All other users don't need to have this knowledge.
> [infra] sec: do not make secrets readable by all users

- backend/tournesol/lib/public_dataset.py
- backend/tournesol/resources/export_readme.txt
- backend/tournesol/tests/test_exports.py
- backend/tournesol/views/exports.py
I manually re-wrote the SQL query to have more control on it.
Now only the required columns are fetched from the database, which significantly reduce the amount of data read from the disk. The previous query used to fetch all columns of all involved tables (including hashed passwords) even if there were not used by the view.
The cost of this new query (in PostgreSQL arbitrary unit) is `48,233.24` contrary to the previous one which was `111,985.19`. The execution time is more than three time faster and could be even further reduced by sorting the results only by usernames (which can greatly increase the sorting effort required by people using our dataset).
Finally the view doesn't go from one table to another using the ORM, preventing any unexpected additional database queries.
> [back] feat: restore the individual scores export

- backend/tournesol/utils/contributors.py
Months and years were not correctly handled and failed now that we are in January :) Tests luckily caught it.
> [back] fix: support january in get_top_public_contributors_last_month

- infra/ansible/roles/postgresql/templates/pg-backups.service.j2
When introducing `post-on-discord.sh`  in #979, the script permissions have been restricted as it requires to be run in the Django virtualenv. 
One of the services relying on this script does not use the user "root" or "gunicorn" and needs extra permissions to trigger the alert (when the service fails).
> [infra] fix: ensure that discord alert script runs with necessary permissions in Systemd services

- frontend/src/index.css
Following the discussion in #1240, I realized this could be a quick fix, before the future comparison redesign on mobile (#1274)
This change would make the slider handle the only interactive part on sliders when using a touch screen (or any pointing device of limited accuracy covered by `pointer: coarse`).
Note that you need to emulate a mobile device to test this change on a desktop browser.
[Capture vidéo du 2023-01-07 11-42-52.webm](https://user-images.githubusercontent.com/4726554/211146921-7d9335d5-91d5-4043-b234-3111e34ed484.webm)
> [front] fix: disable pointer events on slider rails on touchscreens

- backend/tournesol/tests/test_api_unconnected_entities.py
- backend/tournesol/views/unconnected_entities.py
This is a first step for #1247. Next step would be to use this option in the frontend entity selector, but I prefer making this change once the backend route is approved.
> [back] feat: enable non-strict option in unconnected entities API route

- dev-env/docker-compose.yml
`pg_isready` is not enough to check that the "database" itself has been created and is ready:
https://dba.stackexchange.com/a/298647
> [dev-env] fix: postgres container could be healthy before the database is ready

- infra/ansible/roles/monitoring/tasks/main.yml
The Grafana packages are served from a different apt repository and our Ansible configuration must be updated. See the note in the [grafana documentation](https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/#repository-migration-november-8th-2022).
After this change is merged, and before deploying on your local VM,  the previous Grafana apt repository configuration must be manually removed from `/etc/apt/sources.list.d/`. The staging and production servers are already updated.
> [infra] fix: update the grafana rapository URL

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/components/footer/Footer.tsx
This PR changes `YouTube Playlist` for `Playlist YouTube` in the french translation. It sounds more natural to have the main noun first in a mot-valise.
We can also think about the `Twitter Bot`. Should we use `Bot Twitter` in french? In my personal opinion yes, to be coherent with the YouTube Playlist. The contraction `Bot` (from the French and English robot) being more common than `agent` or `robogiciel` I think `Bot Twitter` is an acceptable translation.
> [front] fix: use Playlist YouTube instead of YT Playlist in french

- backend/ml/mehestan/global_scores.py
- backend/ml/mehestan/individual.py
- backend/ml/mehestan/run.py
- backend/tournesol/management/commands/sync_yt_playlists.py
- backend/tournesol/tests/test_ml_run.py
- backend/tournesol/tests/test_sync_yt_playlists.py
* Alpha: 0.01 --> 1.0
* New poll scaling: (the sigmoid shape is unchanged)
**Before** : Tournesol score 50 is the top 1% of rated videos
**After** : Tournesol score 25 is the top 25% of videos rated by at least 4 contributors
`sum_overall_contrib_comparisons` is the total number comparisons made by all users who contributed to a given video
This PR should close #1065
> ml: update alpha and poll scaling to smoothen individual scores distribution

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
#1255
Maybe in english we could use: "considered trustworthy"...
> Improve "email considered trusted" wording

- frontend/.husky/pre-commit
The linter will run in the container if no local `yarn` is found, and the hook will just ignored otherwise.
> [front] fix: ignore pre-commit hook if yarn is absent and support running hook in dev-env 

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/home/videos/HomeVideos.tsx
- frontend/src/pages/home/videos/sections/FundingSection.tsx
**related to** https://github.com/tournesol-app/tournesol/issues/1168
**based on the PR** https://github.com/tournesol-app/tournesol/pull/1287
---
This PR adds a funding section on the home page.
This funding section has been designed to be straightforward: it doesn't explain what we do with the funds (could be the responsibility of the donate page), but it explain why people should give.
**Questions**
**(a)** I'm not sure if `commons` is an acceptable translation for the french `biens communs`. In this PR I use `commons` in it's economical definition, not philosophical, even if both seem to work.
**to-do**
fr
en
> [front] feat: add a funding section on the home page

- frontend/src/features/login/Login.tsx
- frontend/src/features/settings/account/PasswordForm.tsx
- frontend/src/pages/signup/Signup.tsx
I am not sure about how to test this properly. On my environment, it seems that browsers suggest auto-completion options automatically. The browsers may also behave differently on "localhost". 
@lfaucon Could you have a look with your browser?
> [front] feat: set 'autocomplete' attr on login and signup forms

- backend/tournesol/tests/test_text_search.py
- backend/tournesol/views/polls.py
This would cause an error on the frontend when setting all criteria weights to zero in the advanced filters
> [back] fix: server error on search where total criteria weights is zero

- backend/core/locale/fr/LC_MESSAGES/django.po
- backend/core/serializers/user_settings.py
- backend/core/tests/serializers/test_user_settings.py
- backend/core/tests/test_api_user_settings.py
- backend/core/urls/user_settings.py
- backend/core/views/user_settings.py
- backend/tournesol/urls.py
- frontend/scripts/openapi.yaml
**related to** #1293
**based on the PR** #1296
---
This PR adds the user settings API.
Users can get, update or partially update their own settings. For now only the `rate_later__auto_remove` setting for the poll `videos` has been added (not yet used by the comparisons API).
**to-do**
- `GET`
- `PATCH`
- `PUT`
- serializers
- connect the `rate_later__auto_remove` to the comparison API and test it
- return the settings after a user authentication
- ensure they are saved in the front end's redux store
- create the update form in the front end
> [back] feat: add the user settings API

- backend/tournesol/views/exports.py
Related to https://github.com/tournesol-app/tournesol/issues/1143
Changes:
- cast scores to int in comparison
- remove unused weight column
> fix: remove weight column from comparisons and cast scores to int

- backend/tournesol/models/entity.py
- backend/tournesol/models/rate_later.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_api_rate_later.py
- backend/tournesol/views/comparison.py
**related to** #1294 
---
This PR makes the comparisons API use the `rate_later__auto_remove` setting.
If the setting is not defined in the requested poll, the default value defined in the `RateLater` model is used, currently `4`. If the setting is defined, its value is used instead.
The new tests of the comparisons API ensure the API call `auto_remove_from_rate_later` with the user setting or the default value in case of need.
The new tests of the rate-later API ensure the `Entity.auto_remove_from_rate_later` behaves as expected (note: in the future these tests could be moved in the entity unit tests, as they test a behaviour of the `Entity` model, not a behaviour of the rate-later API).
**to-do**
**next steps**
- check if the settings are returned after an authentication
- ensure they …
> [back] feat: the rate-later auto remove is now connected to the user settings

- backend/requirements.txt
Fix:
- CVE-2023-23969
See: https://docs.djangoproject.com/en/4.0/releases/4.0.9/
> [back] sec: upgrade Django to 4.0.9 (from 4.0.8)

- backend/ml/outputs.py
- backend/tournesol/views/comparison.py
A deadlock was recently observed at the end of the "ml_train" job. It's similar to the issue addressed in #1227 
And I think I have now realized what exactly is the root cause for this situation. When creating a comparison at the moment when tournesol scores are being updated, there may exist 2 concurrent transactions which try to update the same Entity objects in a different order:
```
TRANSACTION 1 (ml)                   TRANSACTION 2 (api)
save_tournesol_scores()                 perform_create()
----------------                    ---------------
+-------------------------------+                  |
|    Update tournesol_score     |                  |
|         Entity 1000           |                  |
|   (Locked by Transaction 1)   |                  |
| …
```
> [back] Fix deadlock between comparison and ml

- browser-extension/src/addModal.js
- browser-extension/src/manifest.json
I think it was a typo made when the the code was initially introduced in 4185735c06269a5ae6f3aafef022f91a604d75f7.
> Fix extension's iframe event listener not removed

- backend/ml/mehestan/global_scores.py
- backend/ml/mehestan/primitives.py
- backend/ml/tests/test_mehestan_primitives.py
Feel free to propose changes, especially if you have a better idea Adrien for preventing divisions by zero in `L_prime`.
I didn't add tests for QrUnc, because the current formula doesn't really have the properties I would expect.
> Use LogSumExp, fix the biases, add tests (#1232)

- backend/requirements.txt
Fix:
- CVE-2023-24580
See: https://docs.djangoproject.com/en/4.0/releases/4.0.10/
> [back] sec: upgrade Django to 4.0.10 (from 4.0.9)

- browser-extension/src/addTournesolRecommendations.css
- browser-extension/src/addTournesolRecommendations.js
- browser-extension/src/manifest.json
Hi,
This is a new PR for issue #1315.
1. I have changed the view count logic from using regex and unnecessary string conversion to directly using the in-built `Intl` object. This is what the `millifyViews` function does.
2. The `viewPublishedDate` function takes the publish date from the metadata and converts it into a human-friendly format. According to my observation, Youtube's UI displays `days` until 13 days, then shifts to weeks, months, and years. I have upgraded the logic to match the same. I have also added comments in the code where necessary.
Let me know if it looks good to you, and/or if there are any changes to be made.
**P.S. While developing and debugging, I found out that my `console logs` in the `addTournesolRecommendations.js` were being called twice.** It might just be …
> [ext] feat: display videos' views and publication date

- backend/core/tests/management/test_delete_inactive_users.py
- backend/core/utils/tests/test_time.py
- backend/core/utils/time.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_api_inconsistencies.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/tests/test_api_statistics.py
- I created a `time_ahead` function which is the opposite of the existing `time_ago` function.
- I used those two function when it was possible
> [back] refactor: Add `time_ahead` function and harmonize

- backend/core/management/commands/watch_account_creation.py
- backend/core/tests/management/test_watch_account_creation.py
- backend/core/utils/email_domain.py
- backend/core/utils/tests/test_email_domain.py
To solve #823
Things to do:
The next point will be adressed in a next PR:
- Add timers to run it every 1 hour and every day
- Create a private Discord channel for these alert
- Add the webhook to the secrets
> [back] feat: add a command able to monitor trusted accounts created

- backend/core/models/user.py
- backend/ml/inputs.py
- backend/ml/mehestan/global_scores.py
- backend/ml/mehestan/run.py
- backend/tournesol/suggestions/suggestionprovider.py
- backend/tournesol/tests/test_exports.py
- backend/tournesol/tests/test_ml_run.py
Fixes #1351 
Note: a few references to "supertrusted" users are still present in the suggestion provider, which uses a subset of comparisons from the staff team to initialize its algorithm. (Not related to Mehestan)
> [back] ml: rename 'supertrusted' into 'scaling-calibration' users, sync definition with latest paper

- frontend/src/components/TitledPaper.tsx
- frontend/src/components/index.ts
- frontend/src/features/frame/components/footer/Footer.tsx
- frontend/src/pages/about/Donate.tsx
… into direct transfer section of donate page
TitledPaper now has a titledId props.
Footer direct transfer link now point to the direct_transfer anchor.
DonatePage component now scroll to the pointed anchor once.
> [front] feat: `<TitledPaper>` can now be scrolled into

- backend/tournesol/management/commands/create_dataset.py
- backend/tournesol/resources/export_odc_by_1.0_public_text.txt
- backend/tournesol/resources/export_readme.txt
- backend/tournesol/tests/test_exports.py
This PR adds the dataset license in the dataset archive.
I updated the README.txt to include a human-readable summary to make it clear that can be done with our dataset.
> [back] feat: add a `LICENSE.txt` file in the dataset archive

- backend/tournesol/lib/public_dataset.py
- backend/tournesol/tests/test_exports.py
- backend/tournesol/tests/test_utils_contributors.py
As previously discussed, this PR rounds the computed individual and collective scores in the dataset.
I chose a two digits precision after the decimal point.
> [back] refactor: round floating point numbers of the dataset

- browser-extension/src/browserAction/menu.js
- browser-extension/src/manifest.json
Browser-extension patch: Correct the bug reported on discord informing that the videos loaded by the rate now button of the browser extension are sometimes replaced by another random video on the tournesol.app comparison page.
> [browser-extension] Video link edited to correct a bug reported on discord

- frontend/src/features/comparisons/Comparison.tsx
- tests/cypress/integration/frontend/comparisonPage.ts
When redirecting from legacy params videoA and videoB, the state `selectorA` and `selectorB` was already initialized with empty uids. That breaks assumptions made by the video selectors when using the autofill feature.
> [front] fix redirection from legacy params on comparison page with autofill

- browser-extension/src/addRateButtons.css
- browser-extension/src/manifest.json
This PR tries to be a temporary fix to #1319. 
There are too many factors that decide the width at which we should remove the text from the `Rate Later` and `Rate Now` Buttons. They are:
1. If you are subscribed or not. If you are, their button takes more size and has dropdown for Notification settings (All, Personalized, None)
2. If they have a Membership feature set up, this adds another `Join` button to the UI
3. If their channel name is too long.
We can add UI customization based on the three factors mentioned above or just go with the pixel numbers decided in this commit that may work well for the general use case. We can at least keep `1017px` value since it is a break point of Youtube UI change as well.
**Please Note:** I found out that during inspect in browser and toggling to …
> [extension] fix: removes the text of rate buttons on some screen sizes

- frontend/src/hooks/useListFilter.ts
- tests/cypress/integration/frontend/recommendationsPage.ts
This should also avoid counting duplicated pageviews when accessing the recommendation pages.
A new history entry (and pageview) is still created when one of the filter changes.
> [front] fix: expanding filters should not push entries in history

- browser-extension/src/addRateButtons.js
- browser-extension/src/browserAction/menu.js
- browser-extension/src/html/tournesol-iframe.html
- browser-extension/src/manifest.json
- frontend/src/utils/analytics.ts
The browser extension uses an invisible iframe "/login" to fetch or refresh the access token used for authentication.
This PR adds a parameter "?dnt=1" in the URL of this iframe, to disable tracking of this invisible page.
["UTM tags" ](https://plausible.io/docs/manual-link-tagging )are also used on the comparison iframe and links used in the extension menu.
> [front][ext] fix: disable Plausible in login iframe, add url tags in pageviews from extension

- browser-extension/src/addTournesolRecommendations.js
- browser-extension/src/addVideoStatistics.js
- browser-extension/src/browserAction/menu.js
- browser-extension/src/manifest.json
This PR continues #1400 
If I'm not mistaken all links to the website should now include `utm_source=extension`.
> [ext] chore: add missing `utm_source` query parameter

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/entity/AvailableEntity.tsx
- frontend/src/components/entity/EntityCard.tsx
- frontend/src/features/entities/EntityList.tsx
- frontend/src/pages/rateLater/RateLater.tsx
**related to** #1070
---
This PR has for goal to find and apply a better way to display a video in `<EntityList>` when it is not available anymore. For the moment I focused on the display of unavailable videos on the list of recommendations, video ratings and rate later pages.
On the recommendation and video ratings page a  "video unavailable" message is displayed with the possibility to see the unavailable entity by toggling a button. The rate later page display a delete button in addition of the message so we can still delete the video from the rate later list.
In the rate-later list, actions are displayed.
On other lists, no action is displayed.
> [front] feat: hide unavailable videos in list

- infra/ansible/inventory.yml
The staging server will check the production server, and the production server will check the staging server.
The VM checks the staging server.
> [infra] chore: monitor the web analytics server URL

- data-visualization/pages/03_Community_evolution.py
Combine the community evolution graph to display only two of them with the possibility to switch between cumulative and non-cumulative value with a tab.
> [dataviz] rework community evolution graph

- frontend/src/utils/video.ts
This PR tries to solve issue #1263 where the obsolete `/video/` API call is replaced by `/polls/{name = videos}/recommendations` API when the `Auto` button is clicked on the _comparison_ page.
While I believe this PR is opened way before a merge, I wanted to open the discussion with some code that we could inspect.
> Refactoring /video/ to /polls/videos/recommendations on clicking auto button

- dev-env/run-docker-compose.sh
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/Pagination.tsx
- frontend/src/pages/comparisons/ComparisonList.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/pages/videos/VideoRatings.tsx
- tests/cypress/e2e/frontend/myRatedVideosPage.cy.ts
- tests/cypress/e2e/frontend/recommendationsPage.cy.ts
Refactoring of the Pagination component to present the list of pages.
Allow quick navigation to 3 pages before or 3 pages after.
Ability to go to -100 -10 +10 +100 pages
Added a field to enter the page number.
Pagination on large screens: 
Pagination on small screens: 
Requested change in issue #1001
> [front] multi-page lists navigation (#1001)

- frontend/src/components/Pagination.spec.tsx
Add test on newly version of pagination component
checked:
- The default navigation
- The calculation of the total number of pages
- The offset of elements when choosing a page 
- The click on the different buttons -1 / -10 / -100 / +1 / +10 / +10
- That the -100 / +100 buttons are not displayed by default
- That the buttons are well deactivated according to the selected page
> [front] add test of pagination component

- backend/README.md
Clicking on the `Manual installation` item of the table of content now redirects to the correct section.
You can test here:
https://github.com/tournesol-app/tournesol/blob/2168f5ad1b347dc2e5b09882f136c9ece72c34a6/backend/README.md
> [back] docs: fix broken table of content is the `README.md`

- backend/tournesol/lib/public_dataset.py
Before:
```json
{"data_included_until": "2023-03-20", "generated_by": "https://api.tournesol.app/", "tournesol_version": "d4e7d28eed20395c5cc65ee2cb9afd031160034d", "license": "ODC-By-1.0", "algorithms_parameters": {"byztrust": {"SINK_VOUCH": 5, "TRUSTED_EMAIL_PRETRUST": 0.8, "VOUCH_DECAY": 0.8}, "mehestan": {"ALPHA": 1.0, "R_MAX": 10.0, "W": 20.0, "SCALING_WEIGHT_CALIBRATION": 20.0, "VOTE_WEIGHT_PUBLIC_RATINGS": 1.0, "VOTE_WEIGHT_PRIVATE_RATINGS": 0.5, "OVER_TRUST_BIAS": 2, "OVER_TRUST_SCALE": 0.1, "MAX_SCALED_SCORE": 100.0, "POLL_SCALING_MIN_CONTRIBUTORS": 4, "POLL_SCALING_QUANTILE": 0.75, "POLL_SCALING_SCORE_AT_QUANTILE": 25.0}}}
```
After:
```json
{
"data_included_until": "2023-03-20",
"generated_by": "https://api.tournesol.app/",
"tournesol_version": …
```
> [back] refactor: indent the `metadata.json` file of the dataset

- backend/tournesol/tests/test_api_preview.py
- backend/tournesol/urls.py
The comparison preview was not display for url like:
<https://tournesol.app/comparison?uidA=yt%3AWHUJL-EjsGY&uidB=yt%3ADjwxOH3N-gc>
This is a quick fix, but a more general one should be done with #1051 
Questions:
- Is it OK to use the same name for the path?
- Should we copy/paste all the `DynamicWebsitePreviewComparisonTestCase` to test without the trailling slash?
> [back] fix: comparison preview url without trailing slash

- backend/tournesol/admin.py
**follows the work of** https://github.com/tournesol-app/tournesol/pull/1149
---
This PR allows the administrators to see the new model `EntityPollRating` in the admin interface.
All fields of the model are read-only to prevent updating those computed fields by mistake (the field Tournesol score of the Entity model was already read-only).
> [back] feat: add `EntityPollRating` to the admin interface

- backend/tournesol/serializers/metadata.py
- backend/tournesol/tests/test_api_preview.py
- backend/tournesol/views/preview.py
Server error were observed when fetching the preview related to a video entity with `"duration": null` in its metadata. (For example this is the case for live streams).
After this fix, the duration overlay will not be drawn on the preview image for such videos.
> [back] fix: server error on video preview when duration is null

- backend/core/management/commands/delete_inactive_users.py
- backend/core/tests/management/test_delete_inactive_users.py
- backend/ml/inputs.py
- backend/tournesol/lib/public_dataset.py
- backend/tournesol/tests/test_api_contributor_recommendations.py
- backend/tournesol/tests/test_api_user.py
- backend/tournesol/views/contributor_recommendations.py
- backend/tournesol/views/stats.py
- backend/tournesol/views/user.py
- backend/vouch/serializers.py
- backend/vouch/tests/test_api_voucher.py
- backend/vouch/trust_algo.py
- backend/vouch/views.py
Fixes #1393
When a user asks for account deletion, the "user" is marked as inactive in the database (with the date stored in "last_login") instead of being deleted immediately.
The command "delete_inactive_users" is modified to cover this case, so that the account is deleted after 7 days.
A placeholder email address is associated to the inactive user, to allow immediate reuse of the original address.
The implementations of ml input, voucher views, and public dataset are updated to ignore such inactive users.
> [back] fix: delay user deletion to avoid conflicts with score computations

- data-visualization/requirements.txt
With numpy==1.22.4, the command "streamlit run Tournesol_Data_Visualization.py" produce an the error "ImportError: numpy.core.multiarray failed to import" in User comparisons's page.
Installing numpy==1.24.2 in virtual env corrected the problem.
Cf. https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import?page=1&tab=scoredesc#tab-top
I am new to contributing on an open source project. I hope I'm not missing something @tournesol-app/maintainers .
> [dataviz] Correcting dependency for data-visualization

- backend/core/serializers/user_settings.py
- backend/core/tests/test_api_user_settings.py
I observed this bug when reviewing #1501 
The default value for settings is `{}`, so PATCH should be able to initialize the scope if it's not present yet.
> [back] fix: initialize settings scope if it's not defined yet when patching user settings

- frontend/src/features/settings/userSettingsSlice.ts
- frontend/src/hooks/useLoginState.ts
Close #1510
The goal is to prevent the user to leave tracks of its preferences in the browser after having finished to use Tournesol.
> [front] chore: clear user's settings in the store after a logout

- browser-extension/src/addRateButtons.js
- browser-extension/src/manifest.json
**related to** #1517
---
This PR has for goal the fix of the buttons rate later and rate now on a video page that sometimes don't appear
As for previous behavior if the button rate-later already exists, the script stops and no buttons are added to prevent duplicating them
This behavior works well when the page is reloaded but when you navigate to the page the script sometimes detects the rate-later and rate-now buttons before YouTube delete them so the script does not display new buttons to replace the one removed by YouTube.
The new behavior remove the rate later and rate now buttons if they exist then display them again.
It may not be necessary to delete them when you navigate to a page since youtube remove them from the page but it is necessary when you reload the page.
> [ext] fix: rate buttons sometimes not displayed on YT video page

- backend/tournesol/views/comparison.py
Reduces the number of SQL queries called on `/users/me/comparisons` endpoint.
> [back] optim: use `select_related` and `prefetch_related` in comparisons view

- infra/ansible/inventory.yml
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/django/templates/tournesol-api-watch-account-number-yesterday.service.j2
- infra/ansible/roles/django/templates/tournesol-api-watch-account-number-yesterday.timer.j2
close https://github.com/tournesol-app/tournesol/issues/1454
---
This PR adds a scheduled task running the Django mgmt command `watch_account_number` every day, one minute after midnight.
The command will count the total number of accounts created yesterday, and will send alerts on Discord when appropriate.
> [infra] sec: run manage.py watch_account_number with a scheduled task

- browser-extension/src/addModal.js
- browser-extension/src/manifest.json
- frontend/src/App.tsx
**related to** #1527 
---
This temporary fix should reduce the number of useless call to /stats/ generated by the browser extension hidden iframe, and appease our monitoring system.
As discussed with Adrien, we agreed to replace this temporary fix by a more robust system that will lazily fetch the statistics from the back end when the front end needs to display them (see #1527)
> [ext][front] fix: do not call the API /stats/ when it's not needed

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/Pagination.spec.tsx
- frontend/src/components/Pagination.tsx
- frontend/src/pages/recommendations/RecommendationPage.tsx
The goal is to show the counter of the videos currently displayed on the recommendations page
(e.g. Showing 61 - 80 of 615)
> [front] feat : display limit, offset and count in the pagination 

- backend/tournesol/utils/constants.py
- infra/ansible/roles/django/tasks/main.yml
On 2023-05-01, between 08:10 and 08:12 UTC, many server errors were observed on the backend, due to too many concurrent connections to the database:
```
May 01 08:10:31 tournesol gunicorn[3862359]: psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```
The causes are unclear, but it seems to be related to many "/preview" requests being interrupted by clients after a 5-sec timeout starting from 08:09:37 UTC. Maybe these requests created connections to the db that were not properly closed after the client gave up. 
Anyway, this led me to realize that our deployment does not specify the version of uvicorn + gunicorn used to run the django application. There could be …
> [infra] Upgrade and pin Uvicorn version, attempt to fix timeout issues on previews

- backend/requirements.txt
Fix:
- CVE-2023-31047
See:
- https://docs.djangoproject.com/en/4.2/releases/4.1.9/
- https://docs.djangoproject.com/en/4.2/releases/4.1.8/
> [back] sec: upgrade Django to 4.1.9 (from 4.1.7)

- frontend/src/App.tsx
- frontend/src/features/settings/preferences/VideosPollUserSettingsForm.tsx
**to-do**
**to-do in the following PRs**
- if the user is redirected to `/settings/preferences` after a log in, the displayed settings should be the user's preference and not the default values of the settings
> [front] fix: user settings not retrieved after a login

- frontend/src/features/settings/preferences/VideosPollUserSettingsForm.spec.tsx
- frontend/src/features/settings/preferences/VideosPollUserSettingsForm.tsx
> [front] fix: retrieve user's settings from API when login on preferences page

- backend/tournesol/tests/test_api_preview.py
- backend/tournesol/views/preview_recommendations.py
Did you know that `"".split(",")` returns `[""]` ?  
Whereas `"".split()` without a separator returns `[]`
> [back] fix: recommendations preview is empty when all languages are explicitly requested

- backend/ml/mehestan/global_scores.py
- backend/ml/mehestan/primitives.py
- backend/ml/mehestan/run.py
- backend/ml/tests/test_mehestan_primitives.py
Related to the latest updates in https://www.overleaf.com/project/5f44dd8e84c8540001bf1552
> [ml] Update QrUnc definition, and use QrDev to compute uncertainty on global scores

- frontend/src/features/goals/collective.tsx
As discussed with the rest of the team, we increase the weekly collective comparisons goal to 2500.
We reached several times in a row the goal 2000, and we think we can now aim for 2500 : ) I also reduced the amount of work required to reach the "secret" emoji, to better match the new goal.
> [front] refactor: increase collective goal to 2500 from 2000

- infra/ansible/roles/mediawiki/tasks/main.yml
Once the wiki is disabled and no issue is observed, the infra configuration will be removed
Related to #557
> infra: disable Tournesol wiki

- frontend/src/features/comparisons/ComparisonList.tsx
- frontend/src/pages/home/videos/sections/HomeComparison.tsx
- frontend/src/utils/action.tsx
- tests/cypress/e2e/frontend/comparisonPage.cy.ts
This should fix the duplicates "comparison" and "comparison/" entries in our web analytics tool.
> [front] fix: remove extra trailing slash in comparison URL

- browser-extension/src/addRateButtons.css
- browser-extension/src/addRateButtons.js
- browser-extension/src/manifest.json
fix #1587
---
The buttons are now displayed in a flex container to avoid breaking the YouTube layout and hiding the YouTube buttons.
> [ext] fix: the video actions are now displayed in their own container

- frontend/src/pages/rateLater/RateLater.tsx
I found that some padding on the rate later page would make it look better on mobile.
Without padding (current state):
With some padding (this PR):
> [front] style: add missing content padding in the Rate Later page

- backend/tournesol/views/preview_recommendations.py
Previews for links such as https://tournesol.app/recommendations?language=fr&uploader=Tout+Simplement+%E2%80%93+Kurzgesagt&unsafe=true&duration_lte=7&duration_gte=1 do not filter correctly the expected videos
> [back] fix: handle uploader and duration filters for the recommendation page preview

- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
Solves #1519 by declaring a variable `isMounted` in the useEffect of `<ComparisonSeries>`. This variable checks if the component is mounted whenever we call any setState within the useEffect.
Working behavior can be seen below:
https://github.com/tournesol-app/tournesol/assets/20269286/6531876c-8c0f-4bfb-94d0-dd5202588575
I request you to test it as well and let me know if there are any changes to be made.
> solves unmounting and memory leak issues of ComparisonSeries

- backend/ml/management/commands/ml_train.py
- backend/tournesol/management/commands/load_public_dataset.py
- backend/tournesol/tests/test_load_public_dataset.py
- dev-env/docker-compose.yml
- tests/cypress/e2e/frontend/comparisonPage.cy.ts
* The management command `load_public_dataset` read the "new" dataset format instead of comparison.csv only
* The dev-env database contains non-null `trust_score` values, imported from the public dataset.
As the vouchers are not included in the dataset and to preserve realistic values, the "trust algo" is not executed when importing the dataset.
* All users with a trust_score > 0.5 are created with a fictional trusted email address. This previous implementation used a random status with 10% probabilty to be trusted.
* The new database built in image [`ghcr.io/tournesol-app/postgres-dev-env:2023-06-01` ](https://github.com/tournesol-app/tournesol/pkgs/container/postgres-dev-env/98006768?tag=2023-06-01) has been initialized with `./run-docker-compose.sh download --user-sampling 0.06`
> [dev-env][back] refresh dev-env dataset, update `load_public_dataset` to read trust scores

- backend/tournesol/entities/base.py
- backend/tournesol/tests/test_api_polls.py
- backend/tournesol/tests/test_api_preview.py
- backend/tournesol/views/preview_recommendations.py
2 distinct views where the server error could occur, when trying to parsing empty string as int:
* on recommendation preview, when transforming the query into API parameters
* on recommendations route, when applying the "filter_func" (i.e the `:int` transformation)
> [back] fix: server errors on recommendation and preview when duration filter is empty

- .github/workflows/browser-extension-ci.yml
- .github/workflows/frontend-ci.yml
- dev-env/docker-compose.yml
- frontend/README.md
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/LanguageSelector.tsx
- frontend/src/features/frame/components/footer/FooterSection.tsx
- frontend/src/features/recommendation/subset/RecommendationsSubset.tsx
- frontend/src/hooks/useCurrentPoll.tsx
- frontend/yarn.lock
- infra/ansible/inventory.yml
Node.js 14 (Fermium) reached end-of-life on 2023-04-30.   
Node.js 18 (Hydrogen) is the current LTS, supported until **2025-04-30**.  
See https://nodejs.dev/en/about/releases/
Node.js is used to test and build the frontend application.  No visible changes are expected for end-users.
:rocket:  You can simply recreate the containers with `./run-docker-compose.sh restart` 
1. Install and activate Node.js 18 (e.g with fnm or nvm: `fnm use 18`)
2. Delete the node modules `rm -rf frontend/node_modules`
3. :rocket: Run `yarn install` and `yarn start` 
* `@babel/plugin-proposal-private-property-in-object` is added in devDepencies to solve a warning related to react-scripts. See https://github.com/facebook/create-react-app/issues/11793  
"create-react-app" and "react-scripts" seem to be no longer …
> [infra][frontend] chore: Upgrade Node.js version from 14 to 18

- CONTRIBUTING.md
- README.md
We now expect feature requests only on Discord.
The README should not contain links to our deleted wiki.
> [meta] docs: update CONTRIBUTING and README

- solidago/pyproject.toml
- solidago/src/solidago/__version__.py
The `license` field defined in "pyproject.toml" in #1638  is not enough :shrug:
> [solidago] fix missing license classifier in package

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/SettingsSection.tsx
- frontend/src/features/settings/preferences/TournesolUserSettingsForm.tsx
- frontend/src/pages/settings/account/Account.tsx
- frontend/src/pages/settings/layout.ts
- frontend/src/pages/settings/profile/Profile.tsx
The `<SettingsSection>` component is a Grid item but not all Grid using it have the same spacing, making all settings pages slightly different. Moreover this component was using a custom padding bottom in addition to the spacing used by its parent, making it difficult to precisely control the whole Grid layout without updating the container and its items at the same time.
This PR introduces a new layout variable `mainSectionGridSpacing` that can be used in all settings page to keep their layout coherent, and removes the hardcoded  padding bottom of `<SettingsSection>` to ease the Grid customization.
> [front] style: harmonize and simplify the layout of the settings pages

- backend/core/serializers/user.py
- backend/core/serializers/user_settings.py
- backend/core/tests/test_api_accounts.py
**related to** #1654
---
It looks like the user settings were already handled by `/accounts/register/` but not properly documented in the API schema.
I used the `TournesolUserSettingsSerializer` so that all settings can be defined during the registration. In case of need, we can always limit the settings to the general settings (the notifications) or even to specific fields.
(I also re-ordered the serializers in the `user_settings.py` module, so that the most generic appear first.)
> [back] feat: /accounts/register/ can now officially save user settings

- backend/core/serializers/user.py
- backend/core/tests/test_api_accounts.py
- backend/settings/settings.py
Fixes 2 minor oversights with the serializers used by `/accounts/register` and `/accounts/profile`:
1. `settings` was readable and writable on `/accounts/profile`: as dedicated routes exist to update (and validate) the settings, I think it makes sense to remove this possibility.   
This does not affect `/accounts/register` where the `settings` field has been explicitly defined in #1656
2. `trust_score` was readable and writable on both routes. It's now read-only (e.g used by the Voucher page). 
It was not deliberate to have it writable here. This is not exploitable though, as the value is recomputed on each run before entity scores are updated.
> [back] Restrict writable fields in /accounts routes

- frontend/scripts/openapi.yaml
I ran `yarn update-schema` to update our `openapi.yaml`.
To avoid conflicts as much as possible I removed the changes that are going to be merged by the PR adding settings at sign up (https://github.com/tournesol-app/tournesol/pull/1657).
I also removed the changes related to the recently added banners API as they are already present in a feature branch (https://github.com/tournesol-app/tournesol/tree/front-add_banners).
> [front] chore: update the OpenAPI schema

- backend/requirements.txt
Fix:
- CVE-2023-36053
See:
- https://docs.djangoproject.com/en/4.1/releases/4.1.10/
> [back] sec: upgrade Django to 4.1.10 (from 4.1.9)

- browser-extension/src/manifest.json
- browser-extension/src/models/tournesolContainer/TournesolContainer.js
- frontend/src/features/frame/components/topbar/Search.tsx
This will fix the duplicate entries we have in Plausible.
In the following capture, we can see both `recommendation` and `recommendations/`
> [front] fix: remove the extra trailing slash in `recommendations`

- tests/cypress/e2e/frontend/signup.cy.ts
This PR tries to fix the e2e test related to the sign up that was failing very often.
The `cy.getEmailLink()` should now be called after the activation link is sent, and the user should be able to log in properly after a sign up and a verification.
> WIP / [tests] fix: attempt to fix the failing Signup test

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/polls/PollLargeButton.tsx
- frontend/src/features/tips/Tip.tsx
- frontend/src/features/tips/Tips.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/pages/comparisons/ComparisonList.tsx
- frontend/src/pages/home/presidentielle2022/HomePresidentielle2022.tsx
- frontend/src/pages/home/videos/HomeVideos.tsx
- frontend/src/pages/home/videos/sections/HomeComparison.tsx
- frontend/src/pages/personal/feedback/FeedbackPagePresidentielle2022.tsx
- frontend/src/pages/signup/Verify.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/extension.ts
- frontend/src/utils/polls/videos.ts
- frontend/src/utils/polls/videos.tsx
- frontend/src/utils/types.ts
- frontend/src/utils/ui.ts
- tests/cypress/e2e/frontend/comparisonPage.cy.ts
- tests/cypress/e2e/frontend/comparisonPageTuto.cy.ts
- tests/cypress/e2e/frontend/home.cy.ts
- tests/cypress/e2e/frontend/settingsPreferencesPage.cy.ts
**related to #1682**
---
The PR reworks the tutorial flow. It should be a lot more user friendly.
Main features:
- The users are not interrupted by dialogue boxes after each comparison anymore (configurable)
- Thanks to this, the number of required clicks to go through the tutorial has been divided by ~ 2
- The new `Tips` replace the dialogue boxes, and are always displayed on top of the comparison UI
- The users can browser the tips they have already seen, to "replay" the tutorial
- The messages have been reworked to be more motivating and actionable 
- There is now an invitation and a button allowing to install the browser extension during the tutorial
- The `Tips` component can be used outside of the tutorial for other needs
In order to display the tutorial the comparison page doesn't …
> [front] refactor: rework tutorial

- backend/core/serializers/user_settings.py
- frontend/scripts/openapi.yaml
Will allow the user to chose between the current behavior (Tournesol chose a video for you) or this one designed with miro.
> [back] feat: add the comparison__fill_entity_selector to the generic settings

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/home/videos/sections/research/ScientificLiteratureBox.tsx
Add the tabs "They cite us" and "In the media" with the content sent on Discord.
*Note : The "student works" tab opened the links over the tournesol website tab unlike in the "papers" tab, I took the liberty of changing it, we can delete this fix if that was intentional.*
> [front] feat: add new tabs to the Scientific Literature Box

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/entity_selector/EntitySelectButton.tsx
- frontend/src/features/entity_selector/EntityTabsBox.tsx
- frontend/src/pages/comparisons/Comparison.tsx
**related to #1696**
---
We have multiple ways of handling the display of the description.
Different approaches :
- (1) Always displayed by default, if the user close it, it's stored locally
- (2) Never displayed, there is an icon if we want to show it manually
- (3) Displayed and cant close if NbComp < 2*TutoLength, then it has (2) behavior
(1) Everyone will see it at least once but we need to implement storage
(2) Users might not pay attention and never read the descriptions
(3) New users will see it since they are the ones who should need it the most but we don't give them the choice
> [front] feat: display a description of the video selector tabs

- backend/tournesol/views/previews/recommendations.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/scripts/openapi.yaml
- frontend/src/components/ChoicesFilterSection.tsx
- frontend/src/features/recommendation/AdvancedFilter.tsx
- frontend/src/features/recommendation/SearchFilter.spec.tsx
- frontend/src/features/recommendation/SearchFilter.tsx
- frontend/src/utils/api/recommendations.tsx
- frontend/src/utils/userSettings.ts
- tests/cypress/e2e/frontend/recommendationsPage.cy.ts
- tests/cypress/e2e/frontend/settingsPreferencesPage.cy.ts
Changes:
* chore: update api yaml schema
* Add filtering option for already compared videos available for logged-in users
* Change frontend URLs to use a parameter `advanced` that support the safe option and the exclude option instead of `unsafe`
* Adapt the preview link redirect to support the `advanced=unsafe` option
> feat: Add filtering option for already compared videos

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/entity/EmptyEntityCard.tsx
- frontend/src/features/entity_selector/AutoEntityButton.tsx
- frontend/src/features/entity_selector/EntitySelectButton.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/pages/home/videos/sections/HomeComparison.tsx
- frontend/src/utils/constants.tsx
- frontend/src/utils/types.ts
- tests/cypress/e2e/frontend/comparisonPage.cy.ts
- tests/cypress/e2e/frontend/settingsPreferencesPage.cy.ts
**following #1699 and #1700**
---
The buttons have the same behavior as the current ones.
No video (entity) is loaded if the setting is set to false, default value is true.
> [front] feat: implement the fill entity selector feature

- backend/tournesol/tests/factories/entity.py
- backend/twitterbot/tests/test_tournesolbot.py
- backend/twitterbot/tournesolbot.py
Depends on #1689 (which introduces `.filter_safe_for_poll()` )
> [back] fix: ensure that twitterbot excludes unsafe entities

- frontend/src/utils/video.spec.ts
- frontend/src/utils/video.ts
- tests/cypress/e2e/frontend/comparisonPage.cy.ts
**related to** #1717 
---
The function responsible of extracting the video id from YouTube URLs is now able to extract id from these additional patterns:
- https://youtube.com/live/{video_id}
- https://youtube.com/live/{video_id}?feature=share
- https://www.youtube.com/live/{video_id}
- https://www.youtube.com/live/{video_id}?feature=share
- https://m.youtube.com/watch?v={video_id}
We might want in the future to support more exotic patterns, like a mobile URL used in a desktop environment:
- https://www.youtube.com/watch?app=desktop&v={video_id}
> [front] feat: add support of YouTube mobile and /live/ URLs

- backend/requirements.txt
- frontend/scripts/openapi.yaml
This PR upgrades several Python packages used by the back end.
In the near future we may want upgrade `django-oauth-toolkit` to the latest major release 2.x to benefit from the security improvements. This might involve updating the set-up of the dev-env.
> [back] chore: upgrade several dependencies

- frontend/src/features/settings/preferences/TournesolUserSettingsForm.tsx
> [front] fix: impossible to save preferences when no reco. langs have been selected

- infra/ansible/roles/django/templates/tournesol.j2
**related to** #1439
---
(a)
I read that Mozilla recommend to set max-age to [one year](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#examples), and by doing so our website become eligible for [HTST preload](https://hstspreload.org/?domain=tournesol.app).  Curiously even with our current value of 300 seconds, it looks like we are already considered preloaded by hstspreload, but to confirm this we need to be sure we are part of the Chrome preload list (for instance, we are not part of the [Firefox preload list](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/manager/ssl/nsSTSPreloadList.inc)).
There [several warnings](https://hstspreload.org/?domain=tournesol.app#opt-in) about being preloaded, so it may be a good move to first set max-age …
> sec(infra) set HSTS max-age to 180 days (instead of 300 seconds)

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/signup/Signup.tsx
- tests/cypress/e2e/frontend/signup.cy.ts
**related to** #1739 
---
This PR adds a welcome banner in the sign up form to make it more attractive.
In addition, a `helperText` has been added to the email field, to inform the users that an activation email will be sent to finalize the sign up process. For now there is no indication about the trusted / untrusted domains. I'm still trying to find the correct wording.
Finally, a security net has been added in the `SignupSuccess` component, to invite the users to check the spelling of their email address, and to create a new account in case of need (see the preview below).
> style(front): add a welcome banner in the signup form

- frontend/src/features/comparisons/Comparison.tsx
There was a console.error in the front end's code that was adding necessary noise in the browser's console.
When opening a new comparison, the console was displaying an API error. In our case, there is nothing wrong, it is expected that new comparisons don't exist in the API. Displaying an error here can be understood as "something went wrong", but it's not the case.
> refactor(front): remove an extra console.error

- backend/tournesol/serializers/comparison.py
- backend/tournesol/serializers/entity.py
- backend/tournesol/serializers/poll.py
- backend/tournesol/serializers/rate_later.py
- backend/tournesol/serializers/rating.py
- backend/tournesol/tests/test_api_ratings.py
- backend/tournesol/views/comparison.py
- backend/tournesol/views/rate_later.py
- backend/tournesol/views/ratings.py
- frontend/scripts/openapi.yaml
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/features/feedback/StackedCandidatesPaper.tsx
- frontend/src/features/videos/PublicStatusAction.tsx
- frontend/src/hooks/usePersonalCriteriaScores.tsx
Related to #606
---
This PR updates the response schema of routes `/users/me/contributor_ratings/...`.
Instead of flat fields `n_comparisons`, `criteria_scores`, the response now includes `individual_rating` and `collaborative_rating` object, similarly to the changes introduced in #1720
> [back] refactor: Adapt contributor_ratings API to the new response schema

- backend/tournesol/views/ratings.py
**related issues** #1746 
---
Usually the API `POST /users/me/contributor_ratings/{poll_name}/` correctly returns HTTP 400 when an already existing rating is validated.
There is an exception to this. According to the logs, we received concurrent requests (possibly bearing the same JSON payload), passing the validation, and causing the API to fail with an error 500. This PR makes the back end fail gracefully by returning a 400 Bad Request, instead of a 500 Interval Server Error.
Nevertheless, there might still be an issue in the front end causing two requests to be sent instead of one.
---
Here is the query I used in Grafana to investigate the problem, with different time ranges:
- time range from 2023-09-05 17:12:04 to 2023-09-05 17:12:05
- time range from 2023-09-05 10:25:23 to …
> [back] fix: HTTP 500 is now 400 when unique contrainst of rating is violated

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/features/criteria/CriteriaSelector.tsx
- frontend/src/features/entity_selector/EntityTabsBox.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
This is an attempt to improve the appearance of the website when a large minimal font-size is configured in the browser settings.
* Sidebar: use `min-height` instead of fixed size and wrap labels
* Align metadata of `RowEntityCard` (used in the contextual list on the analysis page and in the video selector) to the top of the card. THis is to avoid hiding the video title when the content overflow the card. Far from perfect, another redesign may be required.
* Wrap labels in `CriteriaSelector`
with min font-size: 24px
|Before|After|
|--|--|
|![Capture d’écran du 2023-09-07 14-33-23](https://github.com/tournesol-app/tournesol/assets/4726554/122be51e-15fa-4382-ad38-d45b06f274a9)|![Capture d’écran du 2023-09-07 14-41-14](https://github.com/tournesol-app/tournesol/assets/4726554/54095188-ebc7-4b …
> [front] adjust style of Sidebar and EntityCard with large fonts

- backend/vouch/tests/test_api_voucher.py
- backend/vouch/views.py
**related issues** #1753 
---
This PR fixes the tests of the `vouch` app that could fail because of non deterministic answers of the vouch API.
Calling several times `VoucherReceivedListAPIView` should not return different results. I ordered the queryset by issuer username so that they can easily be displayed in alphabetical order in the front end.
> [back] test: order the results of VoucherReceivedListAPIView

- browser-extension/src/addTournesolRecommendations.css
- browser-extension/src/displayHomeRecommendations.js
- browser-extension/src/displaySearchRecommendations.js
- browser-extension/src/manifest.json
- browser-extension/src/models/banner/Banner.js
- browser-extension/src/models/tournesolContainer/TournesolContainer.js
- browser-extension/src/models/tournesolVideoCard/TournesolVideoCard.js
**related to** https://github.com/tournesol-app/tournesol/issues/1548
---
This PR removes the usage of `innerHtml` from the browser extension.
In TournesolVideoCard, elements are created separately with `document.createElement`. 
In TournesolContainer, `<svg>` elements are replaced with `<img>`.
> [ext] fix: mozilla security warnings about `innerHtml` usage

- backend/requirements.txt
Fix:
- CVE-2023-41164
See:
- https://docs.djangoproject.com/en/4.1/releases/4.1.11/
> [back] sec: upgrade Django to 4.1.11 (from 4.1.10)

- backend/scripts/ci/lint-fix.sh
- backend/scripts/ci/lint.sh
- backend/tournesol/views/previews/recommendations.py
- frontend/src/features/recommendation/SearchFilter.tsx
- frontend/src/hooks/useListFilter.ts
Fixes #1763 
---
The bug is fixed twice :)  
The frontend will remove the `uploader=` param from the URL (not relevant for UX), and the backend preview will ignore empty values to be consistent with the frontend implementation.
> [front] fix: remove uploader param from URL after deleting filter

- frontend/src/utils/video.ts
**related issues** #1743
**this PR targets** https://github.com/tournesol-app/tournesol/pull/1758
---
This small PR is a suggestion that increases the range of suggested videos by the Auto button, to slightly increase their diversity. 
When using the Auto button, there is 5 % chance to suggest a video from the all time top 100 recommendations (all languages). Today it seems like there are good videos in the top 200 that could be safely suggested, like the following:
- https://tournesol.app/entities/yt:vKA4w2O61Xo
- https://tournesol.app/entities/yt:a_O8u0YT8T0
- https://tournesol.app/entities/yt:YMxtImOzyGw
- https://tournesol.app/entities/yt:_Jgbni6UQig
This PR pseudo-randomly selects an offset between 0 and 100 before making a request to the API /recommendations/, increasing the range …
> [front] refactor: increase the range of the suggested videos

- frontend/src/features/banners/WebsiteBanner.tsx
This PR removes the CSS added by the commit https://github.com/tournesol-app/tournesol/commit/84f876a54348b967264b028d45316c73e669865a to fix the banner button displayed outside of its container, instead of inside. 
The main changes are:
- the banner's text is displayed `inline`
- the action button is now floating
| after | before |
|---|---|
| ![capture](https://github.com/tournesol-app/tournesol/assets/39056254/3e0d3066-d3f0-476a-b4bd-259355783611) | ![capture2](https://github.com/tournesol-app/tournesol/assets/39056254/801a0b07-0484-4e5a-ac03-c2d6764eef14) |
> [front] style: fix the CSS of the banner button causing overflow

- backend/tournesol/tests/factories/entity.py
- backend/tournesol/tests/test_api_preview.py
- backend/tournesol/views/previews/recommendations.py
**related issues** #1772
---
This PR fixes the API `/_preview/recommendations/`. Entities without computed Tournesol score will no longer cause the endpoint to fail.
Here is how entities with and without score look like:
| with score | without |
|---|---|
| ![cap2](https://github.com/tournesol-app/tournesol/assets/39056254/335ad355-767c-4933-8a40-85c2c0f269ac) | ![cap](https://github.com/tournesol-app/tournesol/assets/39056254/ab25394d-a541-4bee-94d9-927516f2f60b) |
> [back] fix: recommendations preview for entities without score

- frontend/src/pages/talks/TalkSingleEntry.tsx
"live" is present only when a talk has just started, since less than 2 hours
> [front] fix: `isLive()` value was not correctly computed based on talk date

- frontend/src/features/entity_selector/AutoEntityButton.tsx
- frontend/src/utils/video.ts
**related issues** #1743
---
This PR replaces the usage of video ids by UIDs in the `getUidForComparison` function.
This avoid having unnecessary id to UID and UID to id conversions between the `AutoEntityButton` component and the `getUidForComparison` function.
> [front] refactor: use UIDs instead of video ids in getUidForComparison

- frontend/src/features/recommendation/subset/RecommendationsSubset.tsx
MUI `grid` uses `flex-wrap: "wrap"` by default, which is not suitable when stacking cards in a column. 
> [front] fix: gap between video cards in RecommendationsSubset was inconsistent

- tests/cypress/e2e/frontend/comparisonPage.cy.ts
Tests in "comparisonPage.cy.ts" have been flaky recently. This PR tried to solve this issue by setting the input value in a single event. But Cypress make things a bit more complicated, ans additional ".type()" is required to make sure that React will behave properly once the value has changed.
> [tests] trigger less input events when pasting values in video input

- frontend/public/locales/fr/translation.json
use "non lucratif" instead of "not lucratif"
This PR was created from directly from github
Run `yarn i18n:parse` is probably needed to update the translation catalogs accordingly in public/locales (or maybe it's only needed for a local usage ?)
> [front] fix: typo in association details (fr)

- backend/requirements.txt
Fix:
- CVE-2023-43665
See:
- https://www.djangoproject.com/weblog/2023/oct/04/security-releases/
> [back] sec: upgrade Django to 4.1.12 (from 4.1.11)

- browser-extension/src/manifest.json
- browser-extension/src/utils.js
**related issues** #1779
---
This PR aims to improve the UX of the browser extension, and addresses the issue **(a)** described in this comment https://github.com/tournesol-app/tournesol/issues/1779#issuecomment-1742648000. The other points require more investigation.
The browser alert telling the users to refresh their connection to Tournesol has been deleted. We consider that an outdated access token should be refreshed automatically in the background, without noticing the users. Some cases still trigger the display of the log in iframe: when the refresh token present in the front end is "expired" (automatically deleted in the API database by a scheduled task when its life time exceed 1 week), the users have to log in again. …
> [ext] fix: remove unecessary browser alerts

- browser-extension/src/manifest.json
- browser-extension/src/models/tournesolVideoCard/TournesolVideoCard.js
**related issues** #1806
---
The `TournesolVideoCard` class now uses the new `entity` and `contributor_rating` fields returned by the recommendations API.
It seems to be the good moment to also delete the unused content script `addVideoStatistics.js`, because it seems to use the legacy fields that will be removed from the API.
> [ext] refactor: stop using the legacy fields

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/features/entities/EntityList.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/features/ratings/MarkAllRatings.tsx
- frontend/src/features/ratings/RatingControl.tsx
- frontend/src/features/ratings/RatingsFilter.tsx
- frontend/src/features/videos/PublicStatusAction.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/pages/videos/VideoRatings.tsx
Related to https://github.com/tournesol-app/tournesol/issues/606  
>  Adapt front rate-later page video cards to display the number of comparisons
This also removes the `RatingsContext` now that the rating object is usually accessible in the API response.
> [front] Adapt rate-later page to display RatingControlon (with nb of comparisons) on cards

- backend/tournesol/tests/test_api_subsamples.py
- backend/tournesol/views/subsamples.py
Calling `array_split()` would fail when `len(all_ratings)` is 0
> [back] fix: server error on subsample when user has no rating

- infra/ansible/roles/django/files/gunicorn_proxy.conf
- infra/ansible/roles/django/tasks/main.yml
- infra/ansible/roles/django/templates/tournesol.j2
The "snippets" folder in /etc/nginx is used to refactor the configuration for the API. A snippet is specifically used for blocking IPs on URLs about account registration and password reset.
> [infra] define blocklist for register and password reset in nginx config

- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
- frontend/src/pages/comparisons/Comparison.tsx
In some cases, it could cause several concurrent attempts to create the same `ContributorRating` on the backend.
I also tried to simplify a bit the logic in `ComparisonSeries` by removing the `isLoading` state: the initialization ref is enough.
> [front] fix: avoid multiple initializations of `Comparison` component in `ComparisonSeries`

- dev-env/docker-compose.yml
Fixes #1818 
In #1735 we assumed it was safe to remove references to the obsolete "faq" entry from the migrations. But we forgot about the dev-env database that was created before the migration from "faq" to "backoffice" was finalized. And as the error went unnoticed as the script used to start the  "tournesol-dev-api" container would not block on error :confused:  and the last few migrations related to "backoffice" does not affect the application.
This PR updates the database with recent data, and all migrations applied correctly from scratch, and makes sure that the container will now fail on the first error.
Thanks @sigmike for catching this!
---
[development-guidelines]: https://github.com/tournesol-app/tournesol/blob/main/CONTRIBUTING.md#dev …
> [dev-env] fix: django migrations were partially applied when using the default db

- infra/ansible/roles/django/templates/tournesol.j2
- infra/ansible/roles/nginx/files/maintenance/index.html
The maintenance mode was not defined properly in Nginx configuration: all assets would redirect return a response code 503, causing the browser to not display them.
This PR defines a separate `location /maintenance` section to serve the static page as expected.
> [infra] fix: maintenance page could not load static assets

- dev-env/README.md
- dev-env/run-docker-compose.sh
The `./run-docker-compose.sh restart` command recreated the containers, and that required downloading again all the backend packages.
With these changes (7d4d1b45f2379a6215ae0b77a87334ed82099bd1) the command only restarts the existing containers, and a new command `recreate` does what the previous `restart` did.
I also refactored the code a bit (c06acfcc627062e8bb16f296e5b0f2b254616621 and 801159fec72d60cb5f057bc918c437ba6b919caa).
> [dev-env] feat: stop recreating the containers on restart

- frontend/src/pages/home/videos/sections/research/ScientificLiteratureBox.tsx
When sharing links to our publications, one good way is to share the link to https://tournesol.app/#research. This PR makes it even better by adding the option to share the link https://tournesol.app/#publications. This is motivated by recently wanting to add a link to our publications in a few administrative documents.
> feat: Add id='publications' on publication home page box

- backend/tournesol/lib/suggestions/strategies/base.py
- backend/tournesol/lib/suggestions/strategies/tocompare/classic.py
- backend/tournesol/tests/test_api_suggestions_tocompare.py
- backend/tournesol/views/suggestions/to_compare.py
- backend/vouch/views.py
- frontend/scripts/openapi.yaml
- frontend/src/utils/video.ts
This PR fixes several OpenAPI schema generation errors.
**(1) error related to the API `suggestions/tocompare`**
If found the error when running the command `yarn update-schema`
```
/home/.../tournesol/backend/tournesol/views/suggestions/to_compare.py:
Error [SuggestionsToCompare]: exception raised while getting serializer.
Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'NoneType' object has no attribute 'get_serializer_class')
```
This was caused by the method `get_serializer_class()`. Before, the method was depending on a request object to return the correct serializer. The code has been simplified, and all suggestion strategies of a view should now conform with the  serializer defined by the …
> [back][front] fix: incorrect schema for suggestions/tocompare API

- backend/tournesol/serializers/contributor_recommendations.py
- backend/tournesol/serializers/poll.py
- backend/tournesol/tests/test_api_contributor_recommendations.py
- backend/tournesol/tests/test_api_polls.py
- backend/tournesol/tests/test_text_search.py
Closes #606 
---
Removes the deprecated fields (already excluded from the docs and API schema) in `RecommendationSerializer` and `ContributorRecommendationsSerializer`
> [back] chore: remove deprecated fields from API responses

- backend/tournesol/serializers/rate_later.py
- backend/tournesol/tests/test_api_rate_later.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/scripts/openapi.yaml
- frontend/src/components/entity/EntityCard.tsx
- frontend/src/features/entities/EntityList.tsx
- frontend/src/features/entity_context/EntityCardContextAlert.tsx
- frontend/src/features/entity_context/EntityContextBox.tsx
- frontend/src/pages/rateLater/RateLater.tsx
- frontend/src/pages/videos/VideoAnalysisPage.tsx
**related to** #1852
---
This PR adds entity context notices in the rate-later list and ensures the notices don't appear in the recommendations.
Only unsafe contexts can display the notice for now.
> [front] feat: display unsafe context in rate-later list

- infra/ansible/roles/base/tasks/main.yml
- infra/ansible/roles/nftables/templates/nftables.conf.j2
Following the migration of our virtual machines to a new provider, we observed networking issues post-provisioning. Specifically, the `networking.service` fails to initialize correctly upon reboot, resulting in slow startup and eventual loss of network connectivity.
It seems that the firewall configuration defined in Ansible tasks is blocking packets essential for the networking service to establish the IPv6 connection with DHCPv6. That's why the service times out and fails to start. Notably, this service is also responsible for renewing the IPv4 DHCP lease, leading to server inaccessibility.
This PR introduces a rule to accept connections related to DHCPv6, addressing the networking issue.
Following #1862, it also applies the same `/etc/hosts` configuration in the template used by …
> [infra] fix: update firewall rules to initialize networking properly

- backend/ml/mehestan/run.py
- backend/settings/settings.py
This PR allows to define per server the number of CPU that won't be used by the ML, leaving more resources for other processes. This may improve the performance of SQL queries made by the API during a ML run.
By default 3 CPU will be kept free. Let me know if this number is too high.
|  | CPU | used by ML (before) | used by ML (after) |
|---|---|---|---|
| staging | 2 | 1 | **1** |
| production | 8 | 7 | **6** |
> [back] refactor: set the nbr of CPU not used during the ML run

- browser-extension/package.json
- browser-extension/src/displayHomeRecommendations.js
- browser-extension/src/displaySearchRecommendations.js
This avoid to repeat API requests to fetch banners and recommendations when initializing the extension.
> [ext] fix: avoid repeated calls to initialize Home and Search Recommendations

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/entity/EntityCard.tsx
- frontend/src/components/entity/EntityContextChip.tsx
- frontend/src/components/entity/EntityIndividualScores.tsx
- frontend/src/features/comparisons/Comparison.tsx
**related issues** #1852
---
This PR adds clickable `<Chip />` in the raw entity card, allowing the users to visualise the existence of entity contexts. A click on this new element redirects the users to the entity analysis page.
Note that the API /unconnected_entities/ and /subsamples/ don't return the entity contexts for now. 
> [front] feat: display entity context Chip in the entity selector

- backend/tournesol/serializers/poll.py
- backend/tournesol/tests/test_api_polls_reco_random.py
- backend/tournesol/urls.py
- backend/tournesol/utils/constants.py
- backend/tournesol/views/polls.py
- backend/tournesol/views/polls_reco_random.py
- browser-extension/package.json
- browser-extension/src/background.js
- browser-extension/src/models/tournesolRecommendations/TournesolRecommendations.js
- frontend/scripts/openapi.yaml
This PR adds two features:
**(1)** A new API `polls/{name}/recommendations/random/` that returns random recommendations, designed to be more efficient than the regular recommendations route.
**(2)** The browser extension now uses this new API to improve the loading time of recommendations and their diversity.
**context**
This PR aims to reduce the number of latency alerts triggered by the API recommendations, by providing API clients, such as the browser extension, an alternative and efficient way to request random recommended entities.
Those latency alerts are currently triggered by the browser extension, when fetching the top 250 of all time recommendations to perform a random selection. Thanks to the new API, the extension doesn't need to fetch a big amount of entities to display a …
> [back][ext] feat: recommendations API can now return random entities

- backend/tournesol/views/polls_reco_random.py
The API /recommendations/random/ was triggering one SQL query per entity to retrieve the related criteria scores. This was caused by the field `criteria_scores` of the serializer `ExtendedCollectiveRatingSerializer`.
Now only one request is made to retrieve all criteria scores.
Note that if the extension doesn't use the criteria scores to display the recommendations, we could remove the criteria scores from the request. This will save one SQL query (nevertheless this request seems to be extremely fast on production). 
> [back] fix: API /reco./random/ now prefetches criteria scores

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/features/goals/CollectiveGoalWeeklyProgress.tsx
Two small changes visible on Safari and/or on small screens
|Before|After|
|--|--|
|![IMG_0034](https://github.com/tournesol-app/tournesol/assets/4726554/10711616-8e2b-4b66-8da1-1bd1a105c0c7)|![IMG_0033](https://github.com/tournesol-app/tournesol/assets/4726554/e24b4a95-2c22-4477-9696-6091c278f994)
> [front] fix: video metadata not wrapped correctly in EntityCard on Safari

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/Frame.tsx
- frontend/src/features/frame/components/sidebar/SideBar.tsx
- frontend/src/features/frame/components/topbar/PwaBanner.tsx
- frontend/src/features/frame/components/topbar/TopBar.tsx
- frontend/src/features/frame/pwaPrompt.ts
- frontend/src/theme.ts
…when the browser supports it. 
---
When the event `beforeinstallprompt` is triggered, the item "Install the app" is added to the menu, and a banner invites the user to install the app. Clicking on "Install" will display the native installation prompt (with screenshot + app description).
The event `beforeinstallprompt` is triggered by the browser when the app is ready to be installed (based on the [engagement heuristics](https://web.dev/articles/install-criteria#criteria)  implemented by the browser, typically after some activity on the website when the app is not already installed).
If the banner is closed with the button "Ignore", the current date is stored in local storage and the banner will never appear again (unless we want to update that implementation later). The menu item remains …
> [front] feat: add menu item and banner to trigger pwa installation prompt

- infra/ansible/roles/django/tasks/main.yml
The list of Tor exits can now be updated at least one time per week, every 4 days. 
> [infra] sec: update tor exits more often (4d instead of 30d)

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/components/entity/EntityCardScores.tsx
- frontend/src/components/entity/EntityCardTitle.tsx
- frontend/src/components/entity/EntityMetadata.tsx
- frontend/src/components/entity/style.ts
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/index.css
- frontend/src/pages/home/videos/sections/HomeComparison.tsx
- frontend/src/pages/rateLater/RateLater.tsx
|Before|After|
|-|-|
|![Capture d’écran 2024-02-01 à 15 33 30](https://github.com/tournesol-app/tournesol/assets/4726554/c3d2360f-214e-4961-9e38-5cc20bd303be)|![Capture d’écran 2024-02-01 à 15 34 49](https://github.com/tournesol-app/tournesol/assets/4726554/6c79e7f1-fbf7-4037-b9c3-ca4f2097a0c6)
|![Capture d’écran 2024-02-01 à 15 34 04](https://github.com/tournesol-app/tournesol/assets/4726554/81c80c7a-133a-4ff9-b682-d8943e73b254)|![Capture d’écran 2024-02-01 à 15 35 17](https://github.com/tournesol-app/tournesol/assets/4726554/b5950fc3-5d8e-40d7-87b7-b9c8b2b7da0a)
> [front] fix: ajust entity card style to fix alignment on RateLater and Comparison pages

- frontend/src/features/frame/components/topbar/Search.tsx
- frontend/src/utils/video.spec.ts
- frontend/src/utils/video.ts
Regular strings and "ambiguous" video id redirect the users to the search results. If a string was actually a real YouTube video id, the video will appear in the search result if it is "safe".
- s0KQHmVR40c 
- algorithmes
- horizon-gul
- horizon-gull
- horizon-gulll
Explicit UIDs and URLs redirect the users to the analysis page:
- yt:s0KQHmVR40c
- https://tournesol.app/entities/yt:s0KQHmVR40c
- https://youtu.be/s0KQHmVR40c
- https://youtu.be/s0KQHmVR40c?feature=shared
- https://www.youtube.com/watch?v=s0KQHmVR40c
- https://www.youtube.com/watch?v=s0KQHmVR40c&feature=shared
- etc
> [front] fix: search returning video id when there is no video id

- infra/ansible/roles/django/tasks/main.yml
I found in our logs one registration request that was accepted despite the fact that its ip address should have been blocked by our nginx snippet. I think it's because the nginx daemon is not restarted when the Tor configuration is updated. 
> [infra] fix: nginx is now restarted when block_tor snippet is updated

- browser-extension/package.json
- browser-extension/src/addVideoButtons.js
**related issues** #1904
---
This PR removes the button Watch on Tournesol from the browser extension for anonymous users.
This is/may be a temporary fix. For now, only authenticated users are allowed to add new videos in the database (and use the YouTube API).
See: https://github.com/tournesol-app/tournesol/issues/1904
> [ext] fix: hide Watch on Tournesol button for anonymous users

- browser-extension/package.json
- browser-extension/src/addTournesolRecommendations.css
- browser-extension/src/models/banner/Banner.js
The banner title displayed in the browser extension was bigger than the title displayed in the front end. This PR adds a bit of CSS to harmonize the styles.
|---|---|
| ![capture2](https://github.com/tournesol-app/tournesol/assets/39056254/70cb38f2-6e75-4182-94ad-11be492dce60) | ![capture](https://github.com/tournesol-app/tournesol/assets/39056254/8d8bac30-fb4c-446c-bbbd-a1744e585253) |
> [ext] style: align banner title style with front end style

- frontend/src/components/entity/style.ts
- frontend/src/features/comparisons/ComparisonList.tsx
Fix bug introduced by #1910 causing video cards to have different widths on /comparisons list.
> [front] fix: update entity card flex style to maintain equal size on comparisons list

- browser-extension/prepareExtension.js
- browser-extension/prepareTools.js
- browser-extension/src/.eslintrc.json
- browser-extension/src/background.js
- browser-extension/src/utils.js
**related issues** #1883
---
This PR implements the changes to support manifest V3. The configure and build commands still produce a manifest V2.
You can produce a manifest V3 version for Chrome with:
EXTENSION_BROWSER=chrome node prepareExtension.js
And for Firefox:
EXTENSION_BROWSER=firefox MANIFEST_VERSION=3 node prepareExtension.js
For Firefox it defaults to manifest V2 because of UX and CORS issues, see https://github.com/tournesol-app/tournesol/issues/1883#issuecomment-1916692065.
If we want to release a manifest V3 version for Chrome the remaining task is to update the build scripts, and we may also want to change the `yarn configure` commands.
> [ext] Manifest V3

- browser-extension/src/addVideoButtons.js
This replaces the generic "Done!" confirmation message by "Added!". Especially useful since this message replaces the button text, so even with the "Rate Later" button text gone we can still see what the grayed button was standing for ^^
Before this commit:
After this commit:
Please note that I couldn't find how to update the translation to French (actually, I'm not even sure if a translation to French existed in the first place for those buttons).
> [ext] trans: replace rate later confirmation with "Added!" instead of "Done!"

- frontend/public/manifest.json
- frontend/src/app/PollRoutes.tsx
- frontend/src/pages/feed/FeedCollectiveRecommendations.tsx
- frontend/src/utils/types.ts
- tests/cypress/e2e/frontend/comparisonPage.cy.ts
- tests/cypress/e2e/frontend/feedRecommendationsPage.cy.ts
**related issues** #1895
---
The start page of the PWA is now the collective recommendations.
If the user is logged, his/her preferences are used to initialize the filters. Anonymous users see the recommendations with the default poll filters.
> [front] feat: add the page /feed/recommendations

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/events/EventSingleEntry.tsx
In the events pages, I removed the word "By" automatically added by the front end because it was not appropriate for events like Tournesol Live. Now the back end has a full control how the speakers are introduced.
> [front] fix: remove word "By" to introduce a talk author

- frontend/src/pages/events/GenericEventsPage.tsx
**related issues** #1923
---
The three pages Events, Tournesol Live and Tournesol Talks now display the pagination component.
The limit is set to `20` like in the recommendations page.
> [front] feat: add pagination in all event pages

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/frame/components/footer/Footer.tsx
- frontend/src/utils/url.ts
The section Follow Us now contains a link to the page `/events`.
I also added the missing YouTube link.
|---|---|
| ![capture1](https://github.com/tournesol-app/tournesol/assets/39056254/387a9f0c-109c-47d2-9ec0-b9c099ec4810) | ![capture](https://github.com/tournesol-app/tournesol/assets/39056254/5330f0db-cc4b-4106-80c8-a55b425910a0) |
> [front] feat: add a link to page Events in the footer

- frontend/public/manifest.json
Following #1920, the scope of the PWA was restricted to the new start URL.  
This PR defines an explicit scope, in order to keep the session on Tournesol inside the app.
See https://web.dev/articles/add-manifest#scope
> [front] fix: manifest scope should cover all URLs

- frontend/src/components/entity/EntityCardTitle.tsx
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/entity_selector/AutoEntityButton.tsx
- frontend/src/features/entity_selector/EntitySelectButton.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/pages/home/videos/sections/HomeComparison.tsx
This PR reduces the size of the entity selector on mobile, making it fit on a single line on a larger variety of small screens.
It also removes the Paper surface on top of which the entity cards were displayed. The objective is to delimit the card surface and to mark clear a distinction between the controls and the card itself, so that it will be easier for users to identify the "swipe-able" surface of the card in the future.
The titles A and B have been removed as suggested, to make to simplify the UI.
**to-do**
|---|---|
| ![capture](https://github.com/tournesol-app/tournesol/assets/39056254/d03d8fb2-4f1f-4417-9f65-fc2072802c4a) | ![capture](https://github.com/tournesol-app/tournesol/assets/39056254/05a6ae2f-b04a-4b86-b177-4f9128705090) |
- if not, delete the related …
> [front] ui: smaller entity selector on mobile

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/pages/actions/sections/BeEducated.tsx
- frontend/src/pages/actions/sections/ExposureToQualityInformation.tsx
- frontend/src/pages/actions/sections/Volition.tsx
This PR adds the authors of the books displayed in the section "Increase your exposure to quality information", and add one more book in the section "Be trained" (as discussed with @lenhoanglnh and @aidanjungo).
The authors:
The book from Cathy O'Neil:
> [front] feat: add missing authors + 1 book in /actions

- frontend/src/components/Links.tsx
In video cards, the tooltip on the channel name was broken after introducing `<InternalLink>` custom component.
> [front] fix: forward ref and props on link components to be compatible with MUI Tooltip

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/features/comparisons/Comparison.tsx
The message "Please select 2 items" is redundant with the buttons "select video". Instead a circular loader is displayed if the rating is not ready yet.
> [front] feat: replace message with loader when a video is being loaded during swipe

- frontend/src/features/comparisonSeries/ComparisonSeries.tsx
Can be merged after https://github.com/tournesol-app/tournesol/pull/1930
The container created by the loading wrapper could cause vdeo cards to be resized during swipes.
The loader is not useful anymore as the entity selector can handle the absence of a video by themselves.
> [front] fix: remove loading wrapper on tutorial

- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/entity_selector/EntitySelectButton.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/features/suggestions/uidHistory.spec.ts
- frontend/src/features/suggestions/uidHistory.ts
- frontend/src/hooks/useSuggestions.ts
- frontend/src/pages/home/videos/sections/HomeComparison.tsx
**related issues** #1931 
**target PR** #1954 
---
The entity selectors now suggest new UIDS after a swipe up and after a swipe down.
Before only a swipe up could suggest new entities to compare, making the swipe down only useful to go back in the suggestion history, but useless once the beginning of the history was reached. Now the history is able to append new entries to its "head" and to its "tail", making the navigation more comfortable and never blocking.
> [front] feat: make `UidHistory` able to append entries to both ends

- solidago/src/solidago/__version__.py
- solidago/src/solidago/voting_rights/affine_overtrust.py
- solidago/tests/test_voting_rights.py
The most expensive operation in `AffineOvertrust` is `min_voting_right()`, which computes the minimal voting right to apply in order to reach the overtrust threshold.
The existing implementation was creating a new `pandas.Series` to compute the overtrust on each iteration. Using numpy arrays only is more efficient.
> [solidago] optim: avoid creating Series on every iteration in `AffineOvertrust`

- backend/tournesol/lib/public_dataset.py
- backend/tournesol/management/commands/create_dataset.py
- backend/tournesol/management/commands/load_public_dataset.py
- backend/tournesol/resources/export_readme.txt
- backend/tournesol/tests/management/test_create_dataset.py
- backend/tournesol/tests/test_exports.py
- solidago/src/solidago/pipeline/inputs.py
As discussed in #1879, the vouchers are already described as public information, so it makes sense to include them in the public dataset.
A few other improvements in this PR:
* files are written to the zip file on the fly, without loading the content in memory
* an isolated session is created in the database with the isolation level `repeatable read`, to make sure the public dataset is internally consistent, even if updates happen during its creation.
> [back] feat: add vouchers.csv in public dataset

- backend/core/models/user.py
- backend/tournesol/lib/suggestions/strategies/base.py
- backend/tournesol/lib/suggestions/strategies/tocompare/classic.py
- backend/tournesol/tests/lib/suggestions/test_tocompare_classic.py
- backend/tournesol/tests/test_api_suggestions_tocompare.py
- backend/tournesol/tests/test_utils_http.py
- backend/tournesol/utils/http.py
- backend/tournesol/views/suggestions/to_compare.py
**related issues** #1834 
---
This PR makes the endpoint `/users/me/suggestions/{poll_name}/tocompare/` able to return recommended entities matching the logged user's preferred languages. This should close the milestone _Video selector redesign_.
The preferred languages are determined using the following procedure:
- check the user's settings for the poll
- if the setting hasn't been configured, check the HTTP header `Accept-Language`
- if the languages `en` or `fr` are not present in the preferred languages, add `en`
The fallback language `en` is explicitly hardcoded in the back end. This might not be satisfactory if we want to make the back end generic. This trick ensures new users without entities in their rate-later list will always be suggested entities by the Auto button, even if …
> [back] feat: /tocompare/ API uses the user's preferred languages

- frontend/src/components/entity/EntityCard.tsx
- frontend/src/components/entity/EntityMetadata.tsx
- frontend/src/features/entity_selector/EntitySearchInput.tsx
- frontend/src/features/entity_selector/EntitySelectButton.tsx
- frontend/src/features/entity_selector/EntityTabsBox.tsx
- frontend/src/features/videos/VideoCard.spec.tsx
**related issues** #1875
---
This PR refactors the display of entity metadata to fix some bugs and make them easier to read.
(a) The entity metadata can now be displayed on a single line. The raw entity cards displayed in the tabs of the entity selector use this configuration to fix the bug described in #1875.
(b) In addition to this, to avoid displaying a truncated uploader on small device, the metadata are now displayed in the following order on all devices: uploader, publication date, views (instead of  view, publication date, uploader).
(c) For more clarity, only the uploader is displayed by the component `<RawEntityCard>` on all devices. This affects only the tabs of the entity selector displayed in the comparison page (not the one displayed by the entity analysis page).
(e) Finally, …
> [front] fix: do not truncate individual scores and context chips

- backend/core/serializers/user_settings.py
- backend/core/tests/test_api_user_settings.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/scripts/openapi.yaml
- frontend/src/features/settings/preferences/TournesolUserSettingsForm.tsx
- frontend/src/features/settings/preferences/VideosPollUserSettingsForm.tsx
- frontend/src/pages/comparisons/Comparison.tsx
- frontend/src/utils/constants.tsx
In the branch `main` the weekly collective goal is displayed by default on mobile. This widget takes up a lot of space, and reduce the space available for the sliders and the future comparison buttons. On some devices, the submit button is not visible without scrolling.
The comparison buttons, and the mobile UI in general, would greatly benefit from more space by default, especially when an entity context is displayed. This PR adds a new setting that controls the display of the weekly collective goal on mobile, and set the default value to false (not displayed on mobile devices). This way it's possible for a user to have the widget enabled on desktop, and disabled on mobile.  
It should make the UI more simple and more friendly with new users.
|---|---|
| …
> [back][front] feat: add a setting to control the weekly col. goal on mobile

- .github/workflows/browser-extension-release.yml
- .github/workflows/e2e.yml
- browser-extension/build.sh
- browser-extension/package.json
- browser-extension/prepareExtension.js
Chrome is deprecating Manifest v2.
https://blog.chromium.org/2024/05/manifest-v2-phase-out-begins.html
2 distinct builds will be released:
* a version with manifest v2 for Firefox (unchanged)
* a version with manifest v3 for the Chrome Web Store
The GitHub workflows are updated to write both versions in the artifact, and upload them to Discord.
The e2e tests workflow is also updated to use the Manifest v3 when testing the extension in Chrome.
> [ext] build separate packages for Firefox and Chrome (manifest v3)

- frontend/src/features/settings/preferences/GeneralUserSettingsForm.tsx
- frontend/src/features/settings/preferences/SettingsHeading.tsx
- frontend/src/features/settings/preferences/VideosPollUserSettingsForm.tsx
The sub-sections of the Preferences page are now more distinct. More settings will be added by the future pages For you and Top videos. The new layout should make the settings configuration a bit more user friendly.
It's a first step, I'll probably update the page style after the new settings have been added. 
|---|---|
| ![screencapture-localhost-3000-settings-preferences-2024-06-13-11_13_09](https://github.com/tournesol-app/tournesol/assets/39056254/2d80ded1-c63a-4135-a928-572c600ae364) | ![screencapture-localhost-3000-settings-preferences-2024-06-13-11_12_37](https://github.com/tournesol-app/tournesol/assets/39056254/cbb8d003-0b0d-4247-a347-0b3b8b628702) |
[development-guidelines]: …
> [front] style: make the Preferences page more user friendly

- .github/workflows/browser-extension-release.yml
* Following  #1982, the existing tags were not fetch by ` actions/checkout`. The options `fetch-tags: true` is misleading.   
(See https://github.com/actions/checkout/issues/1471)
* Fix a typo in the command used to send an alert to Discord when the build fails
> [ext] fix: release workflow could not check a release tag already exists

- data-visualization/pages/02_Videos_and_channels.py
- data-visualization/requirements.txt
- data-visualization/utils.py
**related issues** #1867
---
The page "Videos and channels" now retrieves the recommendations from the API `/polls/` instead of the legacy API `/video/`.
Instead of retrieving up to 99999 entities in one single HTTP request, the new method uses a thread pool and several requests to fetch batches of 2000 entities. The new method takes ~ 28 seconds vs ~ 50 seconds for the previous one.
We can tweak several parameters to adapt the server workload:
- lowering the query parameter **limit** will reduce the execution time per request but will increase the total number of requests (and vice versa) 
- lowering the number of **worker threads** will reduce the number of concurrent HTTP requests and increase the loading time of the Streamlit page 
Let me know if you think 2000 is too low or too high. …
> [dataviz] perf: load reco with several HTTP requests

- infra/ansible/roles/grafana_alerting/templates/defaultEvaluationGroup.yaml.j2
The metric defined to trigger the alert is unchanged: 95th percentile of request time, on a 2-minute window.
The difference is on the moment when the alert is triggered:
**Before**: as soon as the average of the metric is above 500ms in the last 20 minutes. (May be triggered immediately if a request is very slow and the traffic is low, especially on staging).
**After**: when the last measure is above 500ms for a pending period of 8 minutes. It should be less sensitive to traffic spike.
> [infra] update alert rule about slow requests with pending period

- data-visualization/pages/03_Community_evolution.py
- data-visualization/requirements.txt
**related issues** #1726
---
Added a new plot in Streamlit, displaying the number of contributors, new users and active users in one line plot.
"Active" users are defined as having done at least one comparison on the week or before, and having done at least one comparison on the week or after.
> [dataviz] feat: add graph Active contributors grouped by age

- browser-extension/package.json
- browser-extension/src/_locales/en/messages.json
- browser-extension/src/_locales/fr/messages.json
- browser-extension/src/addVideoButtons.js
**related issues** #1917 
---
The buttons Rate Now, Rate Later and Watch on Tournesol displayed on the YT video pages are now translated in French (in addition to English). 
> [ext] fix: translate the buttons rate now, rate later and watch

- backend/tournesol/models/comparisons.py
- backend/tournesol/tests/test_model_comparisoncriteriascore.py
The back end doesn't crash anymore when submitting/editing a `ComparisonCriteriaScore` from the admin interface, with a `score_max` less than `score`.
We should not use the admin interface to edit `ComparisonCriteriaScore` but it is useful for testing and debugging.
> [back] fix: validate score and score_max in ComparisonCriteriaScore form

- backend/vouch/tests/test_api_voucher.py
- backend/vouch/views.py
The API responses of the vouch API should now be deterministic, and the related tests should now fail anymore.
> [back] refactor: all responses of the vouchers API are now ordered

- backend/core/locale/fr/LC_MESSAGES/django.po
- backend/tournesol/locale/fr/LC_MESSAGES/django.po
- backend/tournesol/models/comparisons.py
- backend/tournesol/serializers/comparison.py
- backend/tournesol/tests/test_api_comparison.py
- backend/tournesol/tests/test_model_comparisoncriteriascore.py
**related issues** #2001
---
Instead of returning a HTTP 500 error, the API now returns a proper HTTP 400 Bad Request when a user submits a comparison with an invalid `score_max`.
The comparison UI is able to display the error messages from the API, so I translated the messages to make them match the front end UI language. As long as the front end correctly sets the `score_max` of each criterion these messages shouldn't be displayed to the users.   
> [back] fix: API comparisons should return 400 instead of 500

- frontend/src/features/charts/CriteriaScoresDistribution.tsx
As suggested on Discord, the size of the y axis of the score distribution bar chart is now the same for each criterion of a given video. The size is equal to the highest number of ratings among all bins. 
> [front] feat: normalize the size of Y axis of scores distribution

- infra/ansible/roles/django/templates/tournesol.j2
Contrary to http, the default server for https was grafana, causing timeouts on some requests from bots.
> [infra] fix: close connection on https request without host

- dev-env/docker-compose.yml
- frontend/package.json
- frontend/yarn.lock
Fixes https://github.com/tournesol-app/tournesol/security/dependabot/116
Fixes https://github.com/tournesol-app/tournesol/security/dependabot/118
Note that the minimum compatible Node version is now 18.17.
If your dev-env has been initialized a long time ago with an older version of Node, you may need to recreate the frontend container as described [here](https://github.com/tournesol-app/tournesol/tree/main/dev-env#rebuild-the-containers-while-preserving-the-database) with:
```bash
./run-docker-compose.sh recreate
```
> [front] chore: upgrade packages to fix vuln in i18n-parser dependency

- .github/workflows/e2e.yml
E2E tests are failing as ` actions/upload-artifact@v1` is deprecated as explained in
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> fix: update 'actions/upload-artifact' version in e2e test jobs

- frontend/src/app/localStorage.ts
- frontend/src/features/frame/Frame.tsx
- frontend/src/features/frame/components/topbar/PwaBanner.tsx
- frontend/src/hooks/useCurrentPoll.tsx
- frontend/src/hooks/useLastPoll.ts
- frontend/src/utils/comparison/pending.ts
- frontend/src/utils/comparisonSeries/skip.ts
- frontend/src/utils/entityContexts/collapsed.ts
- frontend/src/utils/recommendationsLanguages.ts
This PR introduces "frontend/src/app/localStorage.ts" when the `localStorage` is checked before usage, to handle potential exceptions like `SecurityError` (e.g when "cookies" and other persistent storage is blocked on Firefox).
Fixes #2013 
> [front] fix: check localStorage is available on app load before read/write

- backend/settings/settings.py
The value `DJANGO_LOG_LEVEL` configured on the server was ignored.
After the change,  it's still possible to use the environment variable `DJANGO_LOG_LEVEL`  to override the settings if necessary. The default level is also modified from "DEBUG" to "INFO".
> [back] fix: read default log level from server settings if it's present

- solidago/src/solidago/pipeline/inputs.py
- solidago/tests/test_pipeline.py
This PR relies on the work initiated by @NatNgs in #1994.
The implementation of `get_individual_scores()` is a prerequisite to initialize the scores (with their previous values) when running GBT in the Solidago pipeline.
> [solidago] Keep get_collective_scores() specific to the public dataset, count comparisons lazily

- frontend/public/locales/en/translation.json
- frontend/public/locales/fr/translation.json
- frontend/src/components/ContentHeader.tsx
- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/features/comparisons/ComparisonInput.tsx
- frontend/src/features/comparisons/inputs/CriteriaButtons.tsx
- frontend/src/features/entity_selector/AutoEntityButton.tsx
- frontend/src/features/entity_selector/EntitySelectButton.tsx
- frontend/src/features/entity_selector/EntitySelector.tsx
- frontend/src/index.css
- frontend/src/pages/comparisons/Comparison.tsx
Based on #1968 
After going from the last criterion back to the first on, draw attention on the "next" buttons to go to next comparison.
https://github.com/user-attachments/assets/b649604c-14e5-4e87-bfe5-8c0d97884522
> [front] ui: make 'next' buttons glow after has user has looped through all criteria

- frontend/src/features/comparisons/Comparison.tsx
- frontend/src/index.css
The `onChange` callback was stopping the glow effect for each submitted criterion. Now the effect is stopped only when one of the two UIDs changes. 
> [front] fix: in the comp. ui the glow effect is now triggered properly

- frontend/src/components/buttons/MobileButton.tsx
- frontend/src/components/buttons/MobileIconButton.tsx
- frontend/src/components/buttons/index.ts
- frontend/src/features/comparisons/inputs/CriteriaButtons.tsx
- frontend/src/features/comparisons/inputs/CriterionButtons.tsx
- frontend/src/features/entity_selector/AutoEntityButton.tsx
- frontend/src/features/entity_selector/EntitySelectButton.tsx
Fix background color being abstent after first touch on mobile browsers
> [front] fix: ensure background color is set on hover for mobile buttons

- backend/tournesol/admin.py
- backend/tournesol/locale/fr/LC_MESSAGES/django.po
This PR adds the possibility to filter the `ComparisonCriteriaScore` by `score_max` and `criteria` in the admin interface.
> [back] feat: display the score max in ComparisonCriteriaScore admin

- frontend/src/features/comparisons/inputs/CriteriaButtonsScoreReview.tsx
This PR defines a common height for all displayed criteria icons in the component `<CriteriaButtonsScoreReview>`. The icons should stay aligned regardless of the browser font size.
The height of the criteria icons has been set to match the size of the biggest icon: important & actionable. 
|---|---|
| ![capture0](https://github.com/user-attachments/assets/be2fe49d-b61b-4c62-a4fc-b5d757ea65ec) | ![capture](https://github.com/user-attachments/assets/8a7d1ccf-2c3c-4fb9-8b34-4882098a55dc) |
> [front] style: set a fixed height to criteria icons in CriteriaButtonsScoreReview.tsx

- solidago/experiments/toy.json
This is a minor fix. The toy json that facilitates experimentations and tests had deprecated arguments, which raised errors when loading it.
> Solidago: Fixed toy.json which had deprecated arguments

- frontend/public/manifest.json
**related to** #1892
---
This PR updates the `manifest.json` of the front end to make the PWA ready for Android stores.
Visit https://www.pwabuilder.com/reportcard?site=https://staging.tournesol.app to see the current state of the `manifest.json` of the staging server. 
`categories`
I'm not sure which categories best fit the Tournesol platform. I chose the standard `education`, but on the Google Play Store, this category contains apps to learn mathematics, new languages, how to play music, etc.
I think we could use less common tags, like `['videos', 'science', 'democracy']`.
Here is a standard list of categories maintained by the W3C: https://github.com/w3c/manifest/wiki/Categories
Examples for the Play Store:
https://support.google.com/googleplay/android-developer/answer/9859673?hl=en#zip …
> [front] feat: make the PWA store ready

- frontend/public/.well-known/assetlinks.tournesol.app.json
- infra/ansible/roles/frontend/handlers/main.yml
- infra/ansible/roles/frontend/tasks/main.yml
The file `assetlinks.json` is generated by PWABuilder and allows to link our Android app to our website. It has been manually deployed in production recently, and this PR makes Ansible responsible of its future deployments.
I plan to create an app for our staging environment, and add the required file `assetlinks.staging.tournesol.app.json` in a following pull request.
> [infra] chore: automatically configure assetlinks.json

- frontend/public/manifest.json
We just received our id from the International Age Rating Coalition.
> The International Age Rating Coalition (IARC) is a revolutionary effort administered by the world's leading content rating authorities that globally unifies and streamlines the age classification process for digitally delivered games and apps, ensuring the consistent accessibility of established, trusted rating systems by today's digital consumers.
> [front] chore: set the iarc_rating_id in manifest.json

- backend/twitterbot/settings.py
The latest changes in solidago make it harder for videos to reach score 25, especially on criteria that are evaluated less often by contributors and score uncertainties are high.
As discussed, let's relax the constraint to make more videos available for the bots.
> [back] chore: adjust min reliability score for videos posted by bots

- backend/settings/settings.py
- backend/tournesol/views/rate_later.py
- browser-extension/src/_locales/en/messages.json
- browser-extension/src/_locales/fr/messages.json
- browser-extension/src/rateLaterHistory.css
- browser-extension/src/rateLaterHistory.js
- browser-extension/src/utils.js
**target PR**: #2059
---
- limit the call to the rate-later bulk create API to 20 requests/day
- handle the HTTP 429 status in the extension
- display the number of new videos imported and the number of skipped videos
> [back][ext] feat: add rate limit to the bulk create route of the rate-later API

- browser-extension/src/_locales/en/messages.json
- browser-extension/src/_locales/fr/messages.json
- browser-extension/src/rateLaterHistory.css
- browser-extension/src/rateLaterHistory.js
The history imports made by the browser extension now remembers the YouTube id of imported videos. This allows the users to import new batch of their history daily, without wasting their limited Tournesol API requests by trying to import already imported videos.
To simplify the UI, and to hide the implementation details, the users will see a single number of successfully imported videos, named `imported videos:`. This number was previously split in two distinct labels `new videos` and `already in your list`. A value of 10 means 10 videos from the history are now in your rate later list (some were already present, some are new, but in the end all videos are in the rate-later list).
During the import 👇️
When the Tournesol API returns a HTTP 429 response 👇️
Do we want to allow the users to …
> [ext] feat: keep imported videos in cache to not import them again

- browser-extension/src/background.js
- browser-extension/src/browserAction/menu.js
- browser-extension/src/rateLaterHistory.js
- browser-extension/src/utils.js
Following my comments in #2059 
> [ext] YouTube history import: fix compatibility with Chrome

- backend/settings/settings.py
- backend/tournesol/serializers/rate_later.py
- backend/tournesol/tests/test_api_rate_later.py
- backend/tournesol/urls.py
- backend/tournesol/utils/constants.py
- backend/tournesol/views/rate_later.py
- browser-extension/package.json
- browser-extension/prepareExtension.js
- browser-extension/src/_locales/en/messages.json
- browser-extension/src/_locales/fr/messages.json
- browser-extension/src/background.js
- browser-extension/src/browserAction/menu.html
- browser-extension/src/browserAction/menu.js
- browser-extension/src/rateLaterHistory.css
- browser-extension/src/rateLaterHistory.js
- browser-extension/src/utils.js
- frontend/scripts/openapi.yaml
Initial draft to import your watch history into your rate later list.
The bulk import is not done yet, so the import is very slow, but it works.
Remaining to do:
> Import YouTube history into the rate later list

- frontend/src/utils/video.spec.ts
- frontend/src/utils/video.ts
I think these URLs were supported at some point? Maybe the regex used to be less strict?
> [front] fix extractVideoId for YouTube urls with /v/ or /shorts/

- browser-extension/src/_locales/en/messages.json
- browser-extension/src/_locales/fr/messages.json
- browser-extension/src/background.js
- browser-extension/src/browserAction/menu.js
- browser-extension/src/rateLaterHistory.js
- browser-extension/src/utils.js
Following #2071, a similar issue exists in the browser extension. 
The implementation of `extractVideoId()` is derived from the frontend.
This PR also add translations for errors and messages related to these actions.
> [ext] fix: support URLs for shorts when interacting with video URLs

- browser-extension/package.json
- browser-extension/src/displayHomeRecommendations.js
A small fix, following #2073 .
cc @sigmike @GresilleSiffle 
> [ext] fix: remove unnecessary delay to render recommendations when YouTube history is disabled

- frontend/package.json
- frontend/src/index.css
- frontend/yarn.lock
This branch upgrade the front end package `notistack` to v3, as required by the recent upgrade of Material UI to version 6.
This is still warning when running `yarn install`
> warning "notistack > goober@2.1.16" has unmet peer dependency "csstype@^3.0.10".
It seems to be a problem known since 2023:
- https://github.com/iamhosseindhv/notistack/issues/561
- https://github.com/iamhosseindhv/notistack/pull/562
Nevertheless the package `csstype` is required by other packages, and correctly installed.   
> [front] chore: upgrade notistack to v3

- .github/workflows/browser-extension-ci.yml
- .github/workflows/browser-extension-release.yml
- .github/workflows/e2e.yml
- .github/workflows/frontend-ci.yml
- dev-env/docker-compose.yml
- frontend/README.md
- frontend/i18next-parser.config.js
- infra/ansible/inventory.yml
- tests/README.md
Node.js 18 reached end-of-life on 2025-04-30. It's time to migrate to the most recent LTS.
See https://github.com/nodejs/release?tab=readme-ov-file#release-schedule
No significant change to report.
No compatibility issue detected in dependencies, except a small syntax change in "frontend/i18next-parser.config.js".
> chore: Upgrade Node.js from v18 to v22

- .github/workflows/e2e.yml
- tests/cypress/e2e/browser-extension/extension.cy.ts
- tests/cypress/plugins/index.js
- tests/package.json
- tests/yarn.lock
`chromium`  is used instead of `chrome`  as Google Chrome v137+ no longer supports flag `--load-extension` 
See https://support.google.com/chrome/a/answer/7679408?sjid=1145328871361200805-EU#chromeBrsrE137
> [e2e] fix browser extension tests after chrome removes support for loading extensions from CLI

- infra/ansible/roles/frontend/handlers/main.yml
Adding an extra file in `/home/react/tournesol-frontend/public/` causes the next ansible run to detect changes and to all frontend handlers unnecessarily. This is especially confusing as this extra file typically exists on production only, and shows a different deployment result and notifications between staging and prod.
This PR suggests to create the extra file in "/home/react/tournesol-frontend/build" directly, as this folder is already ignored by the task "Copy React application repository".
> [infra] fix frontend handlers being run unnecessarily during deploy

- backend/tournesol/management/commands/load_public_dataset.py
- dev-env/docker-compose.yml
- dev-env/dump-db.sh
- dev-env/run-docker-compose.sh
- tests/cypress/e2e/frontend/comparisonPage.cy.ts
- tests/cypress/e2e/frontend/feedTopItemsPage.cy.ts
- tests/cypress/e2e/frontend/myRatedVideosPage.cy.ts
- tests/cypress/e2e/frontend/recommendationsPage.cy.ts
- tests/cypress/e2e/frontend/resetPassword.cy.ts
- tests/cypress/e2e/frontend/settingsPreferencesPage.cy.ts
With `./run-docker-compose.sh download --videos-limit 10000` a subset of users will be selected until the limit is reached, to stay below the default quota of YouTube API keys (10000 video metadata requests per day).
A new database image `ghcr.io/tournesol-app/postgres-dev-env:2025-07-10` has been created with this option and is uploaded to the docker registry to be used by default by the dev-env.
@lfaucon There is one caveat with this approach: the numbers of selected users is relatively low (~400 with the current public dataset). The 5 `SEED_USERS` bring more than 8000 videos already.
As a consequence, the most recent videos are compared by a small number of videos and there is no video in the last month reaching the recommendability threshold.
- if not, delete the related issues …
> dev-env: update db content and add option `--videos-limit` to init devenv with a subset of videos

- browser-extension/src/_locales/en/messages.json
- browser-extension/src/_locales/fr/messages.json
- browser-extension/src/addVideoButtons.css
- browser-extension/src/addVideoButtons.js
- browser-extension/src/addVideoStatistics.css
- browser-extension/src/addVideoStatistics.js
- browser-extension/src/background.js
- browser-extension/src/utils.js
**[extension] feat: Add information about the videos in youtube** #1599
---
With this call: `polls/videos/recommendations/?search=${videoId}`. 
I get information about the video (tournesol score and comparaison by contributors). For the front, I move the buttons into a separate container and then create a statistics container.
> [ext] feat: add videos stats on YouTube watch page

- browser-extension/package.json
- browser-extension/src/addTournesolRecommendations.css
- browser-extension/src/addVideoStatistics.js
* The recommendations container could be truncated in some circumstances  
Something I observed after coming back to the homepage with YouTube history disabled.
* Show number of comparisons on watch page, even if the score is not available yet.
> [ext] prepare new release, fix 2 minor bugs

- browser-extension/package.json
- browser-extension/src/addTournesolRecommendations.css
My fix in #2121 caused another bug related to YouTube search suggestions. I should have avoided messing with z-index values :face_with_diagonal_mouth:  
> [ext] fix search suggestions displayed below tournesol container
